      COMMON/BLK5/BETA(4,4),OMEGA(4,4,4),BETX(4,4),IALBY(4,4,4)
     3,OMEGX(4,4,4),ZSIN(4),ZCOS(4),TAU0(JL,JY,JX),TAUS(JL,JY,JX)
     5,FRADT(JY,JX),FRADG(JY,JX),RADG(JY,JX)
     6,THRMCX(JY,JX),ARLFX(JY,JX),ARSTX(JY,JX)
     7,ZT(JY,JX),ZL(0:JC,JY,JX)

