      COMMON/BLKC/DRAD(12),DTMPX(12),DTMPN(12),DHUM(12),DPREC(12)
     2,DIRRI(12),DWIND(12),DCO2E(12),DCN4R(12),DCNOR(12),TDIRI(JY,JX,12)
     3,TDTPX(JY,JX,12),TDTPN(JY,JX,12),TDRAD(JY,JX,12),TDHUM(JY,JX,12)
     4,TDPRC(JY,JX,12),TDWND(JY,JX,12),TDCO2(JY,JX,12),TDCN4(JY,JX,12)
     5,TDCNO(JY,JX,12),TAREA,XCORP(JY,JX),ZERO,ZERO2,ZEROS(JY,JX)
     6,ZEROP(JP,JY,JX),ZEROQ(JP,JY,JX),ZEROP2(JP,JY,JX),ALAT(JY,JX)
     7,DOY,DYLM(JY,JX),ZEROS2(JY,JX),RIX0,RIXF,RIX,RIY,RABM,RABZ 
     8,XNFZ,XNFH,XNPH,XNPT,XNPG,XNPR,XNPS,XNHR,XNPHX,XNPGX,XNPYX 
     9,XNPZX,XNPQX,XNPDX,XNPXX,XNPAX,XNPBX,XNPCX 
     1,IGO,IFLGV(JY,JX),IFLGS(JY,JX),IFNHB(JY,JX),IFNOB(JY,JX) 
     2,IFPOB(JY,JX),IWTHR(2),IDAYR,IYRC,IYRR,NYR,ITERM,IFIN,ISALTG
     3,IERSNG,NCN(JY,JX),ICLM,IMNG,IFLGW
     4,JOUT,IOUT,KOUT,IOLD,ILAST,IRUN,IBEGIN,ISTART,IEND
     5,ICHKF,ISOIL(4,JZ,JY,JX),LYRX,LYRC,LSG(JZ,JY,JX),NP(JY,JX)
     6,NP0(JY,JX),IFLGI(JP,JY,JX),IFLGC(JP,JY,JX),IFLGN(JP,JY,JX) 
     7,IETYP(JY,JX),NPX,NPY,NFH,NPH,NPT,NPG,NPR,NPS 

