      SUBROUTINE starte(NHW,NHE,NVN,NVS)
C
C     THIS SUBROUTINE INITIALIZES ALL SOIL CHEMISTRY VARIABLES
C
      include "parameters.h"
      include "filec.h"
      include "files.h"
      include "blkc.h"
      include "blk2a.h"
      include "blk2b.h"
      include "blk2c.h"
      include "blk8a.h"
      include "blk8b.h"
      include "blk11a.h"
      include "blk11b.h"
      include "blk13a.h"
      include "blk13b.h"
      include "blk13c.h"
      include "blk19a.h"
      include "blk19b.h"
      include "blk19c.h"
      include "blk19d.h"
      CHARACTER*16 DATA(30)
      CHARACTER*3 CHOICE(102,20)
      CHARACTER*8 CDATE
C
C     SC*X=gas solubility coefficients(g m-3/g m-3):CO2=CO2,CH4=CH4, 
C          OXY=O2,N2G=N2g,N2O=N2O,NH3=NH3,H2G=H2
C     AC*X=activity coefficients (g m-3):CO2=CO2,CH4=CH4, 
C          OXY=O2,N2G=N2g,N2O=N2O,NH3=NH3,H2G=H2
C
      PARAMETER (SCO2X=7.391E-01,SCH4X=3.156E-02,SOXYX=2.925E-02
     2,SN2GX=1.510E-02,SN2OX=5.241E-01,SNH3X=2.852E+02,SH2GX=3.156E-02
     3,ACO2X=0.14,ACH4X=0.14,AOXYX=0.31,AN2GX=0.23,AN2OX=0.23
     4,ANH3X=0.07,AH2GX=0.14)
C
C     SOLUBILITY PRODUCTS AND DISSOCIATION CONSTANTS
C     SAME AS THOSE IN SOLUTE.F
C
C     DPH2O=water,SPALO=AlOH3s,SPFEO=FeOH3s,SPCAC=CaCO3s,SPCAS=CaSO4s
C     SPALP=AlPO4s,SPFEP=FePO4s,SPCAM=Ca(H2PO4)2s,SPCAD=CAHPO4s
C     SPCAH=hydroxyapatite,SXOX2=R-OH2,SXOX1=R-OH,SXH2P=R-H2PO4
C     SXH1P=R-HPO4,DPCO2=CO2,DPHCO=HCO3,DPN4=NH4,DPAL1=ALOH
C     DPAL2=ALOH2,DPAL3=AlOH3,DPAL4=ALOH4,DPALS=AlSO4,DPFE1=FeOH
C     DPFE2=FeOH2,DPFE3=FeOH3,DPFE4=FeOH4,DPFES=FeSO4
C     DPCAO=CaOH,DPCAC=CaCO3,DPCAH=CaHCO3,DPCAS=CaSO4
C     DPMGO=MgOH,DPMGC=MgCO3,DPMGH=MgHCO3,DPMGS=MgSO4
C     DPNAC=NaCO3,DPNAS=NaSO4,DPKAS=KSO4,DPH1P=HPO4
C     DPH2P=H2PO4,DPH3P=H3PO4,DPF1P=FeHPO4,DPF2P=FeH2PO4
C     DPC0P=CaPO4,DPC1P=CaHPO4,DPC2P=CaH2PO4
C     DPM1P=MgHPO4,DPCOH=R-COO,COOH=COOH
C
      PARAMETER (DPH2O=1.0E-08,SPALO=1.9E-21,SPFEO=6.3E-26
     2,SPCAC=3.3E-03,SPCAS=1.4E+01,SPALP=9.8E-15,SPFEP=2.5E-19
     3,SPCAM=7.0E+07,SPCAD=1.3E-01,SPCAH=4.0E-31,SXOH2=4.5E-01
     4,SXOH1=8.1E-04,SXH2P=0.5E+06,SXH1P=0.5E+04
     5,DPCO2=4.2E-04,DPHCO=5.6E-08,DPN4=5.5E-07
     6,DPAL1=4.6E-07,DPAL2=7.3E-07,DPAL3=1.8E-05
     7,DPAL4=1.2E-05,DPALS=0.16,DPFE1=2.7E-08,DPFE2=4.5E-07
     8,DPFE3=2.5E-05,DPFE4=1.2E-05,DPFES=7.1E-02,DPCAO=12.5
     9,DPCAC=4.2E-02,DPCAH=13.5,DPCAS=1.2,DPMGO=0.7,DPMGC=0.3
     1,DPMGH=67.0,DPMGS=2.1,DPNAC=0.45,DPNAS=3.3E+02,DPKAS=5.0E+01
     2,DPH1P=4.8E-10,DPH2P=6.2E-05,DPH3P=7.5,DPF1P=4.5E-02
     3,DPF2P=3.7E-03,DPC0P=3.5E-04,DPC1P=1.82,DPC2P=40.0
     4,DPM1P=1.23,DPCOH=1.0E-02,COOH=2.5E+02)
C
C     DISSOCIATION CONSTANTS CALCULATED FROM OTHER CONSTANTS
C
      PARAMETER (DPCO3=DPCO2*DPHCO 
     8,SHCAH1=SPCAH/(DPH2O*DPH1P**3),SHCAH2=SHCAH1/DPH2P**3)
C
C     TPD,TADA,TADC,TSL=rate constants for equilibrating precipitation
C        adsorption (anion,cation),solution reactions (mol t-1)
C     FION*=limits on reaction rates imposed by substrates, products
C        (t-1)
C
      PARAMETER (TPD=1.0E-01,TADA=1.0E-01,TADC=1.0E-01,TSL=1.0E-01
     2,FION=0.1,FIONS=FION*1.0,ZEROC=1.0E-48
     3,MRXN=10000)
C
C     INITIALIZE CATION AND ANION CONCENTRATIONS
C     IN PRECIPITATION (K=1), IRRIGATION (K=2) AND SOIL (K=3)
C     FROM WEATHER, IRRIGATION AND SOIL FILES IN 'READS'
C
C     CCO2E,CCH4E,COXYE,ZZ2GE,CZ2OE=atmospheric CO2,CH4,N2,N2O
C        concentrations (g m-3)
C
      DO 9995 NX=NHW,NHE
      DO 9990 NY=NVN,NVS
      CCO2M=CCO2EI(NY,NX)/12.0
      CCH4M=CCH4E(NY,NX)/12.0
      COXYM=COXYE(NY,NX)/32.0
      CZ2GM=CZ2GE(NY,NX)/14.0
      CZ2OM=CZ2OE(NY,NX)/14.0
      DO 1200 I=1,366
      DO 1200 L=NU(NY,NX),NL(NY,NX)
      DO 2000 K=1,3
C
C     INITIALIZE IONS IN RAINFALL (K=1)
C
C     PHR,CN4R,CNOR,CPOR,CALR,CFER,CCAR,CMGR,CNAR,CKAR, 
C        CSOR,CCLR=pH,NH4,NO3,H2PO4,Al,Fe,Ca,Mg,Na,K,SO4,Cl 
C        concentration in precipitation from weather file (g,mol m-3)
C
      IF(K.EQ.1.AND.I.EQ.1.AND.L.EQ.1)THEN
      PH1=PHR(NY,NX)
      CHY1=10.0**(-(PHR(NY,NX)-3.0))
      COH1=DPH2O/CHY1
      CN4Z=CN4R(NY,NX)/14.0
      CNOZ=CNOR(NY,NX)/14.0
      CPOZ=CPOR(NY,NX)/31.0
      CALZ=CALR(NY,NX)
      CFEZ=CFER(NY,NX)
      CCAZ=CCAR(NY,NX)
      CMGZ=CMGR(NY,NX)
      CNAZ=CNAR(NY,NX)
      CKAZ=CKAR(NY,NX)
      CSOZ=CSOR(NY,NX)
      CCLZ=CCLR(NY,NX)
C
C     INITIALIZE IRRIGATION WATER (K=2)
C
C     PHI,CN4Q,CNOQ,CPOQ,CALQ,CFEQ,CCAQ,CMGQ,CNAQ,CKAQ, 
C        CSOQ,CCLQ=pH,NH4,NO3,H2PO4,Al,Fe,Ca,Mg,Na,K,SO4,Cl 
C        concentration in irrigation from irrigation file (g,mol m-3)
C
      ELSEIF(K.EQ.2.AND.L.EQ.1)THEN
      PH1=PHQ(I,NY,NX)
      CHY1=10.0**(-(PHQ(I,NY,NX)-3.0))
      COH1=DPH2O/CHY1
      CN4Z=CN4Q(I,NY,NX)/14.0
      CNOZ=CNOQ(I,NY,NX)/14.0
      CPOZ=CPOQ(I,NY,NX)/31.0
      CALZ=CALQ(I,NY,NX)
      CFEZ=CFEQ(I,NY,NX)
      CCAZ=CCAQ(I,NY,NX)
      CMGZ=CMGQ(I,NY,NX)
      CNAZ=CNAQ(I,NY,NX)
      CKAZ=CKAQ(I,NY,NX)
      CSOZ=CSOQ(I,NY,NX)
      CCLZ=CCLQ(I,NY,NX)
C
C     INITIALIZE IONS IN SOIL WATER N (K=3)
C
C     C*=soluble concentration from sat. paste extract in soil file 
C        NH4,NO3,PO4=NH4-N,NO3-N,H2PO4-P (mol Mg-1)
C        AL,FE,CA,MG,NA,KA,SO4,CL=Al,Fe,Ca,Mg,Na,K,SO4-S,Cl (mol Mg-1)
C     CALPO,CFEPO,CCAPD,CCAPH=AlPO4,FePO4,CaHPO4,apatite from soil file
C        (mol Mg-1)
C     CALOH,CFEOH,CCACO,CCASO=AlOH3,FeOH3,CaSO4,CaCO3 from soil file 
C        (mol Mg-1)
C     BKVL,VOLA,VOLW=soil mass (Mg),porosity (m3),water content (m3)
C     XCEC,XAEC=cation,anion exchange capacity (mol)
C     PH=soil pH from soil file
C
      ELSEIF(K.EQ.3.AND.I.EQ.1)THEN
      IF(BKVL(L,NY,NX).GT.ZEROS(NY,NX))THEN
      BKVLX=BKVL(L,NY,NX)
      ELSE
      BKVLX=VOLA(L,NY,NX)
      ENDIF
      IF(VOLW(L,NY,NX).GT.ZEROS(NY,NX))THEN
      BKVLW=AMIN1(1.0,BKVLX/VOLW(L,NY,NX))
      ELSE
      BKVLW=1.0
      ENDIF
      CN4X=0.1*CNH4(L,NY,NX)
      CNOX=CNO3(L,NY,NX) 
      CPOX=0.01*CPO4(L,NY,NX)
      CALX=CAL(L,NY,NX)
      CFEX=CFE(L,NY,NX)
      CCAX=CCA(L,NY,NX)
      CMGX=CMG(L,NY,NX)
      CNAX=CNA(L,NY,NX)
      CKAX=CKA(L,NY,NX)
      CSOX=CSO4(L,NY,NX)
      CCLX=CCL(L,NY,NX)
      CALPOX=CALPO(L,NY,NX)
      CFEPOX=CFEPO(L,NY,NX)
      CCAPDX=CCAPD(L,NY,NX)
      CCAPHX=CCAPH(L,NY,NX)
      CALOHX=CALOH(L,NY,NX)
      CFEOHX=CFEOH(L,NY,NX)
      CCACOX=CCACO(L,NY,NX)
      CCASOX=CCASO(L,NY,NX)
      XCEC(L,NY,NX)=CEC(L,NY,NX)*BKVLX
      XAEC(L,NY,NX)=AEC(L,NY,NX)*BKVLX
      CHY1=10.0**(-(PH(L,NY,NX)-3.0))
      COH1=DPH2O/CHY1
      CN4Z=CN4X
      CNOZ=CNOX
      CPOZ=CPOX
      CALZ=CALX
      CFEZ=CFEX
      CCAZ=CCAX
      CMGZ=CMGX
      CNAZ=CNAX
      CKAZ=CKAX
      CSOZ=CSOX
      CCLZ=CCLX
      ELSE
      GO TO 2000
      ENDIF
C
C     INITIALIZE SOIL GAS CONCENTRATIONS FROM SOLUBILITY COEFFICIENTS
C
C     ATCA=mean annual air temperature (oC) from site file
C     C*M=atmospheric gas concentration (mol m-3)
C     C*1=soil aqueous gas concentration (mol m-3)
C     S*X=gas solubility (mol m-3 / (mol m-3))
C
      IF(K.NE.3.OR.ISALTG.EQ.0)THEN
      CCO21=CCO2M*SCO2X/EXP(ACO2X)
     2*EXP(0.843-0.0281*ATCA(NY,NX))
      ELSE
      CCO21=1.0E+02*CCO2M*SCO2X/EXP(ACO2X)
     2*EXP(0.843-0.0281*ATCA(NY,NX))
      ENDIF
      CCO31=CCO21*DPCO3/CHY1**2
      CHCO31=CCO21*DPCO2/CHY1
      CCH41=CCH4M*SCH4X/EXP(ACH4X)
     2*EXP(0.597-0.0199*ATCA(NY,NX))
      COXY1=COXYM*SOXYX/EXP(AOXYX)
     2*EXP(0.516-0.0172*ATCA(NY,NX))
      CZ2G1=CZ2GM*SN2GX/EXP(AN2GX)
     2*EXP(0.456-0.0152*ATCA(NY,NX))
      CZ2O1=CZ2OM*SN2OX/EXP(AN2OX)
     2*EXP(0.897-0.0299*ATCA(NY,NX))
C
C     INITIALIZE ION PAIR EQUILIBRIA FROM DISSOCIATION CONSTANTS
C
C     C*1=solute concentration (mol m-3)
C     DP*=dissociation constant from PARAMETER above
C     SP*=solubility product from PARAMETER above 
C
      IF(K.NE.3)THEN
      CN41=CN4Z/(1.0+DPN4/CHY1)
      CN31=CN41*DPN4/CHY1
      ELSE
      CN41=CN4Z*0.10
      CN31=0.0
      ENDIF
      IF(CALZ.LT.0.0)THEN
      CAL1=SPALO/COH1**3
      ELSE
      CAL1=AMIN1(CALZ,SPALO/COH1**3)
      ENDIF
      IF(CFEZ.LT.0.0)THEN
      CFE1=SPFEO/COH1**3
      ELSE
      CFE1=AMIN1(CFEZ,SPFEO/COH1**3)
      ENDIF
      IF(K.LE.2)THEN
      CCA1=CCAZ
      ELSE
      CCA1=AMIN1(CCAZ,SPCAC/CCO31) 
      ENDIF
      CN41=AMAX1(ZEROC,CN41)
      CN31=AMAX1(ZEROC,CN31)
      CNO1=AMAX1(ZEROC,CNOZ)
      CPO1=AMAX1(ZEROC,CPOZ)
      CAL1=AMAX1(ZEROC,CAL1)
      CFE1=AMAX1(ZEROC,CFE1)
      CCA1=AMAX1(ZEROC,CCA1)
      CMG1=AMAX1(ZEROC,CMGZ)
      CNA1=AMAX1(ZEROC,CNAZ)
      CKA1=AMAX1(ZEROC,CKAZ)
      CSO41=AMAX1(ZEROC,CSOZ)
      CCL1=AMAX1(ZEROC,CCLZ)
      CALO1=CAL1*COH1/DPAL1
      CALO2=CAL1*COH1**2/(DPAL1*DPAL2)
      CALO3=CAL1*COH1**3/(DPAL1*DPAL2*DPAL3)
      CALO4=CAL1*COH1**4/(DPAL1*DPAL2*DPAL3*DPAL4)
      CALS1=0.0
      CFEO1=CFE1*COH1/DPFE1
      CFEO2=CFE1*COH1**2/(DPFE1*DPFE2)
      CFEO3=CFE1*COH1**3/(DPFE1*DPFE2*DPFE3)
      CFEO4=CFE1*COH1**4/(DPFE1*DPFE2*DPFE3*DPFE4)
      CFES1=0.0
      CCAO1=CCA1*COH1/DPCAO
      CCAC1=CCA1*CCO31**2/DPCAC
      CCAH1=CCA1*CHCO31/DPCAH
      CCAS1=0.0
      CMGO1=CMG1*COH1/DPMGO
      CMGC1=CMG1*CCO31**2/DPMGC
      CMGH1=CMG1*CHCO31/DPMGH
      CMGS1=0.0
      CNAC1=CNA1*CCO31/DPNAC
      CNAS1=0.0
      CKAS1=0.0
      CF1P1=0.0
      CF2P1=0.0
      CC0P1=0.0
      CC1P1=0.0
      CC2P1=0.0
      CM1P1=0.0
C
C     INITIALIZE PHOSPHORUS EQUILIBRIA AMONG SOLUBLE, ADSORBED
C     AND PRECIPITATED FORMS FROM SOULUBILITY PRODUCTS
C
C     C*1=solute P concentration (mol m-3)
C     DP*=dissociation constant from PARAMETER above
C     SP*=solubility product from PARAMETER above 
C     X*=exchangeable P concentration (mol Mg-1)
C     XAEC=anion exchange capacity (mol)
C
      IF(K.NE.3)THEN
      CH3P1=CPO1/(1.0+DPH3P/CHY1+DPH3P*DPH2P
     2/(CHY1**2)+DPH3P*DPH2P*DPH1P/CHY1**3)
      CH2P1=CH3P1*DPH3P/CHY1
      CH1P1=CH3P1*DPH3P*DPH2P/CHY1**2
      CH0P1=CH3P1*DPH3P*DPH2P*DPH1P/CHY1**3
      ELSE
      XHP=CPO1 
      XOH=XAEC(L,NY,NX)/BKVLX
      FHP3=1.0/(1.0+DPH3P/CHY1+DPH3P*DPH2P
     2/CHY1**2+DPH3P*DPH2P*DPH1P/CHY1**3)
      FHP2=FHP3*DPH3P/CHY1
      FHP1=FHP3*DPH3P*DPH2P/CHY1**2
      FHP0=FHP3*DPH3P*DPH2P*DPH1P/CHY1**3
      SPOH2=SXOH2
      SPOH1=SXOH1
      SPH2P=SXH2P*DPH2O
      SPH1P=SXH1P*DPH2O
      FXH2=1.0/(1.0+SPOH2/CHY1+SPOH2*SPOH1/CHY1**2)
      FXH1=FXH2*SPOH2/CHY1
      FXH0=FXH1*SPOH1/CHY1
      FXP2=1.0/(1.0+SXH2P*DPH2P/(SXH1P*CHY1))
      FXP1=FXP2*SXH2P*DPH2P/(SXH1P*CHY1)
      FHPA=FHP2
      XPT=AMIN1(XOH,CPO4(L,NY,NX))
      XOH21=(XOH-XPT)*FXH2
      XOH11=(XOH-XPT)*FXH1
      XOH01=(XOH-XPT)*FXH0
      XH1P1=XPT*FXP1
      XH2P1=XPT*FXP2
      CH3P1=XHP*FHP3
      CH2P1=XHP*FHP2
      CH1P1=XHP*FHP1
      CH0P1=XHP*FHP0
      ENDIF
C     IF(K.EQ.3)THEN
C     WRITE(*,1109)'STARTE',I,L,K 
C    2,XH1P1,XH2P1,XOH01,XOH11,XOH21
C    3,XH1P1+XH2P1+XOH01+XOH11+XOH21
C    4,XH1P1/BKVL(L,NY,NX),XH2P1/BKVL(L,NY,NX)
C    4,XOH,XHP,XPT,FXP1,FXP2,XAEC(L,NY,NX),BKVLX,CPO4(L,NY,NX)
C    5,CH0P1,CH1P1,CH2P1,CH3P1
1109  FORMAT(A8,3I4,30E12.4)
C     ENDIF
C
C     INITIALIZE EQUILIBRIA BETWEEN SOLUBLE AND PRECIPITATED FORMS
C
C     P*1=precipitated Al(OH)3, Fe(OH)3, CaCO3, CaSO4, AlPO4, FePO4, 
C        Ca(H2PO4)2, CaHPO4, apatite from soil file (mol(Mg-1) 
C     VLPO4,VLPOB=fraction of soil volume in non-band,band P zones
C
      IF(K.EQ.3)THEN
      PALOH1=CALOHX
      PFEOH1=CFEOHX
      PCACO1=CCACOX
      PCASO1=CCASOX
      PALPO1=CALPOX
      PFEPO1=CFEPOX
      PCAPD1=CCAPDX
      PCAPH1=CCAPHX
C
C     INITIALIZE CATION EQILIBRIA BETWEEN SOLUBLE
C     AND EXCHANGEABLE FORMS
C
C     CCEC=cation exchange capacity (mol Mg-1)
C     XCEC=cation exchange capacity from soil file (mol)
C     BKVLx=soil mass (Mg)
C     ORGC=SOC (g Mg-1) from soil file
C     XCOOH,XHC1=total carboxyl exchange sites,occupied by H+ (mol)
C     ORGC=SOC (g)
C
C     IF(BKVL(L,NY,NX).GT.ZEROS(NY,NX))THEN
C     BKVLX=BKVL(L,NY,NX)
C     ELSE
C     BKVLX=VOLW(L,NY,NX)
C     ENDIF
      CCEC=XCEC(L,NY,NX)/BKVLX
      XCECQ=CEC(L,NY,NX)
      XCOOH=AMAX1(ZEROC,COOH*1.0E-06*ORGC(L,NY,NX)/BKVLX)
      XHC1=XCOOH*AMIN1(1.0,CHY1/DPCOH) 
      ENDIF
C
C     CONVERGE TOWARDS ALL SOLUBILITY EQUILIBRIA
C
      DO 1000 M=1,MRXN
C
C     ION ACTIVITY COEFFICIENTS
C
C     CC*,CA*=total cation,anion concentration (mol m-3)
C     CSTR*=ion strengths
C     A*S=ion activity coefficients
C     SP*,SH*=solubility product from PARAMETER above 
C     R*,P*=reactants, products of solubility reactions
C
      CC3=CAL1+CFE1
      CA3=CH0P1
      CC2=CCA1+CMG1+CALO1+CFEO1+CF2P1
      CA2=CSO41+CCO31+CH1P1
      CC1=CN41+CHY1+CNA1+CKA1+CALO2+CFEO2+CALS1+CFES1+CCAO1
     2+CCAH1+CMGO1+CMGH1+CF1P1+CC2P1
      CA1=CNO1+COH1+CHCO31+CCL1+CALO4+CFEO4+CNAC1+CNAS1+CKAS1
     2+CH2P1+CC0P1
      CSTR1=0.5E-03*(9.0*(CC3+CA3)+4.0*(CC2+CA2)+CC1+CA1)
      CSTRQ=SQRT(CSTR1)
      CSTRX=CSTRQ/(1.0+CSTRQ)-0.20*CSTR1
      A1S=AMIN1(1.0,10.0**(-0.509*1.0*CSTRX))
      A2S=AMIN1(1.0,10.0**(-0.509*4.0*CSTRX))
      A3S=AMIN1(1.0,10.0**(-0.509*9.0*CSTRX))
C
C     PRECIPITATION-DISSOLUTION EQUILIBRIA FROM SOLUBILITY PRODUCTS
C
C     A*1=ion activity (mol m-3)
C     C*1=ion concentration (mol m-3)
C     A*S=ion activity coefficients
C
      AHY1=10.0**(-(PH(L,NY,NX)-3.0))
      AOH1=DPH2O/AHY1
      AAL1=CAL1*A3S
      AALO1=CALO1*A2S
      AALO2=CALO2*A1S
      AALO3=CALO3
      AALO4=CALO4*A1S
      AFE1=CFE1*A3S
      AFEO1=CFEO1*A2S
      AFEO2=CFEO2*A1S
      AFEO3=CFEO3
      AFEO4=CFEO4*A1S
      ACA1=CCA1*A2S
      ACO31=CCO31*A2S
      AHCO31=CHCO31*A1S
      ACO21=CCO21
      ASO41=CSO41*A2S
      AH0P1=CH0P1*A3S
      AH1P1=CH1P1*A2S
      AH2P1=CH2P1*A1S
      AH3P1=CH3P1
      AF1P1=CF1P1*A2S
      AF2P1=CF2P1*A1S
      AC0P1=CC0P1*A1S
      AC1P1=CC1P1
      AC2P1=CC2P1*A1S
      AM1P1=CM1P1
      AN41=CN41*A1S
      AN31=CN31
      AMG1=CMG1*A2S
      ANA1=CNA1*A1S
      AKA1=CKA1*A1S
      AALS1=CALS1*A1S
      AFES1=CFES1*A1S
      ACAO1=CCAO1*A1S
      ACAC1=CCAC1
      ACAS1=CCAS1
      ACAH1=CCAH1*A1S
      AMGO1=CMGO1*A1S
      AMGC1=CMGC1
      AMGH1=CMGH1*A1S
      AMGS1=CMGS1
      ANAC1=CNAC1*A1S
      ANAS1=CNAS1*A1S
      AKAS1=CKAS1*A1S
C
C     PRECIPITATION-DISSOLUTION REACTIONS
C
C     XMINP,XMINN=limits on reaction rates imposed by substrate,
C        product activities (mol t-1)
C     FION*=limits on reaction rates imposed by substrate, product
C        activities (t-1)
C     SP*=solubility product from PARAMETER above 
C     TPD=rate constant for equilibrating precipitation reactions 
C        (mol t-1)
C     RP*=precipitation (+ve), dissolution (-ve) rate (mol t-1)
C     A*1,A*1Q=current,equilibrium ion activity (mol m-3)
C     P*1=precipitate concentration (mol Mg-1)
C     ISALTG:0=salt concentrations entered in soil file generate
C              equilibrium concentrations that remain static during
C              model run
C           :1=salt equilibrium concentrations are solved
C              dynamically in ‘solute.f’ and transported in ‘trnsfrs.f’ 
C
      IF(K.EQ.3)THEN
C
C     ALUMINUM HYDROXIDE (GIBBSITE)
C
      XMINP=FION*AAL1
      AAL1Q=SPALO/AOH1**3
      RPALOX=AMAX1(-AMAX1(0.0,PALOH1),-TPD 
     2,(AMIN1(TPD,XMINP,AAL1-AAL1Q)))
C     IF(M.EQ.1.OR.(M/250)*250.EQ.M)THEN 
C     WRITE(*,1112)'ALOH3I',I,L,K,M 
C    2,RPALOX,AAL1,AAL1Q,AOH1,A1S 
C    3,AAL1*AOH1**3,SPALO,XMINP,TPD,PH(L,NY,NX)
C     ENDIF
C
C     IRON HYDROXIDE
C
      AFE1Q=SPFEO/AOH1**3
      RPFEOX=AMAX1(-AMAX1(0.0,PFEOH1),-TPD 
     2,(AMIN1(TPD,XMINP,AFE1-AFE1Q)))
C     IF(M.EQ.1.OR.(M/250)*250.EQ.M)THEN 
C     WRITE(*,1112)'FEOH3I',I,L,K,M 
C    2,RPFEOX,AFE1,AFE1Q,AOH1,A1S 
C    3,AFE1*AOH1**3,SPFEO,XMINP,TPD,PH(L,NY,NX)
C     ENDIF
C
C     CALCITE
C
      IF(ISALTG.NE.0)THEN
      XMINP=FION*AMIN1(ACA1,ACO31)
      ACA1Q=SPCAC/ACO31
      RPCACX=AMAX1(-AMAX1(0.0,PCACO1),-TPD 
     2,(AMIN1(TPD,XMINP,ACA1-ACA1Q)))
C     IF(K.EQ.3.AND.(M.LE.10.OR.INT(M/100)*100.EQ.M)
C    2.AND.L.LE.13)THEN
C     WRITE(*,1112)'CALCI',I,L,K,M
C    2,RPCACX,ACA1,ACA1Q,ACO31,AHCO31,ACO21,AHY1,SPCAC 
C    3,ACA1*ACO31,CCA(L,NY,NX),PCACO1,XMINP,PH(L,NY,NX)
C     ENDIF
C
C     GYPSUM
C
      XMINP=FION*AMIN1(ACA1,ASO41)
      ACA1Q=SPCAS/ASO41
      RPCASO=AMAX1(-AMAX1(0.0,PCASO1),-TPD 
     2,(AMIN1(TPD,XMINP,ACA1-ACA1Q)))
C     IF(K.EQ.3.AND.(M.LE.10.OR.INT(M/100)*100.EQ.M).AND.L.EQ.1)THEN
C     WRITE(*,1112)'GYPS',I,L,K,M,PCASO1,RPCASO,ACA1,ASO41
C    3,ACA1*ASO41,SPCAS
C     ENDIF
      ELSE
      RPCACX=0.0
      RPCASO=0.0
      ENDIF
C
C     PHOSPHORUS PRECIPITATION-DISSOLUTION IN NON-BAND SOIL ZONE
C
C     ALUMINUM PHOSPHATE (VARISCITE)
C
C     IF(AAL1.GT.ZEROC)THEN
      XMINN=FION*AH2P1
      XMINP=FION*AMIN1(AAL1,AH2P1)
      AAL1Q=SPALP/AH0P1
      RPALPX=AMAX1(-AMAX1(0.0,PALPO1),-TPD 
     2,(AMIN1(TPD,XMINP,AAL1-AAL1Q)))
C     ELSE
C     RPALPX=0.0
C     ENDIF
C     IF(K.EQ.3.AND.(M/250)*250.EQ.M)THEN 
C     WRITE(*,1112)'RPALPX',I,L,K,M 
C    2,RPALPX,AAL1,AAL1Q
C    2,AH0P1,AH1P1,AH2P1,AHY1,AOH1,AAL1*AH0P1,SPALP,TPD,XMINN,XMINP 
1112  FORMAT(A8,3I4,1I6,60E12.4)
C     ENDIF
C
C     IRON PHOSPHATE (STRENGITE)
C
C     IF(AFE1.GT.ZEROC)THEN
      XMINN=FION*AH2P1
      XMINP=FION*AMIN1(AFE1,AH2P1)
      AFE1Q=SPFEP/AH0P1
      RPFEPX=AMAX1(-AMAX1(0.0,PFEPO1),-TPD 
     2,(AMIN1(TPD,XMINP,AFE1-AFE1Q)))
C     ELSE
C     RPFEPX=0.0
C     ENDIF
C     IF(K.EQ.3.AND.(M/250)*250.EQ.M)THEN 
C     WRITE(*,1112)'RPFEPX',I,L,K,M 
C    2,RPFEPX,AFE1,AFE1Q 
C    2,AH0P1,AH1P1,AH2P1,AHY1,AOH1,AFE1*AH0P1,SPFEP,XMINN,XMINP 
C     ENDIF
C
C     DICALCIUM PHOSPHATE
C
C     IF(ACA1.GT.ZEROC)THEN
      XMINN=FION*AH2P1
      XMINP=FION*AMIN1(ACA1,AH2P1)
      ACA1Q=SPCAD/AH1P1 
      RPCADX=AMAX1(-AMAX1(0.0,PCAPD1),-TPD 
     2,(AMIN1(TPD,XMINP,ACA1-ACA1Q)))
C     ELSE
C     RPCADX=0.0
C     ENDIF
C     IF((M/10)*10.EQ.M)THEN
C     WRITE(*,1112)'CAPO4',I,L,K,M,PCAPM1,PCAPD1,CCA1
C    2,CH1P1,CH2P1,CHY1,COH1,RPCADX,RPCAD1,RHCAD2,R1,P1,P2,P3
C    3,SP,Z,FX,Y,X,TX,A2,CCA1*A2S*CH1P1*A2S,SPCAD
C     ENDIF
C
C     HYDROXYAPATITE
C
C     IF(ACA1.GT.ZEROC)THEN
      XMINN=FION*AH2P1
      XMINP=FION*AMIN1(ACA1,AH2P1)
      ACA1Q=(SPCAH/(AH0P1**3*AOH1))**0.2
      RPCAHX=AMAX1(-AMAX1(0.0,PCAPH1),-TPD 
     2,(AMIN1(TPD,XMINP,ACA1-ACA1Q)))
C     ELSE
C     RPCAHX=0.0
C     ENDIF
C
C     RECALCULATE PRECIPITATES
C
C     PALOH1=PALOH1+RPALOX
C     PFEOH1=PFEOH1+RPFEOX
C     PCACO1=PCACO1+RPCACX
C     PCASO1=PCASO1+RPCASO
      PALPO1=PALPO1+RPALPX
      PFEPO1=PFEPO1+RPFEPX
      PCAPD1=PCAPD1+RPCADX
      PCAPH1=PCAPH1+RPCAHX
C
C     ANION EXCHANGE EQUILIBRIA
C
C     XAEC=anion exchange capacity (mol-)
C     XMINP,XMINN=limits on reaction rates imposed by substrates,
C        products (mol t-1)
C     XOH21,XOH11,XOH01=exchange OH2,OH,O- sites(mol Mg-1)
C     XOH2Q,XOH1Q,XOH0Q=equilibrium exchange OH2,OH,O- sites(mol Mg-1)
C     SXOH2,SXOH1=equilibrium constants for OH- exchange among 
C        XOH21,XOH11,XOH01 sites
C     RXOH2,RXOH1=OH2,OH exchange among XOH21,XOH11,XOH01 sites 
C        (mol t-1)
C     RXH2P,RYH2P=H2PO4 adsorption (+ve), desorption 
C        (-ve)(mol t-1)
C     RXH1P=HPO4 adsorption (+ve), desorption 
C        (-ve)(mol t-1) 
C     XH2P,XH1P=exchangeable H2PO4,HPO4 (mol Mg-1)
C     SP*=solubility product from PARAMETER above 
C     TADA=adsorption rate constant (mol t-1)
C     AHY1=H+ activity (mol m-3)
C
C     OH- EXCHANGE
C
      IF(XAEC(L,NY,NX).GT.ZEROS(NY,NX))THEN
      XMINN=FION*XOH21
      XMINP=FION*AMIN1(AHY1,XOH11)
      XOH1Q=SXOH2*XOH21/AHY1
      RXOH2=AMAX1(-TADA,-XMINN
     2,(AMIN1(TADA,XMINP,XOH11-XOH1Q)))
      XMINN=FION*XOH11
      XMINP=FION*AMIN1(AHY1,XOH01)
      XOH0Q=SXOH1*XOH11/AHY1
      RXOH1=AMAX1(-TADA,-XMINN
     2,(AMIN1(TADA,XMINP,XOH01-XOH0Q)))
C
C     H2PO4 EXCHANGE
C
      XMINN2=FION*XH2P1 
      XMINP2=FION*AMIN1(AH2P1,XOH21) 
      SPH2P=SXH2P*AHY1*AOH1 
      AH2PQ2=SPH2P*XH2P1/XOH21
      RXH2P=AMAX1(-TADA,-XMINN2
     2,(AMIN1(TADA,XMINP2,AH2P1-AH2PQ2)))
      XMINN1=FION*XH2P1 
      XMINP1=FION*AMIN1(AH2P1,XOH11) 
      SYH2P=SXH2P*AOH1
      AH2PQ1=SYH2P*XH2P1/XOH11
      RYH2P=AMAX1(-TADA,-XMINN1
     2,(AMIN1(TADA,XMINP1,AH2P1-AH2PQ1)))
C
C     HPO4 EXCHANGE
C
      XMINN=FION*XH1P1
      XMINP=FION*AMIN1(AH1P1,XOH11) 
      SPH1P=SXH1P*DPH2O/DPH2P
      AH1PQ=SPH1P*XH1P1/XOH11
      RXH1P=AMAX1(-TADA,-XMINN
     2,(AMIN1(TADA,XMINP,AH1P1-AH1PQ)))
C
C     RECALCULATE EXCHANGEABLE P
C
      ELSE
      RXOH2=0.0
      RXOH1=0.0
      RXH2P=0.0
      RYH2P=0.0
      RXH1P=0.0
      ENDIF
C     IF(M.EQ.1.OR.(M/250)*250.EQ.M)THEN 
C     WRITE(*,1112)'RXH2PI',I,L,K,M 
C    2,RXH2P,XOH21,AH2P1,AH2PQ2,AH2P1*XOH21/XH2P1,SPH2P 
C    2,XH2P1,BKVLW,CH2P1,A1(L,NY,NX)
C    2,XMINN2,XMINP2,TADA
C    2,XOH01+XOH11+XOH21+XH2P1+XH1P1
C    2,XOH01,XOH11,XOH21,XH2P1,XH1P1
C     ENDIF
C
C     CATION EXCHANGE FROM GAPON SELECTIVITY CO-EFFICIENTS
C
C     XCEC=cation exchange capacity from soil file (mol+)
C     GKC4,GKCH,GKCA,GKCM,GKCN,GKCK=Gapon selectivity coefficients for
C        Ca-NH4,Ca-H,Ca-Al,Ca-Mg,Ca-Na,Ca-K from soil file
C     A*1=ion activity (mol m-3)
C     X*Q=exchangeable ion conc’n at Gapon equilibrium (mol Mg-1) 
C     X*1=exchangeable ion conc’n (mol Mg-1) 
C     RX*=cation adsorption (+ve) or desorption (-ve) (mol t-1)
C     TADC=adsorption rate constant from PARAMETER (t-1)
C
      IF(M.EQ.1)THEN
      IF(XCEC(L,NY,NX).GT.ZEROS(NY,NX))THEN
      AALX=AMAX1(0.0,AAL1)**0.333
      AFEX=AMAX1(0.0,AFE1)**0.333
      ACAX=AMAX1(0.0,ACA1)**0.500
      AMGX=AMAX1(0.0,AMG1)**0.500
      XCAX=CCEC/(1.0
     2+GKC4(L,NY,NX)*AN41/ACAX*VLNH4(L,NY,NX)
     4+GKCH(L,NY,NX)*AHY1/ACAX
     5+GKCA(L,NY,NX)*AALX/ACAX*3.0
     6+GKCA(L,NY,NX)*AFEX/ACAX*3.0
     7+GKCM(L,NY,NX)*AMGX/ACAX*2.0
     8+GKCN(L,NY,NX)*ANA1/ACAX
     9+GKCK(L,NY,NX)*AKA1/ACAX)
      XN4Q=XCAX*AN41/ACAX*GKC4(L,NY,NX) 
      XHYQ=XCAX*AHY1/ACAX*GKCH(L,NY,NX)
      XALQ=XCAX*AALX/ACAX*GKCA(L,NY,NX)*3.0
      XFEQ=XCAX*AFEX/ACAX*GKCA(L,NY,NX)*3.0
      XCAQ=XCAX*ACAX/ACAX*2.0
      XMGQ=XCAX*AMGX/ACAX*GKCM(L,NY,NX)*2.0
      XNAQ=XCAX*ANA1/ACAX*GKCN(L,NY,NX)
      XKAQ=XCAX*AKA1/ACAX*GKCK(L,NY,NX)
      XTLQ=XN4Q+XHYQ+XALQ+XFEQ+XCAQ+XMGQ+XNAQ+XKAQ
C
C     MATCH SUM OF ALL X*1 TO CCED
C 
      IF(XTLQ.GT.ZERO)THEN
      FX=CCEC/XTLQ
      ELSE
      FX=0.0
      ENDIF
      XN4Q=FX*XN4Q
      XHYQ=FX*XHYQ
      XALQ=FX*XALQ
      XFEQ=FX*XFEQ
      XCAQ=FX*XCAQ
      XMGQ=FX*XMGQ
      XNAQ=FX*XNAQ
      XKAQ=FX*XKAQ
      XN41=XN4Q
      XHY1=XHYQ
      XAL1=XALQ/3.0
      XFE1=XFEQ/3.0
      XCA1=XCAQ/2.0
      XMG1=XMGQ/2.0
      XNA1=XNAQ
      XKA1=XKAQ
C     IF(L.EQ.2)THEN 
C     WRITE(*,1112)'RXCA',I,K,L,M 
C    2,XN4Q,XHYQ,XALQ,XFEQ,XCAQ,XMGQ,XNAQ,XKAQ
C    2,XN41,XHY1,XAL1,XFE1,XCA1,XMG1,XNA1,XKA1
C    2,AN41,AHY1,AAL1,AFE1,ACA1,AMG1,ANA1,AKA1
C    2,XN41+XHY1+XAL1*3.0+XFE1*3.0+XCA1*2.0+XMG1*2.0+XNA1+XKA1
C    2,CCEC,XCAX,XTLQ,FX,TXXX,TXXY
C     ENDIF
      ELSE
      XN41=0.0
      XHY1=0.0
      XAL1=0.0
      XFE1=0.0
      XCA1=0.0
      XMG1=0.0
      XNA1=0.0
      XKA1=0.0
      ENDIF
      ENDIF
      ELSE
      RPALOX=0.0
      RPFEOX=0.0
      RPCACX=0.0
      RPCASO=0.0
      RPALPX=0.0
      RPFEPX=0.0
      RPCADX=0.0
      RPCAHX=0.0
      RXOH2=0.0
      RXOH1=0.0
      RXH2P=0.0
      RYH2P=0.0
      RXH1P=0.0
      XN41=0.0
      XHY1=0.0
      XAL1=0.0
      XFE1=0.0
      XCA1=0.0
      XMG1=0.0
      XNA1=0.0
      XKA1=0.0
      ENDIF
C
C     DISSOCIATION OF CARBOXYL RADICALS
C
C     XCOOH=total carboxyl exchange sites (mol Mg-1)
C     XHC1,XCOO=XCOOH occupied,unoccupied by H+ (mol Mg-1)
C     AHY1=H+ activity (mol m-3)
C     XCOOQ=XCOO in equilibrium with H+ (mol Mg-1)
C     RXHC=COOH-COO+H desorption(-ve) or adsorption(+ve)(mol C m-3 t-1)
C
      IF(K.EQ.3)THEN
      XMIN=FION*AMIN1(XHC1,AHY1)
      XCOO=AMAX1(ZEROC,XCOOH-XHC1)
      XCOOQ=AMIN1(XCOOH,DPCOH*XHC1/AHY1)
      RXHC=AMAX1(-TADC,-XMIN
     2,(AMIN1(TADC,XMIN,XCOO-XCOOQ))) 
C     IF(L.EQ.1)THEN
C     WRITE(*,1112)'XHC1',I,L,K,M 
C    2,RXHC,XHC1,XCOO,XCOOQ,XCOOH,CHY1,AHY1,DPCOH,COOH
C     ENDIF
      XHC1=XHC1+RXHC
      ELSE
      RXHC=0.0
      ENDIF
C
C     ION SPECIATION FROM ION DISSOCIATION CONSTANTS
C
C     XMIN=substrate,product limit on R* (mol t-1)
C     R*=ion dissociation (mol t-1)
C     A*1=ion activity (mol m-3)
C     A*Q=ion activity at equilibrium (mol m-3)
C     DP*=dissociation products from PARAMETER above
C     TSL=rate constants for equilibrating solution reactions (mol t-1)
C
C     NH4=NH3+H
C
      XMIN=FION*AMIN1(AN41,AHY1)
      AN3Q=DPN4*AN41/AHY1
      RNH4=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AN31-AN3Q)))
C
C     RHCO3=HCO3-CO3+H dissociation
C
      XMIN=FION*AMIN1(AHCO31,AHY1)
      ACO3Q=DPHCO*AHCO31/AHY1
      RHCO3=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ACO31-ACO3Q)))
C
C     RCO2Q=CO2-HCO3+H dissociation
C
      XMIN=FION*AMIN1(ACO21,AHY1)
      AHCO3Q=DPCO2*ACO21/AHY1
      RCO2Q=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AHCO31-AHCO3Q)))
C
C     RALO1=ALOH-AL+OH dissociation
C
      XMIN=FIONS*AMIN1(AALO1,AOH1)
      AAL1Q=DPAL1*AALO1/AOH1
      RALO1=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AAL1-AAL1Q)))
C
C     RALO2=ALOH2-ALOH+OH dissociation 
C
      XMIN=FIONS*AMIN1(AALO2,AOH1)
      AALO1Q=DPAL2*AALO2/AOH1
      RALO2=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AALO1-AALO1Q)))
C
C     RALO3=ALOH3-ALOH2+OH dissociation 
C
      XMIN=FIONS*AMIN1(AALO3,AOH1)
      AALO2Q=DPAL3*AALO3/AOH1
      RALO3=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AALO2-AALO2Q)))
C
C     RALO4=ALOH4-ALOH3+OH dissociation 
C
      XMIN=FIONS*AMIN1(AALO4,AOH1)
      AALO3Q=DPAL4*AALO4/AOH1
      RALO4=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AALO3-AALO3Q)))
C     IF(L.EQ.11)THEN
C     WRITE(*,23)'RALO4',I,J,NFZ,NX,NY,L,M
C    2,RALO4,TSL,AALO3,AOH1,DPAL4,AALO4,AALO3*AOH1-DPAL4*AALO4
C    3,COH1,A1(L,NY,NX),ZOH(L,NY,NX),VOLW(L,NY,NX) 
C     ENDIF
C
C     RALS=ALSO4-AL+SO4 dissociation 
C
      XMIN=FIONS*AMIN1(AALS1,ASO41)
      AAL1Q=DPALS*AALS1/ASO41
      RALS=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AAL1-AAL1Q))) 
C     WRITE(*,23)'RALS',I,J,NFZ,NX,NY,L,M
C    2,RALS,TSL,AAL1,AAL1Q,ASO41,DPALS,AALS1 
C
C     RFEO1=FEOH-FE+OH dissociation 
C
      XMIN=FIONS*AMIN1(AFEO1,AOH1)
      AFE1Q=DPFE1*AFEO1/AOH1
      RFEO1=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AFE1-AFE1Q)))
C
C     RFEO2=FEOH2-FEOH+OH dissociation 
C
      XMIN=FIONS*AMIN1(AFEO2,AOH1)
      AFEO1Q=DPFE2*AFEO2/AOH1
      RFEO2=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AFEO1-AFEO1Q)))
C
C     RFEO3=FEOH3-FEOH2+OH dissociation 
C
      XMIN=FIONS*AMIN1(AFEO3,AOH1)
      AFEO2Q=DPFE3*AFEO3/AOH1
      RFEO3=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AFEO2-AFEO2Q)))
C
C     RFEO4=ALOH4-ALOH3+OH dissociation 
C
      XMIN=FIONS*AMIN1(AFEO4,AOH1)
      AFEO3Q=DPFE4*AFEO4/AOH1
      RFEO4=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AFEO3-AFEO3Q)))
C
C     RFES-FE+SO4 dissociation 
C
      XMIN=FIONS*AMIN1(AFES1,ASO41)
      AFE1Q=DPFES*AFES1/ASO41
      RFES=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AFES1-AFE1Q))) 
C
C     RCAO=CAOH-CA+OH dissociation 
C
      XMIN=FIONS*AMIN1(ACAO1,AOH1)
      ACA1Q=DPCAO*ACAO1/AOH1
      RCAO=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ACA1-ACA1Q)))
C
C     RCAC=CACO3-CA+CO3 dissociation 
C
      XMIN=FIONS*AMIN1(ACAC1,ACO31)
      ACA1Q=DPCAC*ACAC1/ACO31
      RCAC=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ACA1-ACA1Q))) 
C
C     RCAH=CAHCO3-CA+HCO3 dissociation 
C
      XMIN=FIONS*AMIN1(ACAH1,AHCO31)
      ACA1Q=DPCAH*ACAH1/AHCO31
      RCAH=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ACA1-ACA1Q))) 
C
C     RCAS=CASO4-CA+SO4 dissociation 
C
      XMIN=FIONS*AMIN1(ACAS1,ASO41)
      ACA1Q=DPCAS*ACAS1/ASO41
      RCAS=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ACA1-ACA1Q))) 
C
C     RMGO=MGOH-MG+OH dissociation 
C
      XMIN=FIONS*AMIN1(AMGO1,AOH1)
      AMG1Q=DPMGO*AMGO1/AOH1
      RMGO=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AMG1-AMG1Q)))
C
C     RMGC=MGCO3-MG+CO3 dissociation 
C
      XMIN=FIONS*AMIN1(AMGC1,ACO31)
      AMG1Q=DPMGC*AMGC1/ACO31
      RMGC=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AMG1-AMG1Q)))
C
C     RMGH=MGHCO3-MG+HCO3 dissociation 
C
      XMIN=FIONS*AMIN1(AMGH1,AHCO31)
      AMG1Q=DPMGH*AMGH1/AHCO31
      RMGH=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AMG1-AMG1Q)))
C
C     RMGS=MGSO4-MG+SO4 dissociation 
C
      XMIN=FIONS*AMIN1(AMGS1,ASO41)
      AMG1Q=DPMGS*AMGS1/ASO41
      RMGS=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AMG1-AMG1Q)))
C
C     RNAC=NACO3-NA+CO3 dissociation 
C
      XMIN=FIONS*AMIN1(ANAC1,ACO31)
      ANA1Q=DPNAC*ANAC1/ACO31
      RNAC=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ANA1-ANA1Q)))
C
C     RNAS=NASO4-NA+SO4 dissociation 
C
      XMIN=FIONS*AMIN1(ANAS1,ASO41)
      ANA1Q=DPNAS*ANAS1/ASO41
      RNAS=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ANA1-ANA1Q)))
C
C     RKAS=KSO4-K+SO4 dissociation 
C
      XMIN=FIONS*AMIN1(AKAS1,ASO41)
      AKA1Q=DPKAS*AKAS1/ASO41
      RKAS=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AKA1-AKA1Q)))
C
C     RH1P=HPO4-H+PO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AH1P1,AHY1,AH0P1)
      AH0P1Q=DPH1P*AH1P1/AHY1
      RH1P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AH0P1-AH0P1Q)))
C
C     RH2P=H2PO4-H+HPO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AH2P1,AHY1,AH1P1)
      AH1P1Q=DPH2P*AH2P1/AHY1
      RH2P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AH1P1-AH1P1Q)))
C
C     RH3P=H3PO4-H+H2PO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AH3P1,AHY1,AH2P1)
      AH2P1Q=DPH3P*AH3P1/AHY1
      RH3P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AH2P1-AH2P1Q)))
C
C     RF1P=FEHPO4-FE+HPO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AF1P1,AH1P1,AFE1)
      AFE1Q=DPF1P*AF1P1/AH1P1
      RF1P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AFE1-AFE1Q)))
C
C     RF2P=FEH2PO4-FE+H2PO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AF2P1,AH2P1,AFE1)
      AFE1Q=DPF2P*AF2P1/AH2P1
      RF2P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AFE1-AFE1Q)))
C
C     RC0P=CAPO4-CA+PO4 dissociation in non-band 
C
      RC0P=0.0
C
C     RC1P=CAHPO4-CA+HPO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AC1P1,AH1P1)
      ACA1Q=DPC1P*AC1P1/AH1P1
      RC1P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ACA1-ACA1Q)))
C
C     RC2P=CAH2PO4-CA+H2PO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AC2P1,AH2P1)
      ACA1Q=DPC2P*AC2P1/AH2P1
      RC2P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,ACA1-ACA1Q)))
C
C     RM1P=MGHPO4-MG+HPO4 dissociation in non-band 
C
      XMIN=FION*AMIN1(AM1P1,AH1P1)
      AMG1Q=DPM1P*AM1P1/AH1P1
      RM1P=AMAX1(-TSL,-XMIN
     2,(AMIN1(TSL,XMIN,AMG1-AMG1Q)))
C
C     TOTAL ION FLUX FOR EACH ION SPECIES
C     FROM PRECIPITATION-DISSOLUTION, EXCGANGE AND SOLUTION REACTIONS
C
      RN4S=RNH4 
      RN3S=-RNH4
      RAL=-RPALOX-RALO1-RALS-RPALPX
      RFE=-RPFEOX-RFEO1-RFES-(RPFEPX+RF1P+RF2P) 
      RCA=-RPCACX-RPCASO-RPCADX-5.0*RPCAHX
     2-RCAO-RCAC-RCAH-RCAS-RC0P-RC1P-RC2P
      RMG=-RMGO-RMGC-RMGH-RMGS-RM1P
      RNA=-RNAC-RNAS
      RKA=-RKAS
      RSO4=-RPCASO-RALS-RFES-RCAS-RMGS-RNAS-RKAS
      RAL1=RALO1-RALO2
      RAL2=RALO2-RALO3
      RAL3=RALO3-RALO4
      RAL4=RALO4
      RFE1=RFEO1-RFEO2
      RFE2=RFEO2-RFEO3
      RFE3=RFEO3-RFEO4
      RFE4=RFEO4
      RHP0=-RH1P-RC0P
      RHP1=-RXH1P+RH1P-RH2P-RF1P-RC1P-RM1P
      RHP2=-RPALPX-RPFEPX-RPCADX-3.0*RPCAHX
     2-RXH2P-RYH2P+RH2P-RH3P-RF2P-RC2P
      RHP3=RH3P
C     IF((M.EQ.1.OR.(M/100)*100.EQ.M).AND.K.EQ.3)THEN
C     WRITE(*,1112)'RHP1',I,L,K,M 
C    2,CH1P1,AH1P1,RHP1,-RXH1P,+RH1P,-RH2P,-RF1P,-RC1P,-RM1P
C     WRITE(*,1112)'RHP2',I,L,K,M 
C    2,CH2P1,AH2P1,RHP2,-RPALPX,-RPFEPX,-RPCADX,-3.0*RPCAHX
C    2,-RXH2P,-RYH2P,+RH2P,-RH3P,-RF2P,-RC2P
C     ENDIF
C
C     RECALCULATE SOLUBLE ION CONCENTRATIONS FROM TOTAL ION FLUXES
C        (mol m-3)
C
      CN41=AMAX1(ZEROC,CN41+RN4S) 
      CN31=AMAX1(ZEROC,CN31+RN3S)
      CAL1=AMAX1(ZEROC,CAL1+RAL)
      CFE1=AMAX1(ZEROC,CFE1+RFE)
      CCA1=AMAX1(ZEROC,CCA1+RCA)
      CMG1=AMAX1(ZEROC,CMG1+RMG)
      CNA1=AMAX1(ZEROC,CNA1+RNA)
      CKA1=AMAX1(ZEROC,CKA1+RKA)
      CSO41=AMAX1(ZEROC,CSO41+RSO4)
      CALO1=AMAX1(ZEROC,CALO1+RAL1)
      CALO2=AMAX1(ZEROC,CALO2+RAL2) 
      CALO3=AMAX1(ZEROC,CALO3+RAL3)
      CALO4=AMAX1(ZEROC,CALO4+RAL4)
      CALS1=AMAX1(ZEROC,CALS1+RALS)
      CFEO1=AMAX1(ZEROC,CFEO1+RFE1)
      CFEO2=AMAX1(ZEROC,CFEO2+RFE2) 
      CFEO3=AMAX1(ZEROC,CFEO3+RFE3)
      CFEO4=AMAX1(ZEROC,CFEO4+RFE4)
      CFES1=AMAX1(ZEROC,CFES1+RFES)
      CCAO1=AMAX1(ZEROC,CCAO1+RCAO)
      CCAC1=AMAX1(ZEROC,CCAC1+RCAC)
      CCAH1=AMAX1(ZEROC,CCAH1+RCAH)
      CCAS1=AMAX1(ZEROC,CCAS1+RCAS)
      CMGO1=AMAX1(ZEROC,CMGO1+RMGO)
      CMGC1=AMAX1(ZEROC,CMGC1+RMGC)
      CMGH1=AMAX1(ZEROC,CMGH1+RMGH)
      CMGS1=AMAX1(ZEROC,CMGS1+RMGS)
      CNAC1=AMAX1(ZEROC,CNAC1+RNAC)
      CNAS1=AMAX1(ZEROC,CNAS1+RNAS)
      CKAS1=AMAX1(ZEROC,CKAS1+RKAS)
      CH0P1=AMAX1(ZEROC,CH0P1+RHP0)
      CH1P1=AMAX1(ZEROC,CH1P1+RHP1)
      CH2P1=AMAX1(ZEROC,CH2P1+RHP2)
      CH3P1=AMAX1(ZEROC,CH3P1+RHP3)
      CF1P1=AMAX1(ZEROC,CF1P1+RF1P)
      CF2P1=AMAX1(ZEROC,CF2P1+RF2P)
      CC0P1=AMAX1(ZEROC,CC0P1+RC0P)
      CC1P1=AMAX1(ZEROC,CC1P1+RC1P)
      CC2P1=AMAX1(ZEROC,CC2P1+RC2P)
      CM1P1=AMAX1(ZEROC,CM1P1+RM1P)
C
C     RECALCULATE EXCHANGEABLE CONCENTRATIONS FROM TOTAL ION FLUXES
C        (mol Mg-1)
C
      IF(K.EQ.3)THEN
      XOH01=XOH01-RXOH1
      XOH11=XOH11+RXOH1-RXOH2-RYH2P-RXH1P 
      XOH21=XOH21+RXOH2-RXH2P
      XH1P1=XH1P1+RXH1P 
      XH2P1=XH2P1+RXH2P+RYH2P
      ENDIF 
C     IF(K.EQ.3.AND.(M/25)*25.EQ.M)THEN 
C     IF(K.EQ.3)THEN 
C     WRITE(*,1112)'ALL',I,L,K,M 
C    2,CHY1,CSTRQ,CC3,CA3,CC2,CA2,CC1,CA1,VOLW(L,NY,NX)
C    2,CAL1,CFE1,CH0P1,CCA1,CMG1,CALO1,CFEO1,CF2P1
C    3,CSO41,CCO31,CH1P1
C    4,CN41,CHY1,CNA1,CKA1,CALO2,CFEO2,CALS1,CFES1,CCAO1
C    5,CCAH1,CMGO1,CMGH1,CF1P1,CC2P1
C    6,CNO1,COH1,CHCO31,CCL1,CALO4,CFEO4,CNAC1,CNAS1,CKAS1
C    2,CH2P1,CC0P1
C     WRITE(*,1112)'CH1P1',I,L,K,M
C    2,CH1P1,RHP1,-RXH1P,+RH1P,-RH2P,-RF1P,-RC1P,-RM1P 
C     WRITE(*,1112)'ALPO4I',I,L,K,M,CAL1,AAL1 
C    5,RAL,-RPALOX,-RALO1,-RALS,-RPALPX,SPALO/AOH1**3  
C     WRITE(*,1112)'FEPO4I',I,L,K,M,CFE1,AFE1 
C    2,RFE,-RPFEOX,-RFEO1,-RFES,-(RPFEPX+RF1P+RF2P),SPFEO/AOH1**3  
C     WRITE(*,1112)'APATITE',I,L,K,M,PCAPH1,ACA1,CCA1,XCA1
C    2,RCA,RPCACX,RPCASO,RPCADX,5.0*RPCAHX
C    2,RCAO,RCAC,RCAH,RCAS,RC0P,RC1P,RC2P,VOLW(L,NY,NX)
C    3,SPCAC,CCO31,CHCO31,CCO21,CCO2M 
C    2,CSO41,CCAS1,RSO4,RPCASO,RALS,RFES,RCAS,RMGS,RNAS,RKAS 
C    2,AH0P1,AH1P1,AH2P1,AHY1,AOH1,RPCAHX,RHCAH1,RHCAH2 
C    3,SP,SPX,ACA1**5*AH0P1**3*AOH1,SPCAH,SHCAH1,SHCAH2
C    3,CH0P1,CH1P1,CH2P1,XOH01,XOH11,XOH21,XH1P1,XH2P1
C    4,RHA0P1,RHA1P1,RHA2P1,RHA3P1
C    2,RHA4P1,RHF0P1,RHF1P1,RHF2P1 
C    3,RHF3P1,RHF4P1,RPCAD1,3.0*RHCAH1 
C    4,RXH1P,RH1P,RH2P,RF1P,RC1P,RM1P
C    5,RHA0P2,RHA1P2,RHA2P2,RHA3P2
C    2,RHA4P2,RHF0P2,RHF1P2,RHF2P2 
C    3,RHF3P2,RHF4P2,RHCAD2,3.0*RHCAH2
C    4,RXH2P,RYH2P,RH2P,RH3P,RF2P,RC2P,RH3P 
C     ENDIF
1000  CONTINUE
C
C     RECALCULATE SOLUTE CONCENTRATIONS IN PRECIPITATION
C     FROM TOTAL ION FLUXES IN RAINWATER
C
C     C*R=solute concentrations in precipitation (mol m-3)
C
      IF(K.EQ.1.AND.I.EQ.1.AND.L.EQ.1)THEN
      CCOR(NY,NX)=CCO21
      CCHR(NY,NX)=CCH41
      COXR(NY,NX)=COXY1
      CNNR(NY,NX)=CZ2G1
      CN2R(NY,NX)=CZ2O1
      CN4R(NY,NX)=CN41
      CN3R(NY,NX)=CN31
      CALR(NY,NX)=CAL1
      CFER(NY,NX)=CFE1
      CHYR(NY,NX)=CHY1
      CCAR(NY,NX)=CCA1
      CMGR(NY,NX)=CMG1
      CNAR(NY,NX)=CNA1
      CKAR(NY,NX)=CKA1
      COHR(NY,NX)=COH1
      CSOR(NY,NX)=CSO41
      CCLR(NY,NX)=CCL1
      CC3R(NY,NX)=CCO31
      CHCR(NY,NX)=CHCO31
      CAL1R(NY,NX)=CALO1
      CAL2R(NY,NX)=CALO2
      CAL3R(NY,NX)=CALO3
      CAL4R(NY,NX)=CALO4
      CALSR(NY,NX)=CALS1
      CFE1R(NY,NX)=CFEO1
      CFE2R(NY,NX)=CFEO2
      CFE3R(NY,NX)=CFEO3
      CFE4R(NY,NX)=CFEO4
      CFESR(NY,NX)=CFES1
      CCAOR(NY,NX)=CCAO1
      CCACR(NY,NX)=CCAC1
      CCAHR(NY,NX)=CCAH1
      CCASR(NY,NX)=CCAS1
      CMGOR(NY,NX)=CMGO1
      CMGCR(NY,NX)=CMGC1
      CMGHR(NY,NX)=CMGH1
      CMGSR(NY,NX)=CMGS1
      CNACR(NY,NX)=CNAC1
      CNASR(NY,NX)=CNAS1
      CKASR(NY,NX)=CKAS1
      CH0PR(NY,NX)=CH0P1
      CH1PR(NY,NX)=CH1P1
      CPOR(NY,NX)=CH2P1
      CH3PR(NY,NX)=CH3P1
      CF1PR(NY,NX)=CF1P1
      CF2PR(NY,NX)=CF2P1
      CC0PR(NY,NX)=CC0P1
      CC1PR(NY,NX)=CC1P1
      CC2PR(NY,NX)=CC2P1
      CM1PR(NY,NX)=CM1P1
C
C     RECALCULATE SOLUTE CONCENTRATIONS IN IRRIGATION
C     FROM TOTAL ION FLUXES IN IRRIGATION WATER
C
C     C*Q=solute concentrations in irrigation (mol m-3)
C
      ELSEIF(K.EQ.2.AND.L.EQ.1)THEN
      CCOQ(NY,NX)=CCO21
      CCHQ(NY,NX)=CCH41
      COXQ(NY,NX)=COXY1
      CNNQ(NY,NX)=CZ2G1
      CN2Q(NY,NX)=CZ2O1
      CN4Q(I,NY,NX)=CN41
      CN3Q(I,NY,NX)=CN31
      CALQ(I,NY,NX)=CAL1
      CFEQ(I,NY,NX)=CFE1
      CHYQ(I,NY,NX)=CHY1
      CCAQ(I,NY,NX)=CCA1
      CMGQ(I,NY,NX)=CMG1
      CNAQ(I,NY,NX)=CNA1
      CKAQ(I,NY,NX)=CKA1
      COHQ(I,NY,NX)=COH1
      CSOQ(I,NY,NX)=CSO41
      CCLQ(I,NY,NX)=CCL1
      CC3Q(I,NY,NX)=CCO31
      CHCQ(I,NY,NX)=CHCO31
      CAL1Q(I,NY,NX)=CALO1
      CAL2Q(I,NY,NX)=CALO2
      CAL3Q(I,NY,NX)=CALO3
      CAL4Q(I,NY,NX)=CALO4
      CALSQ(I,NY,NX)=CALS1
      CFE1Q(I,NY,NX)=CFEO1
      CFE2Q(I,NY,NX)=CFEO2
      CFE3Q(I,NY,NX)=CFEO3
      CFE4Q(I,NY,NX)=CFEO4
      CFESQ(I,NY,NX)=CFES1
      CCAOQ(I,NY,NX)=CCAO1
      CCACQ(I,NY,NX)=CCAC1
      CCAHQ(I,NY,NX)=CCAH1
      CCASQ(I,NY,NX)=CCAS1
      CMGOQ(I,NY,NX)=CMGO1
      CMGCQ(I,NY,NX)=CMGC1
      CMGHQ(I,NY,NX)=CMGH1
      CMGSQ(I,NY,NX)=CMGS1
      CNACQ(I,NY,NX)=CNAC1
      CNASQ(I,NY,NX)=CNAS1
      CKASQ(I,NY,NX)=CKAS1
      CH0PQ(I,NY,NX)=CH0P1
      CH1PQ(I,NY,NX)=CH1P1
      CPOQ(I,NY,NX)=CH2P1
      CH3PQ(I,NY,NX)=CH3P1
      CF1PQ(I,NY,NX)=CF1P1
      CF2PQ(I,NY,NX)=CF2P1
      CC0PQ(I,NY,NX)=CC0P1
      CC1PQ(I,NY,NX)=CC1P1
      CC2PQ(I,NY,NX)=CC2P1
      CM1PQ(I,NY,NX)=CM1P1
C
C     RECALCULATE SOLUTE CONCENTRATIONS IN SOIL
C     FROM TOTAL ION FLUXES IN SOIL WATER
C
C     C*U=solute concentrations in soil water (g or mol m-3)
C
      ELSEIF(K.EQ.3.AND.I.EQ.1)THEN
      CCOU=CCO21
      CCHU=CCH41
      COXU=0.0
      CNNU=CZ2G1
      CN2U=CZ2O1
      CN4U(L,NY,NX)=CN41
      CN3U(L,NY,NX)=CN31
      CNOU(L,NY,NX)=CNOX
      CALU(L,NY,NX)=CAL1
      CFEU(L,NY,NX)=CFE1
      CHYU(L,NY,NX)=CHY1
      CCAU(L,NY,NX)=CCA1
      CMGU(L,NY,NX)=CMG1
      CNAU(L,NY,NX)=CNA1
      CKAU(L,NY,NX)=CKA1
      COHU(L,NY,NX)=COH1
      CSOU(L,NY,NX)=CSO41
      CCLU(L,NY,NX)=CCL1
      CC3U(L,NY,NX)=CCO31
      CHCU(L,NY,NX)=CHCO31
      CAL1U(L,NY,NX)=CALO1
      CAL2U(L,NY,NX)=CALO2
      CAL3U(L,NY,NX)=CALO3
      CAL4U(L,NY,NX)=CALO4
      CALSU(L,NY,NX)=CALS1
      CFE1U(L,NY,NX)=CFEO1
      CFE2U(L,NY,NX)=CFEO2
      CFE3U(L,NY,NX)=CFEO3
      CFE4U(L,NY,NX)=CFEO4
      CFESU(L,NY,NX)=CFES1
      CCAOU(L,NY,NX)=CCAO1
      CCACU(L,NY,NX)=CCAC1
      CCAHU(L,NY,NX)=CCAH1
      CCASU(L,NY,NX)=CCAS1
      CMGOU(L,NY,NX)=CMGO1
      CMGCU(L,NY,NX)=CMGC1
      CMGHU(L,NY,NX)=CMGH1
      CMGSU(L,NY,NX)=CMGS1
      CNACU(L,NY,NX)=CNAC1
      CNASU(L,NY,NX)=CNAS1
      CKASU(L,NY,NX)=CKAS1
      CH0PU(L,NY,NX)=CH0P1
      CH1PU(L,NY,NX)=CH1P1
      CH2PU(L,NY,NX)=CH2P1
      CH3PU(L,NY,NX)=CH3P1
      CF1PU(L,NY,NX)=CF1P1
      CF2PU(L,NY,NX)=CF2P1
      CC0PU(L,NY,NX)=CC0P1
      CC1PU(L,NY,NX)=CC1P1
      CC2PU(L,NY,NX)=CC2P1
      CM1PU(L,NY,NX)=CM1P1
C
C     INITIALIZE STATE VARIABLES FOR GAS IN SOIL 
C     AQUEOUS (*S) AND GASEOUS (*G) PHASES
C
C     C*G=soil gaseous gas content (g)
C     C*S=soil aqueous gas content (g)
C     C*E=atmospheric gas concentration (g m-3)
C     VOLP,VOLW=soil air,water content (m3)
C     S*X=gas solubility (g m-3 / (g m-3))
C
      IF(DATA(20).EQ.'NO'.AND.IGO.EQ.0)THEN
      CO2G(L,NY,NX)=CCO2EI(NY,NX)*VOLP(L,NY,NX)
      CH4G(L,NY,NX)=CCH4E(NY,NX)*VOLP(L,NY,NX)
      OXYG(L,NY,NX)=COXYE(NY,NX)*VOLP(L,NY,NX)
      Z2GG(L,NY,NX)=CZ2GE(NY,NX)*VOLP(L,NY,NX)
      Z2OG(L,NY,NX)=CZ2OE(NY,NX)*VOLP(L,NY,NX)
      ZNH3G(L,NY,NX)=CNH3E(NY,NX)*VOLP(L,NY,NX)
      H2GG(L,NY,NX)=CH2GE(NY,NX)*VOLP(L,NY,NX)
      IF(CDPTH(L-1,NY,NX).LT.DTBLZ(NY,NX))THEN
      OXYS(L,NY,NX)=COXYE(NY,NX)*SOXYX/(EXP(AOXYX*CSTR1))
     2*EXP(0.516-0.0172*ATCA(NY,NX))*VOLW(L,NY,NX)
      ELSE
      OXYS(L,NY,NX)=0.0
      ENDIF
      CO2S(L,NY,NX)=CCO2EI(NY,NX)*SCO2X/(EXP(ACO2X*CSTR1))
     2*EXP(0.843-0.0281*ATCA(NY,NX))*VOLW(L,NY,NX)
      CH4S(L,NY,NX)=CCH4E(NY,NX)*SCH4X/(EXP(ACH4X*CSTR1))
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(L,NY,NX)
      Z2GS(L,NY,NX)=CZ2GE(NY,NX)*SN2GX/(EXP(AN2GX*CSTR1))
     2*EXP(0.456-0.0152*ATCA(NY,NX))*VOLW(L,NY,NX)
      Z2OS(L,NY,NX)=CZ2OE(NY,NX)*SN2OX/(EXP(AN2OX*CSTR1))
     2*EXP(0.897-0.0299*ATCA(NY,NX))*VOLW(L,NY,NX)
      H2GS(L,NY,NX)=CH2GE(NY,NX)*SH2GX/(EXP(AH2GX*CSTR1))
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(L,NY,NX)
C
C     INITIAL STATE VARIABLES FOR MINERAL N AND P IN SOIL
C     IN NON-BAND ABND BAND ZONES
C
C     VLNH4,VLNHB=fractions of soil volume in NH4 non-band,band
C     VLNO3,VLNOB=fractions of soil volume in NO3 non-band,band
C     VLPO4,VLPOB=fractions of soil volume in H2PO4 non-band,band
C     ZNH4,ZNH3,ZNO3,ZNO2,H2PO4,H1PO=NH4,NH3,NO3,NO2,H2PO4,HPO4 (g)
C
      ZNH4S(L,NY,NX)=CN4U(L,NY,NX)*VOLW(L,NY,NX)*VLNH4(L,NY,NX)*14.0
      ZNH4B(L,NY,NX)=CN4U(L,NY,NX)*VOLW(L,NY,NX)*VLNHB(L,NY,NX)*14.0
      ZNH3S(L,NY,NX)=CN3U(L,NY,NX)*VOLW(L,NY,NX)*VLNH4(L,NY,NX)*14.0
      ZNH3B(L,NY,NX)=CN3U(L,NY,NX)*VOLW(L,NY,NX)*VLNHB(L,NY,NX)*14.0
      ZNO3S(L,NY,NX)=CNOU(L,NY,NX)*VOLW(L,NY,NX)*VLNO3(L,NY,NX)*14.0
      ZNO3B(L,NY,NX)=CNOU(L,NY,NX)*VOLW(L,NY,NX)*VLNOB(L,NY,NX)*14.0
      ZNO2S(L,NY,NX)=0.0
      ZNO2B(L,NY,NX)=0.0
      H2PO4(L,NY,NX)=CH2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)*31.0
      H2POB(L,NY,NX)=CH2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)*31.0
      H1PO4(L,NY,NX)=CH1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)*31.0
      H1POB(L,NY,NX)=CH1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)*31.0
C     WRITE(*,444)'ZNH4S',NX,NY,L,ZNH4S(L,NY,NX),CN4U(L,NY,NX)
C    2,VOLW(L,NY,NX),VLNH4(L,NY,NX),H2PO4(L,NY,NX),CH2PU(L,NY,NX)
C    3,H1PO4(L,NY,NX),CH1PU(L,NY,NX),VLPO4(L,NY,NX)
C    4,XN41*BKVL(L,NY,NX)*VLNH4(L,NY,NX)
C    5,XN41,BKVL(L,NY,NX),VLNH4(L,NY,NX)
444   FORMAT(A8,3I4,20E12.4)
C
C     INITIAL STATE VARIABLES FOR CATIONS, ANIONS AND ION PAIRS 
C     IN SOIL WATER
C
C     Z*=ion content (g (N,P) or mol)
C     C*U=solute concentrations in soil water (g (N,P) or mol m-3)
C     VOLW=soil water content (m3)
C
      ZAL(L,NY,NX)=CALU(L,NY,NX)*VOLW(L,NY,NX)
      ZFE(L,NY,NX)=CFEU(L,NY,NX)*VOLW(L,NY,NX)
      ZHY(L,NY,NX)=CHYU(L,NY,NX)*VOLW(L,NY,NX)
      ZCA(L,NY,NX)=CCAU(L,NY,NX)*VOLW(L,NY,NX)
      ZMG(L,NY,NX)=CMGU(L,NY,NX)*VOLW(L,NY,NX)
      ZNA(L,NY,NX)=CNAU(L,NY,NX)*VOLW(L,NY,NX)
      ZKA(L,NY,NX)=CKAU(L,NY,NX)*VOLW(L,NY,NX)
      ZOH(L,NY,NX)=COHU(L,NY,NX)*VOLW(L,NY,NX)
      ZSO4(L,NY,NX)=CSOU(L,NY,NX)*VOLW(L,NY,NX)
      ZCL(L,NY,NX)=CCLU(L,NY,NX)*VOLW(L,NY,NX)
      ZCO3(L,NY,NX)=CC3U(L,NY,NX)*VOLW(L,NY,NX)
      ZHCO3(L,NY,NX)=CHCU(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH1(L,NY,NX)=CAL1U(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH2(L,NY,NX)=CAL2U(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH3(L,NY,NX)=CAL3U(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH4(L,NY,NX)=CAL4U(L,NY,NX)*VOLW(L,NY,NX)
      ZALS(L,NY,NX)=CALSU(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH1(L,NY,NX)=CFE1U(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH2(L,NY,NX)=CFE2U(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH3(L,NY,NX)=CFE3U(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH4(L,NY,NX)=CFE4U(L,NY,NX)*VOLW(L,NY,NX)
      ZFES(L,NY,NX)=CFESU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAO(L,NY,NX)=CCAOU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAC(L,NY,NX)=CCACU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAH(L,NY,NX)=CCAHU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAS(L,NY,NX)=CCASU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGO(L,NY,NX)=CMGOU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGC(L,NY,NX)=CMGCU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGH(L,NY,NX)=CMGHU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGS(L,NY,NX)=CMGSU(L,NY,NX)*VOLW(L,NY,NX)
      ZNAC(L,NY,NX)=CNACU(L,NY,NX)*VOLW(L,NY,NX)
      ZNAS(L,NY,NX)=CNASU(L,NY,NX)*VOLW(L,NY,NX)
      ZKAS(L,NY,NX)=CKASU(L,NY,NX)*VOLW(L,NY,NX)
      H0PO4(L,NY,NX)=CH0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      H3PO4(L,NY,NX)=CH3PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZFE1P(L,NY,NX)=CF1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZFE2P(L,NY,NX)=CF2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZCA0P(L,NY,NX)=CC0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZCA1P(L,NY,NX)=CC1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZCA2P(L,NY,NX)=CC2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZMG1P(L,NY,NX)=CM1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      H0POB(L,NY,NX)=CH0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      H3POB(L,NY,NX)=CH3PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZFE1PB(L,NY,NX)=CF1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZFE2PB(L,NY,NX)=CF2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZCA0PB(L,NY,NX)=CC0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZCA1PB(L,NY,NX)=CC1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZCA2PB(L,NY,NX)=CC2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZMG1PB(L,NY,NX)=CM1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZHYSI(L,NY,NX)=1.0E-03*VOLW(L,NY,NX)
C     IF(L.EQ.1)THEN
C     WRITE(*,1112)'ZHCO3',I,L,K,M
C    2,ZHCO3(L,NY,NX),CHCU(L,NY,NX),VOLW(L,NY,NX),ZHYSI(L,NY,NX)
C     WRITE(*,1112)'ZFE',I,L,K,M
C    2,ZFE(L,NY,NX),CFEU(L,NY,NX),VOLW(L,NY,NX),CFE1
C     WRITE(*,1112)'ZCA',I,L,K,M
C    2,ZCA(L,NY,NX),CCAU(L,NY,NX),CCA1,CCAX,CCAZ,CCA(L,NY,NX)
C    2,ZSO4(L,NY,NX),CSOU(L,NY,NX),CSO41,CSOX,CSOZ,CSO4(L,NY,NX)
C     ENDIF
C
C     INITIAL STATE VARIABLES FOR ALL MATERIAL IN SOIL MACROPORES
C
C     *H=soil macropore gas, solute content (g or mol m-3)
C
      CO2SH(L,NY,NX)=0.0
      CH4SH(L,NY,NX)=0.0
      OXYSH(L,NY,NX)=0.0
      Z2GSH(L,NY,NX)=0.0
      Z2OSH(L,NY,NX)=0.0
      H2GSH(L,NY,NX)=0.0
      ZNH4SH(L,NY,NX)=0.0
      ZNH4BH(L,NY,NX)=0.0
      ZNH3SH(L,NY,NX)=0.0
      ZNH3BH(L,NY,NX)=0.0
      ZNO3SH(L,NY,NX)=0.0
      ZNO3BH(L,NY,NX)=0.0
      ZNO2SH(L,NY,NX)=0.0
      ZNO2BH(L,NY,NX)=0.0
      H2PO4H(L,NY,NX)=0.0
      H2POBH(L,NY,NX)=0.0
      H1PO4H(L,NY,NX)=0.0
      H1POBH(L,NY,NX)=0.0
      ZALH(L,NY,NX)=0.0
      ZFEH(L,NY,NX)=0.0
      ZHYH(L,NY,NX)=0.0
      ZCCH(L,NY,NX)=0.0
      ZMAH(L,NY,NX)=0.0
      ZNAH(L,NY,NX)=0.0
      ZKAH(L,NY,NX)=0.0
      ZOHH(L,NY,NX)=0.0
      ZSO4H(L,NY,NX)=0.0
      ZCLH(L,NY,NX)=0.0
      ZCO3H(L,NY,NX)=0.0
      ZHCO3H(L,NY,NX)=0.0
      ZALO1H(L,NY,NX)=0.0
      ZALO2H(L,NY,NX)=0.0
      ZALO3H(L,NY,NX)=0.0
      ZALO4H(L,NY,NX)=0.0
      ZALSH(L,NY,NX)=0.0
      ZFEO1H(L,NY,NX)=0.0
      ZFEO2H(L,NY,NX)=0.0
      ZFEO3H(L,NY,NX)=0.0
      ZFEO4H(L,NY,NX)=0.0
      ZFESH(L,NY,NX)=0.0
      ZCAOH(L,NY,NX)=0.0
      ZCACH(L,NY,NX)=0.0
      ZCAHH(L,NY,NX)=0.0
      ZCASH(L,NY,NX)=0.0
      ZMGOH(L,NY,NX)=0.0
      ZMGCH(L,NY,NX)=0.0
      ZMGHH(L,NY,NX)=0.0
      ZMGSH(L,NY,NX)=0.0
      ZNACH(L,NY,NX)=0.0
      ZNASH(L,NY,NX)=0.0
      ZKASH(L,NY,NX)=0.0
      H0PO4H(L,NY,NX)=0.0
      H1PO4H(L,NY,NX)=0.0
      H3PO4H(L,NY,NX)=0.0
      ZFE1PH(L,NY,NX)=0.0
      ZFE2PH(L,NY,NX)=0.0
      ZCA0PH(L,NY,NX)=0.0
      ZCA1PH(L,NY,NX)=0.0
      ZCA2PH(L,NY,NX)=0.0
      ZMG1PH(L,NY,NX)=0.0
      H0POBH(L,NY,NX)=0.0
      H1POBH(L,NY,NX)=0.0
      H3POBH(L,NY,NX)=0.0
      ZFE1BH(L,NY,NX)=0.0
      ZFE2BH(L,NY,NX)=0.0
      ZCA0BH(L,NY,NX)=0.0
      ZCA1BH(L,NY,NX)=0.0
      ZCA2BH(L,NY,NX)=0.0
      ZMG1BH(L,NY,NX)=0.0
C
C     INITIAL STATE VARIABLES FOR EXCHANGEABLE CATIONS AND ANIONS
C     IN NON-BAND AND BAND ZONES
C
C     XN4,XHY,XAL,XFE,XCA,XMG,XNA,XKA,XHC,XOH0,XOH1,XOH2
C        XH1P,XH2P=exchangeable NH4,H,AL,FE,CA,MG,NA,K,HCO3
C        OH,OH2,HPO4,H2PO4 (mol)
C     VLNH4,VLNHB=fractions of soil volume in NH4 non-band,band
C     VLNO3,VLNOB=fractions of soil volume in NO3 non-band,band
C     VLPO4,VLPOB=fractions of soil volume in H2PO4 non-band,band
C
      XN4(L,NY,NX)=XN41*BKVL(L,NY,NX)*VLNH4(L,NY,NX)
      XNB(L,NY,NX)=XN41*BKVL(L,NY,NX)*VLNHB(L,NY,NX)
      XHY(L,NY,NX)=XHY1*BKVL(L,NY,NX)
      XAL(L,NY,NX)=XAL1*BKVL(L,NY,NX) 
      XFE(L,NY,NX)=XFE1*BKVL(L,NY,NX) 
      XCA(L,NY,NX)=XCA1*BKVL(L,NY,NX) 
      XMG(L,NY,NX)=XMG1*BKVL(L,NY,NX) 
      XNA(L,NY,NX)=XNA1*BKVL(L,NY,NX)
      XKA(L,NY,NX)=XKA1*BKVL(L,NY,NX)
      XHC(L,NY,NX)=XHC1*BKVL(L,NY,NX)
      XOH0(L,NY,NX)=XOH01*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XOH1(L,NY,NX)=XOH11*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XOH2(L,NY,NX)=XOH21*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XH1P(L,NY,NX)=XH1P1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XH2P(L,NY,NX)=XH2P1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XOH0B(L,NY,NX)=XOH01*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XOH1B(L,NY,NX)=XOH11*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XOH2B(L,NY,NX)=XOH21*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XH1PB(L,NY,NX)=XH1P1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XH2PB(L,NY,NX)=XH2P1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
C
C     INITIAL STATE VARIABLES FOR SILICATES 
C
C     SSAL=soil surface area (m2)
C     CSAND,CSILT,CCLAY=sand,silt,clay content from soil file (g Mg-1)
C     BKVL=soil mass (Mg)
C     Q*SI=silicate content (mol)
C        silicate code: AL=Al,FE=Fe,CA=Ca,MG=Mg,NA=Na,KA=K
C
      SSAL=(0.3*CSAND(L,NY,NX)+2.2*CSILT(L,NY,NX)
     2+8.0*CCLAY(L,NY,NX))*BKVL(L,NY,NX) 
      QALSI(L,NY,NX)=0.167*SSAL*5.0E+03
      QFESI(L,NY,NX)=0.167*SSAL*5.0E+03
      IF(PH(L,NY,NX).GT.4.5)THEN
      QCASI(L,NY,NX)=0.167*SSAL*5.0E+03
      QMGSI(L,NY,NX)=0.167*SSAL*5.0E+03
      QNASI(L,NY,NX)=0.167*SSAL*5.0E+03
      QKASI(L,NY,NX)=0.167*SSAL*5.0E+03
      ELSE
      QCASI(L,NY,NX)=0.0
      QMGSI(L,NY,NX)=0.0
      QNASI(L,NY,NX)=0.0
      QKASI(L,NY,NX)=0.0
      ENDIF
C
C     INITIAL STATE VARIABLES FOR PRECIPITATES 
C
C     P*=precipitate content in non-band,band(*B) zones (mol)
C        ALOH,FEOH,CACO,CASO,ALPO,FEPO,CAPD,CAPH,CAPM
C        =AL(OH)3,FE(OH)3,CACO3,CASO4,ALPO4,FEPO4,CAHPO4
C         CA(H2PO4)2,hydroxyapatite     
C     BKVL=soil mass (Mg)
C
      PALOH(L,NY,NX)=PALOH1*BKVL(L,NY,NX)
      PFEOH(L,NY,NX)=PFEOH1*BKVL(L,NY,NX)
      PCACO(L,NY,NX)=PCACO1*BKVL(L,NY,NX)
      PCASO(L,NY,NX)=PCASO1*BKVL(L,NY,NX)
      PALPO(L,NY,NX)=PALPO1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PFEPO(L,NY,NX)=PFEPO1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PCAPD(L,NY,NX)=PCAPD1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PCAPH(L,NY,NX)=PCAPH1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PCAPM(L,NY,NX)=0.0
      PALPB(L,NY,NX)=PALPO1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PFEPB(L,NY,NX)=PFEPO1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PCPDB(L,NY,NX)=PCAPD1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PCPHB(L,NY,NX)=PCAPH1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PCPMB(L,NY,NX)=0.0
      ECND(L,NY,NX)=0.0
C
C     AMEND INTITIAL NH4 FOR INITIAL MANURE
C
C     ZNH4S=soil NH4+ (g)
C     OSN=intitial manure from soil file (g)
C
      ZNH4S(L,NY,NX)=ZNH4S(L,NY,NX)+0.5*OSN(1,2,L,NY,NX)
      OSN(1,2,L,NY,NX)=OSN(1,2,L,NY,NX)-0.5*OSN(1,2,L,NY,NX)
C     IF(K.EQ.3.AND.L.EQ.1)THEN
C     WRITE(*,2222)'XN4F',I,K,L
C    2,XN4(L,NY,NX),XN41,BKVL(L,NY,NX),VLNH4(L,NY,NX)
C    3,XHY(L,NY,NX),XHY1,BKVL(L,NY,NX)
C     WRITE(*,2222)'XOH2F',I,K,L
C    2,XOH21,XOH11,XOH01,XH2P1,XH1P1
C    3,XH1P(L,NY,NX),XH2P(L,NY,NX),BKVL(L,NY,NX),VLPO4(L,NY,NX) 
C     WRITE(*,2222)'PCACO',I,K,L
C    2,PCACO(L,NY,NX),PCACO1,BKVL(L,NY,NX)
2222  FORMAT(A8,3I4,20E12.4)
C     ENDIF
      ENDIF
      ENDIF
2000  CONTINUE
1200  CONTINUE
C
C     INITIALIZE SURFACE LITTER
C
C     BKVL=soil mass (Mg)
C     ORGC=SOC(g Mg-1) from soil file
C     XCOOH,XHC1=carboxyl exchange sites,occupied by H+ (mol)
C     ORGC=surface litter C (g)
C     C*1=litter ion concentration (mol Mg-1)
C     SP*=solubility product from PARAMETER above 
C     C*U=solute concentrations in soil surface water (g or mol m-3)
C     ISALTG:0=salt concentrations entered in soil file generate
C              equilibrium concentrations that remain static during
C              model run
C           :1=salt equilibrium concentrations are solved
C              dynamically in ‘solute.f’ and transported in ‘trnsfrs.f’ 
C
      IF(ISALTG.NE.0)THEN
      CHY1=10.0**(-(PH(0,NY,NX)-3.0))
      COH1=DPH2O/CHY1
      IF(BKVL(0,NY,NX).GT.ZEROS(NY,NX))THEN
      XCOOH=AMAX1(ZEROC,COOH*1.0E-06*ORGC(0,NY,NX)/BKVL(0,NY,NX))
      ELSE
      XCOOH=ZERO
      ENDIF
      XHC1=XCOOH*AMIN1(1.0,CHY1/DPCOH) 
C     WRITE(*,1114)'XHCX',M
C    2,XHC1,XCOO,XCOOQ,XCOOH,CHY1,AHY1,DPCOH,COOH
      CCEC0=XCOOH
      CN41=CNH4(NU(NY,NX),NY,NX)*0.10/14.0
      CAL1=SPALO/COH1**3
      CFE1=SPFEO/COH1**3
      CCA1=CCA(NU(NY,NX),NY,NX)
      CMG1=CMG(NU(NY,NX),NY,NX)
      CNA1=CNA(NU(NY,NX),NY,NX)
      CKA1=CKA(NU(NY,NX),NY,NX)
      CSO41=CSOU(NU(NY,NX),NY,NX)
      CCL1=CCLU(NU(NY,NX),NY,NX) 
      CCO31=CC3U(NU(NY,NX),NY,NX)
      CHCO31=CHCU(NU(NY,NX),NY,NX)
      CALO1=CAL1U(NU(NY,NX),NY,NX)
      CALO2=CAL2U(NU(NY,NX),NY,NX)
      CALO3=CAL3U(NU(NY,NX),NY,NX)
      CALO4=CAL4U(NU(NY,NX),NY,NX)
      CALS1=CALSU(NU(NY,NX),NY,NX)
      CFEO1=CFE1U(NU(NY,NX),NY,NX)
      CFEO2=CFE2U(NU(NY,NX),NY,NX)
      CFEO3=CFE3U(NU(NY,NX),NY,NX)
      CFEO4=CFE4U(NU(NY,NX),NY,NX)
      CFES1=CFESU(NU(NY,NX),NY,NX)
      CCAO1=CCAOU(NU(NY,NX),NY,NX)
      CCAC1=CCACU(NU(NY,NX),NY,NX)
      CCAH1=CCAHU(NU(NY,NX),NY,NX)
      CCAS1=CCASU(NU(NY,NX),NY,NX)
      CMGO1=CMGOU(NU(NY,NX),NY,NX)
      CMGC1=CMGCU(NU(NY,NX),NY,NX)
      CMGH1=CMGHU(NU(NY,NX),NY,NX)
      CMGS1=CMGSU(NU(NY,NX),NY,NX)
      CNAC1=CNACU(NU(NY,NX),NY,NX)
      CNAS1=CNASU(NU(NY,NX),NY,NX)
      CKAS1=CKASU(NU(NY,NX),NY,NX)
      CH0P1=CH0PU(NU(NY,NX),NY,NX)
      CH3P1=CH3PU(NU(NY,NX),NY,NX)
      CF1P1=CF1PU(NU(NY,NX),NY,NX)
      CF2P1=CF2PU(NU(NY,NX),NY,NX)
      CC0P1=CC0PU(NU(NY,NX),NY,NX)
      CC1P1=CC1PU(NU(NY,NX),NY,NX)
      CC2P1=CC2PU(NU(NY,NX),NY,NX)
      CM1P1=CM1PU(NU(NY,NX),NY,NX)
      DO 3000 M=1,MRXN
C
C     ION ACTIVITY COEFFICIENTS
C
C     CC*,CA*=total cation,anion concentration (mol m-3)
C     CSTR*=ion strengths
C     A*R=ion activity coefficients
C     A*1=ion activity (mol m-3)
C
      CC3=CAL1+CFE1
      CA3=CH0P1
      CC2=CCA1+CMG1+CALO1+CFEO1+CF2P1
      CA2=CSO41+CCO31+CH1P1
      CC1=CN41+CHY1+CNA1+CKA1+CALO2+CFEO2+CALS1+CFES1+CCAO1
     2+CCAH1+CMGO1+CMGH1+CF1P1+CC2P1
      CA1=CNO1+COH1+CHCO31+CCL1+CALO4+CFEO4+CNAC1+CNAS1+CKAS1
     2+CH2P1+CC0P1
      CSTR1=1.0E-03*(9.0*(CC3+CA3)+4.0*(CC2+CA2)+CC1+CA1)
      CSTRQ=SQRT(CSTR1)
      CSTRX=CSTRQ/(1.0+CSTRQ)-0.20*CSTR1
      A1R=AMIN1(1.0,10.0**(-0.509*1.0*CSTRX))
      A2R=AMIN1(1.0,10.0**(-0.509*4.0*CSTRX))
      A3R=AMIN1(1.0,10.0**(-0.509*9.0*CSTRX))
      AHY1=10.0**(-(PH(0,NY,NX)-3.0))
      AOH1=DPH2O/AHY1
      AN41=CN41*A1R
      AAL1=CAL1*A3R
      AFE1=CFE1*A3R
      ACA1=CCA1*A2R
      AMG1=CMG1*A2R
      ANA1=CNA1*A1R
      AKA1=CKA1*A1R
C
C     CATION EXCHANGE
C
C     XCEC=cation exchange capacity from soil file (mol)
C     GKC4,GKCH,GKCA,GKCM,GKCN,GKCK=Gapon selectivity coefficients for
C        Ca-NH4,Ca-H,Ca-Al,Ca-Mg,Ca-Na,Ca-K from soil file
C     A*1=ion activity
C     X*Q=exchangeable ion concentration at equilibrium (mol Mg-1) 
C     X*1=exchangeable ion concentration (mol Mg-1) 
C     RX*=cation adsorption (+ve) or desorption (-ve) (mol m-3 t-1)
C     TADC=adsorption rate constant (mol m-3 t-1)
C
      IF(M.EQ.1)THEN
      IF(ORGC(0,NY,NX).GT.ZEROS(NY,NX))THEN
      AALX=AMAX1(ZEROC,AAL1)**0.333
      AFEX=AMAX1(ZEROC,AFE1)**0.333
      ACAX=AMAX1(ZEROC,ACA1)**0.500
      AMGX=AMAX1(ZEROC,AMG1)**0.500
      XCAX=CCEC0/(1.0+GKC4(NU(NY,NX),NY,NX)*AN41/ACAX
     3+GKCH(NU(NY,NX),NY,NX)*AHY1/ACAX
     3+GKCA(NU(NY,NX),NY,NX)*AALX/ACAX
     4+GKCA(NU(NY,NX),NY,NX)*AFEX/ACAX
     4+GKCM(NU(NY,NX),NY,NX)*AMGX/ACAX
     5+GKCN(NU(NY,NX),NY,NX)*ANA1/ACAX
     5+GKCK(NU(NY,NX),NY,NX)*AKA1/ACAX)
      XN4Q=XCAX*AN41*GKC4(NU(NY,NX),NY,NX)
      XHYQ=XCAX*AHY1*GKCH(NU(NY,NX),NY,NX) 
      XALQ=XCAX*AALX*GKCA(NU(NY,NX),NY,NX) 
      XFEQ=XCAX*AFEX*GKCA(NU(NY,NX),NY,NX) 
      XCAQ=XCAX*ACAX
      XMGQ=XCAX*AMGX*GKCM(NU(NY,NX),NY,NX) 
      XNAQ=XCAX*ANA1*GKCN(NU(NY,NX),NY,NX) 
      XKAQ=XCAX*AKA1*GKCK(NU(NY,NX),NY,NX) 
      XTLQ=XN4Q+XALQ+XFEQ+XCAQ+XMGQ+XHYQ+XNAQ+XKAQ 
C
C     MATCH SUM OF ALL X*1 TO CCED
C 
      IF(XTLQ.GT.ZERO)THEN
      FX=CCEC0/XTLQ
      ELSE
      FX=0.0
      ENDIF
      XN4Q=FX*XN4Q
      XHYQ=FX*XHYQ
      XALQ=FX*XALQ
      XFEQ=FX*XFEQ
      XCAQ=FX*XCAQ
      XMGQ=FX*XMGQ
      XNAQ=FX*XNAQ
      XKAQ=FX*XKAQ
      XN41=XN4Q
      XHY1=XHYQ
      XAL1=XALQ/3.0
      XFE1=XFEQ/3.0
      XCA1=XCAQ/2.0
      XMG1=XMGQ/2.0
      XNA1=XNAQ
      XKA1=XKAQ
C     IF((M.LE.10.OR.(M/100)*100.EQ.M).AND.L.LE.4)THEN 
C     WRITE(*,1113)'RXCA0',M 
C    2,XN4Q,XHYQ,XALQ,XFEQ,XCAQ,XMGQ,XNAQ,XKAQ
C    2,XN41,XHY1,XAL1,XFE1,XCA1,XMG1,XNA1,XKA1
C    2,AN41,AHY1,AAL1,AFE1,ACA1,AMG1,ANA1,AKA1
C    2,XN41+XHY1+XAL1*3.0+XFE1*3.0+XCA1*2.0+XMG1*2.0+XNA1+XKA1
C    2,CCEC0,XCAX,XTLQ,FX,TXXX,TXXY
C     ENDIF
      ELSE
      XN41=0.0
      XHY1=0.0
      XAL1=0.0
      XFE1=0.0
      XCA1=0.0
      XMG1=0.0
      XNA1=0.0
      XKA1=0.0
      ENDIF
      ENDIF
C
C     DISSOCIATION OF CARBOXYL RADICALS
C
C     XCOOH=total carboxyl exchange sites (mol Mg-1)
C     XHC1,XCOO=XCOOH occupied,unoccupied by H+ (mol Mg-1)
C     AHY1=H+ activity (mol m-3)
C     XCOOQ=XCOO in equilibrium with H+ (mol Mg-1)
C     RXHC=COOH-COO+H desorption(-ve) or adsorption(+ve)(mol C m-3 t-1)
C
      XCOO=AMAX1(ZEROC,XCOOH-XHC1)
      XCOOQ=AMIN1(XCOOH,DPCOH*XHC1/AHY1)
      RXHC=AMAX1(-TADC*XHC1,-TADC,(AMIN1(TADC
     2,(XCOO-XCOOQ))))
      XHC1=XHC1+RXHC
C     WRITE(*,1114)'XHC0',M
C    2,RXHC,XHC1,XCOO,XCOOQ,XCOOH,CHY1,AHY1,DPCOH,COOH
1114  FORMAT(A8,1I4,20E12.4) 
1113  FORMAT(A8,1I4,/,8F16.8,/,8F16.8,/,8F16.8,/,8F16.8,/
     2,8F16.8,/,8F16.8,/,8F16.8)
3000  CONTINUE 
      XHC(0,NY,NX)=XHC1*BKVL(0,NY,NX)
      ELSE
      XHC(0,NY,NX)=0.0
      ENDIF
C
C     INITIAL STATE VARIABLES FOR MINERALS IN SURFACE LITTER
C
C     surface litter L=0
C     C*G=litter gaseous gas content (g)
C     C*S=litter aqueous gas content (g)
C     C*E=atmospheric gas concentration (g m-2)
C     VOLP,VOLW=litter air,water content (m3)
C     S*X=gas solubility (g m-3 / (g m-3))
C
      IF(DATA(20).EQ.'NO'.AND.IGO.EQ.0)THEN
      CO2G(0,NY,NX)=CCO2EI(NY,NX)*VOLP(0,NY,NX)
      CH4G(0,NY,NX)=CCH4E(NY,NX)*VOLP(0,NY,NX)
      OXYG(0,NY,NX)=COXYE(NY,NX)*VOLP(0,NY,NX)
      Z2GG(0,NY,NX)=CZ2GE(NY,NX)*VOLP(0,NY,NX)
      Z2OG(0,NY,NX)=CZ2OE(NY,NX)*VOLP(0,NY,NX)
      ZNH3G(0,NY,NX)=CNH3E(NY,NX)*VOLP(0,NY,NX)
      H2GG(0,NY,NX)=CH2GE(NY,NX)*VOLP(0,NY,NX)
      CO2S(0,NY,NX)=CCO2EI(NY,NX)*SCO2X
     2*EXP(0.843-0.0281*ATCA(NY,NX))*VOLW(0,NY,NX)
      CH4S(0,NY,NX)=CCH4E(NY,NX)*SCH4X
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(0,NY,NX)
      OXYS(0,NY,NX)=COXYE(NY,NX)*SOXYX
     2*EXP(0.516-0.0172*ATCA(NY,NX))*VOLW(0,NY,NX)
      Z2GS(0,NY,NX)=CZ2GE(NY,NX)*SN2GX
     2*EXP(0.456-0.0152*ATCA(NY,NX))*VOLW(0,NY,NX)
      Z2OS(0,NY,NX)=CZ2OE(NY,NX)*SN2OX
     2*EXP(0.897-0.0299*ATCA(NY,NX))*VOLW(0,NY,NX)
      H2GS(0,NY,NX)=CH2GE(NY,NX)*SH2GX
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(0,NY,NX)
C
C     SOLUTES
C
C     Z*=litter solute content (g or mol)
C     VOLW=litter water content (m3)
C     C*U=solute concentrations in soil surface water (g or mol m-3)
C
      ZNH4S(0,NY,NX)=CN41*VOLW(0,NY,NX)*14.0
      ZNH3S(0,NY,NX)=CN3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNO3S(0,NY,NX)=CNOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNO2S(0,NY,NX)=0.0
      H2PO4(0,NY,NX)=CH2PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      H1PO4(0,NY,NX)=CH1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNH4B(0,NY,NX)=0.0
      ZNH3B(0,NY,NX)=0.0
      ZNO3B(0,NY,NX)=0.0
      ZNO2B(0,NY,NX)=0.0
      H2POB(0,NY,NX)=0.0
      H1POB(0,NY,NX)=0.0
      ZNO2B(0,NY,NX)=0.0
      CHY0=10.0**(-(PH(0,NY,NX)-3.0))
      COH0=DPH2O/CHY0
      ZHY(0,NY,NX)=CHY0*VOLW(0,NY,NX)
      ZOH(0,NY,NX)=COH0*VOLW(0,NY,NX)
      ZAL(0,NY,NX)=CAL1*VOLW(0,NY,NX)
      ZFE(0,NY,NX)=CFE1*VOLW(0,NY,NX)
      ZCA(0,NY,NX)=CCA1*VOLW(0,NY,NX)
      ZMG(0,NY,NX)=CMG1*VOLW(0,NY,NX)
      ZNA(0,NY,NX)=CNA1*VOLW(0,NY,NX)
      ZKA(0,NY,NX)=CKA1*VOLW(0,NY,NX)
C
C     INITIAL STATE VARIABLES FOR CATIONS, ANIONS AND ION PAIRS 
C     IN LITTER
C
C     ISALTG:0=salt concentrations entered in soil file generate
C              equilibrium concentrations that remain static during
C              model run
C           :1=salt equilibrium concentrations are solved
C              dynamically in ‘solute.f’ and transported in ‘trnsfrs.f’ 
C
      IF(ISALTG.NE.0)THEN
      ZSO4(0,NY,NX)=CSOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCL(0,NY,NX)=CCLU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCO3(0,NY,NX)=CC3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZHCO3(0,NY,NX)=CHCU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH1(0,NY,NX)=CAL1U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH2(0,NY,NX)=CAL2U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH3(0,NY,NX)=CAL3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH4(0,NY,NX)=CAL4U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALS(0,NY,NX)=CALSU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH1(0,NY,NX)=CFE1U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH2(0,NY,NX)=CFE2U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH3(0,NY,NX)=CFE3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH4(0,NY,NX)=CFE4U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFES(0,NY,NX)=CFESU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAO(0,NY,NX)=CCAOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAC(0,NY,NX)=CCACU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAH(0,NY,NX)=CCAHU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAS(0,NY,NX)=CCASU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGO(0,NY,NX)=CMGOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGC(0,NY,NX)=CMGCU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGH(0,NY,NX)=CMGHU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGS(0,NY,NX)=CMGSU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNAC(0,NY,NX)=CNACU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNAS(0,NY,NX)=CNASU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZKAS(0,NY,NX)=CKASU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZHYSI(0,NY,NX)=1.0E-03*VOLW(0,NY,NX)
      H0PO4(0,NY,NX)=CH0PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      H3PO4(0,NY,NX)=CH3PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFE1P(0,NY,NX)=CF1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFE2P(0,NY,NX)=CF2PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCA0P(0,NY,NX)=CC0PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCA1P(0,NY,NX)=CC1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCA2P(0,NY,NX)=CC2PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMG1P(0,NY,NX)=CM1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ELSE
      ZSO4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCL(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCO3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZHCO3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH1(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH2(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH1(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH2(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFES(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAO(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAC(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAH(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGO(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGC(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGH(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZNAC(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZNAS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZKAS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      H0PO4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      H3PO4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFE1P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFE2P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCA0P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCA1P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCA2P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMG1P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ENDIF
C
C     EXCHANGEABLE CATIONS AND ANIONS
C
      XN4(0,NY,NX)=XN41*BKVL(0,NY,NX)
      XNB(0,NY,NX)=0.0
      XHY(0,NY,NX)=XHY1*BKVL(0,NY,NX)
      XAL(0,NY,NX)=XAL1*BKVL(0,NY,NX)
      XFE(0,NY,NX)=XFE1*BKVL(0,NY,NX)
      XCA(0,NY,NX)=XCA1*BKVL(0,NY,NX)
      XMG(0,NY,NX)=XMG1*BKVL(0,NY,NX)
      XNA(0,NY,NX)=XNA1*BKVL(0,NY,NX)
      XKA(0,NY,NX)=XKA1*BKVL(0,NY,NX) 
      XOH0(0,NY,NX)=0.0
      XOH1(0,NY,NX)=0.0
      XOH2(0,NY,NX)=0.0
      XH1P(0,NY,NX)=0.0
      XH2P(0,NY,NX)=0.0
C
C     INITIAL STATE VARIABLES FOR GAS AND MINERAL N AND P IN SNOWPACK
C     FROM CONCENTRATIONS IN PRECIPITATION
C
      DO 9985 L=1,JS
      IF(VHCPW(L,NY,NX).GT.VHCPWX(NY,NX))THEN
C
C     VOLSSL,VOLWSL,VOLISL,VOLSL=snow,water,ice,total layer volume (m3)
C     DENSI=ice density (Mg m-3)
C     *W=snowpack solute content (g or mol)
C     C*R=solute concentration in precipitation (mol m-3)
C     ISALTG:0=salt concentrations entered in soil file generate
C              equilibrium concentrations that remain static during
C              model run
C           :1=salt equilibrium concentrations are solved
C              dynamically in ‘solute.f’ and transported in ‘trnsfrs.f’ 
C
      VOLWW=VOLWSL(L,NY,NX)+VOLSSL(L,NY,NX)+VOLISL(L,NY,NX)*DENSI
      CO2W(L,NY,NX)=VOLWW*CCOR(NY,NX)
      CH4W(L,NY,NX)=VOLWW*CCHR(NY,NX)
      OXYW(L,NY,NX)=VOLWW*COXR(NY,NX)
      ZNGW(L,NY,NX)=VOLWW*CNNR(NY,NX)
      ZN2W(L,NY,NX)=VOLWW*CN2R(NY,NX)
      ZN4W(L,NY,NX)=VOLWW*CN4R(NY,NX)*14.0
      ZN3W(L,NY,NX)=VOLWW*CN3R(NY,NX)*14.0
      ZNOW(L,NY,NX)=VOLWW*CNOR(NY,NX)*14.0
      Z1PW(L,NY,NX)=VOLWW*CH1PR(NY,NX)*31.0
      ZHPW(L,NY,NX)=VOLWW*CPOR(NY,NX)*31.0
C
C     INITIAL STATE VARIABLES FOR CATIONS AND ANIONS IN SNOWPACK
C
      IF(ISALTG.NE.0)THEN
      ZALW(L,NY,NX)=VOLWW*CALR(NY,NX)
      ZFEW(L,NY,NX)=VOLWW*CFER(NY,NX)
      ZHYW(L,NY,NX)=VOLWW*CHYR(NY,NX)
      ZCAW(L,NY,NX)=VOLWW*CCAR(NY,NX)
      ZMGW(L,NY,NX)=VOLWW*CMGR(NY,NX)
      ZNAW(L,NY,NX)=VOLWW*CNAR(NY,NX)
      ZKAW(L,NY,NX)=VOLWW*CKAR(NY,NX)
      ZOHW(L,NY,NX)=VOLWW*COHR(NY,NX)
      ZSO4W(L,NY,NX)=VOLWW*CSOR(NY,NX)
      ZCLW(L,NY,NX)=VOLWW*CCLR(NY,NX)
      ZCO3W(L,NY,NX)=VOLWW*CC3R(NY,NX)
      ZHCO3W(L,NY,NX)=VOLWW*CHCR(NY,NX)
      ZALH1W(L,NY,NX)=VOLWW*CAL1R(NY,NX)
      ZALH2W(L,NY,NX)=VOLWW*CAL2R(NY,NX)
      ZALH3W(L,NY,NX)=VOLWW*CAL3R(NY,NX)
      ZALH4W(L,NY,NX)=VOLWW*CAL4R(NY,NX)
      ZALSW(L,NY,NX)=VOLWW*CALSR(NY,NX)
      ZFEH1W(L,NY,NX)=VOLWW*CFE1R(NY,NX)
      ZFEH2W(L,NY,NX)=VOLWW*CFE2R(NY,NX)
      ZFEH3W(L,NY,NX)=VOLWW*CFE3R(NY,NX)
      ZFEH4W(L,NY,NX)=VOLWW*CFE4R(NY,NX)
      ZFESW(L,NY,NX)=VOLWW*CFESR(NY,NX)
      ZCAOW(L,NY,NX)=VOLWW*CCAOR(NY,NX)
      ZCACW(L,NY,NX)=VOLWW*CCACR(NY,NX)
      ZCAHW(L,NY,NX)=VOLWW*CCAHR(NY,NX)
      ZCASW(L,NY,NX)=VOLWW*CCASR(NY,NX)
      ZMGOW(L,NY,NX)=VOLWW*CMGOR(NY,NX)
      ZMGCW(L,NY,NX)=VOLWW*CMGCR(NY,NX)
      ZMGHW(L,NY,NX)=VOLWW*CMGHR(NY,NX)
      ZMGSW(L,NY,NX)=VOLWW*CMGSR(NY,NX)
      ZNACW(L,NY,NX)=VOLWW*CNACR(NY,NX)
      ZNASW(L,NY,NX)=VOLWW*CNASR(NY,NX)
      ZKASW(L,NY,NX)=VOLWW*CKASR(NY,NX)
      H0PO4W(L,NY,NX)=VOLWW*CH0PR(NY,NX)
      H3PO4W(L,NY,NX)=VOLWW*CH3PR(NY,NX)
      ZFE1PW(L,NY,NX)=VOLWW*CF1PR(NY,NX)
      ZFE2PW(L,NY,NX)=VOLWW*CF2PR(NY,NX)
      ZCA0PW(L,NY,NX)=VOLWW*CC0PR(NY,NX)
      ZCA1PW(L,NY,NX)=VOLWW*CC1PR(NY,NX)
      ZCA2PW(L,NY,NX)=VOLWW*CC2PR(NY,NX)
      ZMG1PW(L,NY,NX)=VOLWW*CM1PR(NY,NX)
      ENDIF
      ELSE
      CO2W(L,NY,NX)=0.0
      CH4W(L,NY,NX)=0.0
      OXYW(L,NY,NX)=0.0
      ZNGW(L,NY,NX)=0.0
      ZN2W(L,NY,NX)=0.0
      ZN4W(L,NY,NX)=0.0
      ZN3W(L,NY,NX)=0.0
      ZNOW(L,NY,NX)=0.0
      Z1PW(L,NY,NX)=0.0
      ZHPW(L,NY,NX)=0.0
C
C     INITIAL STATE VARIABLES FOR CATIONS AND ANIONS IN SNOWPACK
C
      IF(ISALTG.NE.0)THEN
      ZALW(L,NY,NX)=0.0
      ZFEW(L,NY,NX)=0.0
      ZHYW(L,NY,NX)=0.0
      ZCAW(L,NY,NX)=0.0
      ZMGW(L,NY,NX)=0.0
      ZNAW(L,NY,NX)=0.0
      ZKAW(L,NY,NX)=0.0
      ZOHW(L,NY,NX)=0.0
      ZSO4W(L,NY,NX)=0.0 
      ZCLW(L,NY,NX)=0.0 
      ZCO3W(L,NY,NX)=0.0 
      ZHCO3W(L,NY,NX)=0.0
      ZALH1W(L,NY,NX)=0.0
      ZALH2W(L,NY,NX)=0.0
      ZALH3W(L,NY,NX)=0.0
      ZALH4W(L,NY,NX)=0.0
      ZALSW(L,NY,NX)=0.0 
      ZFEH1W(L,NY,NX)=0.0 
      ZFEH2W(L,NY,NX)=0.0
      ZFEH3W(L,NY,NX)=0.0
      ZFEH4W(L,NY,NX)=0.0
      ZFESW(L,NY,NX)=0.0
      ZCAOW(L,NY,NX)=0.0
      ZCACW(L,NY,NX)=0.0
      ZCAHW(L,NY,NX)=0.0
      ZCASW(L,NY,NX)=0.0
      ZMGOW(L,NY,NX)=0.0
      ZMGCW(L,NY,NX)=0.0
      ZMGHW(L,NY,NX)=0.0
      ZMGSW(L,NY,NX)=0.0
      ZNACW(L,NY,NX)=0.0
      ZNASW(L,NY,NX)=0.0
      ZKASW(L,NY,NX)=0.0
      H0PO4W(L,NY,NX)=0.0
      H3PO4W(L,NY,NX)=0.0
      ZFE1PW(L,NY,NX)=0.0
      ZFE2PW(L,NY,NX)=0.0
      ZCA0PW(L,NY,NX)=0.0
      ZCA1PW(L,NY,NX)=0.0
      ZCA2PW(L,NY,NX)=0.0
      ZMG1PW(L,NY,NX)=0.0
      ENDIF
      ENDIF
9985  CONTINUE
      ENDIF
9990  CONTINUE
9995  CONTINUE
      RETURN
      END



