      SUBROUTINE starte(NHW,NHE,NVN,NVS)
C
C     THIS SUBROUTINE INITIALIZES ALL SOIL CHEMISTRY VARIABLES
C
      include "parameters.h"
      include "filec.h"
      include "files.h"
      include "blkc.h"
      include "blk2a.h"
      include "blk2b.h"
      include "blk2c.h"
      include "blk8a.h"
      include "blk8b.h"
      include "blk11a.h"
      include "blk11b.h"
      include "blk13a.h"
      include "blk13b.h"
      include "blk13c.h"
      include "blk19a.h"
      include "blk19b.h"
      include "blk19c.h"
      include "blk19d.h"
      CHARACTER*16 DATA(30)
      CHARACTER*3 CHOICE(102,20)
      CHARACTER*8 CDATE
C
C     SC*X=gas solubility coefficients(g m-3/g m-3):CO2=CO2,CH4=CH4, 
C          OXY=O2,N2G=N2g,N2O=N2O,NH3=NH3,H2G=H2
C     AC*X=activity coefficients (g m-3):CO2=CO2,CH4=CH4, 
C          OXY=O2,N2G=N2g,N2O=N2O,NH3=NH3,H2G=H2
C
      PARAMETER (SCO2X=7.391E-01,SCH4X=3.156E-02,SOXYX=2.925E-02
     2,SN2GX=1.510E-02,SN2OX=5.241E-01,SNH3X=2.852E+02,SH2GX=3.156E-02
     3,ACO2X=0.14,ACH4X=0.14,AOXYX=0.31,AN2GX=0.23,AN2OX=0.23
     4,ANH3X=0.07,AH2GX=0.14)
C
C     SOLUBILITY PRODUCTS AND DISSOCIATION CONSTANTS
C
C     DPH2O=water,SPALO=AlOH3s,SPFEO=FeOH3s,SPCAC=CaCO3s,SPCAS=CaSO4s
C     SPALP=AlPO4s,SPFEP=FePO4s,SPCAM=Ca(H2PO4)2s,SPCAD=CAHPO4s
C     SPCAH=hydroxyapatite,SXOX2=R-OH2,SXOX1=R-OH,SXH2P=R-H2PO4
C     SXH1P=R-HPO4,DPCO2=CO2,DPHCO=HCO3,DPN4=NH4,DPAL1=ALOH
C     DPAL2=ALOH2,DPAL3=AlOH3,DPAL4=ALOH4,DPALS=AlSO4,DPFE1=FeOH
C     DPFE2=FeOH2,DPFE3=FeOH3,DPFE4=FeOH4,DPFES=FeSO4
C     DPCAO=CaOH,DPCAC=CaCO3,DPCAH=CaHCO3,DPCAS=CaSO4
C     DPMGO=MgOH,DPMGC=MgCO3,DPMGH=MgHCO3,DPMGS=MgSO4
C     DPNAC=NaCO3,DPNAS=NaSO4,DPKAS=KSO4,DPH1P=HPO4
C     DPH2P=H2PO4,DPH3P=H3PO4,DPF1P=FeHPO4,DPF2P=FeH2PO4
C     DPC0P=CaPO4,DPC1P=CaHPO4,DPC2P=CaH2PO4
C     DPM1P=MgHPO4,DPCOH=R-COO,DPALO=R-AlOH2,DPFEO=R-FeOH2
C     COOH=COOH
C
      PARAMETER (DPH2O=1.0E-08,SPALO=3.0E-22,SPFEO=2.8E-27
     2,SPCAC=3.3E-03,SPCAS=1.4E+01,SPALP=7.2E-18,SPFEP=4.8E-23
     3,SPCAM=7.0E+07,SPCAD=1.0E-01,SPCAH=2.0E-31,SXOH2=4.5E-05
     4,SXOH1=1.1E-06,SXH2P=1.5E+07,SXH1P=0.75E+06
     5,DPCO2=4.2E-04,DPHCO=5.6E-08,DPN4=5.5E-07
     6,DPAL1=4.6E-07,DPAL2=7.3E-07,DPAL3=1.8E-05
     7,DPAL4=1.2E-05,DPALS=0.16,DPFE1=2.7E-08,DPFE2=4.5E-07
     8,DPFE3=2.5E-05,DPFE4=1.2E-05,DPFES=7.1E-02,DPCAO=12.5
     9,DPCAC=4.2E-02,DPCAH=13.5,DPCAS=1.2,DPMGO=0.7,DPMGC=0.3
     1,DPMGH=67.0,DPMGS=2.1,DPNAC=0.45,DPNAS=3.3E+02,DPKAS=5.0E+01
     2,DPH1P=2.1E-10,DPH2P=6.2E-05,DPH3P=7.5,DPF1P=4.5E-02
     3,DPF2P=3.7E-03,DPC0P=3.5E-04,DPC1P=1.82,DPC2P=40.0
     4,DPM1P=1.23,DPCOH=1.0E-02,DPALO=6.3E-02,DPFEO=6.3E-02
     5,COOH=1.0E+03)
C
C     DISSOCIATION CONSTANTS CALCULATED FROM OTHER CONSTANTS
C
      PARAMETER (DPCO3=DPCO2*DPHCO,SHALO=SPALO/DPH2O**3
     2,SYAL1=SPALO/DPAL1,SHAL1=SYAL1/DPH2O**2,SYAL2=SYAL1/DPAL2
     3,SHAL2=SYAL2/DPH2O,SPAL3=SYAL2/DPAL3,SYAL4=SPAL3/DPAL4
     4,SHAL4=SYAL4*DPH2O,SHFEO=SPFEO/DPH2O**3,SYFE1=SPFEO/DPFE1
     5,SHFE1=SYFE1/DPH2O**2,SYFE2=SYFE1/DPFE2,SHFE2=SYFE2/DPH2O
     6,SPFE3=SYFE2/DPFE3,SYFE4=SPFE3/DPFE4,SHFE4=SYFE4*DPH2O
     7,SHCAC1=SPCAC/DPHCO,SYCAC1=SHCAC1*DPH2O,SHCAC2=SHCAC1/DPCO2
     8,SYCAC2=SHCAC2*DPH2O**2,SHA0P1=SPALP/DPH1P,SYA0P1=SHA0P1*DPH2O
     9,SPA1P1=SYA0P1/DPAL1,SYA2P1=SPA1P1/DPAL2,SHA2P1=SYA2P1*DPH2O
     1,SYA3P1=SYA2P1/DPAL3,SHA3P1=SYA3P1*DPH2O**2,SYA4P1=SYA3P1/DPAL4
     2,SHA4P1=SYA4P1*DPH2O**3,SHA0P2=SHA0P1/DPH2P
     3,SYA0P2=SHA0P2*DPH2O**2,SYA1P2=SYA0P2/DPAL1,SHA1P2=SYA1P2/DPH2O
     4,SPA2P2=SYA1P2/DPAL2,SYA3P2=SPA2P2/DPAL3,SHA3P2=SYA3P2*DPH2O
     5,SYA4P2=SYA3P2/DPAL4,SHA4P2=SYA4P2*DPH2O**2)
      PARAMETER (SHF0P1=SPFEP/DPH1P,SYF0P1=SHF0P1*DPH2O
     2,SPF1P1=SYF0P1/DPFE1,SYF2P1=SPF1P1/DPFE2,SHF2P1=SYF2P1*DPH2O
     3,SYF3P1=SYF2P1/DPFE3,SHF3P1=SYF3P1*DPH2O**2,SYF4P1=SYF3P1/DPFE4
     4,SHF4P1=SYF4P1*DPH2O**3,SHF0P2=SHF0P1/DPH2P
     4,SYF0P2=SHF0P2*DPH2O**2
     5,SYF1P2=SYF0P2/DPFE1,SHF1P2=SYF1P2/DPH2O,SPF2P2=SYF1P2/DPFE2
     6,SYF3P2=SPF2P2/DPFE3,SHF3P2=SYF3P2*DPH2O,SYF4P2=SYF3P2/DPFE4
     7,SHF4P2=SYF4P2*DPH2O**2,SHCAD2=SPCAD/DPH2P,SYCAD2=SHCAD2*DPH2O
     8,SHCAH1=SPCAH/(DPH2O*DPH1P**3),SYCAH1=SHCAH1*DPH2O**4
     9,SHCAH2=SHCAH1/DPH2P**3,SYCAH2=SHCAH2*DPH2O**7)
C
C     TPD,TADA,TADC,TSL=rate constants for equilibrating precipitation
C        adsorption (anion,cation),solution reactions
C
      PARAMETER (TPD=5.0E-03,TADA=5.0E-03,TADC=5.0E-02,TSL=5.0E-01
     2,ZEROC=1.0E-48,MRXN=1000,FCHY=0.25,FCOH=0.25)
C
C     INITIALIZE CATION AND ANION CONCENTRATIONS
C     IN PRECIPITATION (K=1), IRRIGATION (K=2) AND SOIL (K=3)
C     FROM WEATHER, IRRIGATION AND SOIL FILES IN 'READS'
C
C     CCO2E,CCH4E,COXYE,ZZ2GE,CZ2OE=atmospheric CO2,CH4,N2,N2O
C        concentrations (g m-3)
C
      DO 9995 NX=NHW,NHE
      DO 9990 NY=NVN,NVS
      CCO2M=CCO2EI(NY,NX)/12.0
      CCH4M=CCH4E(NY,NX)/12.0
      COXYM=COXYE(NY,NX)/32.0
      CZ2GM=CZ2GE(NY,NX)/14.0
      CZ2OM=CZ2OE(NY,NX)/14.0
      DO 1200 I=1,366
      DO 1200 L=NU(NY,NX),NL(NY,NX)
      DO 2000 K=1,3
C
C     INITIALIZE IONS IN RAINFALL (K=1)
C
C     PHR,CN4R,CNOR,CPOR,CALR,CFER,CCAR,CMGR,CNAR,CKAR, 
C        CSOR,CCLR=pH,NH4,NO3,H2PO4,Al,Fe,Ca,Mg,Na,K,SO4,Cl 
C        concentration in precipitation from weather file (g m-3)
C
      IF(K.EQ.1.AND.I.EQ.1.AND.L.EQ.1)THEN
      PH1=PHR(NY,NX)
      CHY1=10.0**(-(PHR(NY,NX)-3.0))
      COH1=DPH2O/CHY1
      CN4Z=CN4R(NY,NX)/14.0
      CNOZ=CNOR(NY,NX)/14.0
      CPOZ=CPOR(NY,NX)/31.0
      CALZ=CALR(NY,NX)
      CFEZ=CFER(NY,NX)
      CCAZ=CCAR(NY,NX)
      CMGZ=CMGR(NY,NX)
      CNAZ=CNAR(NY,NX)
      CKAZ=CKAR(NY,NX)
      CSOZ=CSOR(NY,NX)
      CCLZ=CCLR(NY,NX)
C
C     INITIALIZE IRRIGATION WATER (K=2)
C
C     PHI,CN4Q,CNOQ,CPOQ,CALQ,CFEQ,CCAQ,CMGQ,CNAQ,CKAQ, 
C        CSOQ,CCLQ=pH,NH4,NO3,H2PO4,Al,Fe,Ca,Mg,Na,K,SO4,Cl 
C        concentration in irrigation from irrigation file (g m-3)
C
      ELSEIF(K.EQ.2.AND.L.EQ.1)THEN
      PH1=PHQ(I,NY,NX)
      CHY1=10.0**(-(PHQ(I,NY,NX)-3.0))
      COH1=DPH2O/CHY1
      CN4Z=CN4Q(I,NY,NX)/14.0
      CNOZ=CNOQ(I,NY,NX)/14.0
      CPOZ=CPOQ(I,NY,NX)/31.0
      CALZ=CALQ(I,NY,NX)
      CFEZ=CFEQ(I,NY,NX)
      CCAZ=CCAQ(I,NY,NX)
      CMGZ=CMGQ(I,NY,NX)
      CNAZ=CNAQ(I,NY,NX)
      CKAZ=CKAQ(I,NY,NX)
      CSOZ=CSOQ(I,NY,NX)
      CCLZ=CCLQ(I,NY,NX)
C
C     INITIALIZE IONS IN SOIL WATER N (K=3)
C
C     C*=soluble concentration from sat. paste extract in soil file 
C        NH4,NO3,PO4=NH4-N,NO3-N,H2PO4-P (g Mg-1)
C        AL,FE,CA,MG,NA,KA,SO4,CL=Al,Fe,Ca,Mg,Na,K,SO4-S,Cl (mol Mg-1)
C     CALPO,CFEPO,CCAPD,CCAPH=AlPO4,FePO4,CaHPO4,apatite from soil file
C        (g Mg-1)
C     CALOH,CFEOH,CCACO,CCASO=AlOH3,FeOH3,CaSO4,CaCO3 from soil file 
C        (g Mg-1)
C     BKVL,VOLA,VOLW=soil mass (Mg),porosity (m3),water content (m3)
C     XCEC,XAEC=cation,anion exchange capacity (mol)
C     PH=soil pH from soil file
C
      ELSEIF(K.EQ.3.AND.I.EQ.1)THEN
      IF(BKVL(L,NY,NX).GT.ZEROS(NY,NX))THEN
      BKVLX=BKVL(L,NY,NX)
      ELSE
      BKVLX=VOLA(L,NY,NX)
      ENDIF
      IF(VOLW(L,NY,NX).GT.ZEROS(NY,NX))THEN
      BKVLW=AMIN1(1.0,BKVLX/VOLW(L,NY,NX))
      ELSE
      BKVLW=1.0
      ENDIF
      CN4X=0.1*CNH4(L,NY,NX)
      CNOX=CNO3(L,NY,NX) 
      CPOX=0.01*CPO4(L,NY,NX)
      CALX=CAL(L,NY,NX)
      CFEX=CFE(L,NY,NX)
      CCAX=CCA(L,NY,NX)
      CMGX=CMG(L,NY,NX)
      CNAX=CNA(L,NY,NX)
      CKAX=CKA(L,NY,NX)
      CSOX=CSO4(L,NY,NX)
      CCLX=CCL(L,NY,NX)
      CALPOX=CALPO(L,NY,NX)
      CFEPOX=CFEPO(L,NY,NX)
      CCAPDX=CCAPD(L,NY,NX)
      CCAPHX=CCAPH(L,NY,NX)
      CALOHX=CALOH(L,NY,NX)
      CFEOHX=CFEOH(L,NY,NX)
      CCACOX=CCACO(L,NY,NX)
      CCASOX=CCASO(L,NY,NX)
      XCEC(L,NY,NX)=AMAX1(CN4X,CEC(L,NY,NX))*BKVLX
      XAEC(L,NY,NX)=AMAX1(CPOX,AEC(L,NY,NX))*BKVLX
      CHY1=10.0**(-(PH(L,NY,NX)-3.0))
      COH1=DPH2O/CHY1
      CN4Z=CN4X
      CNOZ=CNOX
      CPOZ=CPOX
      CALZ=CALX
      CFEZ=CFEX
      CCAZ=CCAX
      CMGZ=CMGX
      CNAZ=CNAX
      CKAZ=CKAX
      CSOZ=CSOX
      CCLZ=CCLX
      ELSE
      GO TO 2000
      ENDIF
C
C     INITIALIZE SOIL GAS CONCENTRATIONS FROM SOLUBILITY COEFFICIENTS
C
C     ATCA=mean annual air temperature (oC) from site file
C     C*M=atmospheric gas concentration (mol m-3)
C     C*1=soil aqueous gas concentration (mol m-3)
C     S*X=gas solubility (mol m-3 / (mol m-3))
C
      IF(K.NE.3)THEN
      CCO21=CCO2M*SCO2X/EXP(ACO2X)
     2*EXP(0.843-0.0281*ATCA(NY,NX))
      ELSE
      CCO21=10.0*CCO2M*SCO2X/EXP(ACO2X)
     2*EXP(0.843-0.0281*ATCA(NY,NX))
      ENDIF
      CCO31=CCO21*DPCO3/CHY1**2
      CHCO31=CCO21*DPCO2/CHY1
      CCH41=CCH4M*SCH4X/EXP(ACH4X)
     2*EXP(0.597-0.0199*ATCA(NY,NX))
      COXY1=COXYM*SOXYX/EXP(AOXYX)
     2*EXP(0.516-0.0172*ATCA(NY,NX))
      CZ2G1=CZ2GM*SN2GX/EXP(AN2GX)
     2*EXP(0.456-0.0152*ATCA(NY,NX))
      CZ2O1=CZ2OM*SN2OX/EXP(AN2OX)
     2*EXP(0.897-0.0299*ATCA(NY,NX))
      CNO1=CNOZ
C
C     INITIALIZE ION PAIR EQUILIBRIA FROM DISSOCIATION CONSTANTS
C
C     C*1=solute concentration (mol m-3)
C     DP*=dissociation constant from PARAMETER above
C     SP*=solubility product from PARAMETER above 
C
      IF(K.NE.3)THEN
      CN41=CN4Z/(1.0+DPN4/CHY1)
      CN31=CN41*DPN4/CHY1
      ELSE
      CN41=CN4Z*0.10
      CN31=0.0
      ENDIF
      IF(CALZ.LT.0.0)THEN
      CAL1=SPALO/COH1**3
      ELSE
      CAL1=AMIN1(CALZ,SPALO/COH1**3)
      ENDIF
      IF(CFEZ.LT.0.0)THEN
      CFE1=SPFEO/COH1**3
      ELSE
      CFE1=AMIN1(CFEZ,SPFEO/COH1**3)
      ENDIF
      IF(K.LE.2)THEN
      CCA1=CCAZ
      ELSE
      CCA1=AMIN1(CCAZ,SPCAC/CCO31) 
      ENDIF
      CMG1=CMGZ
      CNA1=CNAZ
      CKA1=CKAZ
      CSO41=CSOZ
      CCL1=CCLZ
      CALO1=CAL1*COH1/DPAL1
      CALO2=CAL1*COH1**2/(DPAL1*DPAL2)
      CALO3=CAL1*COH1**3/(DPAL1*DPAL2*DPAL3)
      CALO4=CAL1*COH1**4/(DPAL1*DPAL2*DPAL3*DPAL4)
      CALS1=0.0
      CFEO1=CFE1*COH1/DPFE1
      CFEO2=CFE1*COH1**2/(DPFE1*DPFE2)
      CFEO3=CFE1*COH1**3/(DPFE1*DPFE2*DPFE3)
      CFEO4=CFE1*COH1**4/(DPFE1*DPFE2*DPFE3*DPFE4)
      CFES1=0.0
      CCAO1=CCA1*COH1/DPCAO
      CCAC1=CCA1*CCO31**2/DPCAC
      CCAH1=CCA1*CHCO31/DPCAH
      CCAS1=0.0
      CMGO1=CMG1*COH1/DPMGO
      CMGC1=CMG1*CCO31**2/DPMGC
      CMGH1=CMG1*CHCO31/DPMGH
      CMGS1=0.0
      CNAC1=CNA1*CCO31/DPNAC
      CNAS1=0.0
      CKAS1=0.0
      CF1P1=0.0
      CF2P1=0.0
      CC0P1=0.0
      CC1P1=0.0
      CC2P1=0.0
      CM1P1=0.0
C
C     INITIALIZE PHOSPHORUS EQUILIBRIA AMONG SOLUBLE, ADSORBED
C     AND PRECIPITATED FORMS FROM SOULUBILITY PRODUCTS
C
C     C*1=solute P concentration (mol m-3)
C     DP*=dissociation constant from PARAMETER above
C     SP*=solubility product from PARAMETER above 
C     X*=exchangeable P concentration (mol Mg-1)
C     XAEC=anion exchange capacity (mol)
C
      IF(K.NE.3)THEN
      CH3P1=CPOZ/(1.0+DPH3P/CHY1+DPH3P*DPH2P
     2/(CHY1**2)+DPH3P*DPH2P*DPH1P/CHY1**3)
      CH2P1=CH3P1*DPH3P/CHY1
      CH1P1=CH3P1*DPH3P*DPH2P/CHY1**2
      CH0P1=CH3P1*DPH3P*DPH2P*DPH1P/CHY1**3
      ELSE
      XHP=CPOZ 
      XOH=XAEC(L,NY,NX)/BKVLX
      FHP3=1.0/(1.0+DPH3P/CHY1+DPH3P*DPH2P
     2/CHY1**2+DPH3P*DPH2P*DPH1P/CHY1**3)
      FHP2=FHP3*DPH3P/CHY1
      FHP1=FHP3*DPH3P*DPH2P/CHY1**2
      FHP0=FHP3*DPH3P*DPH2P*DPH1P/CHY1**3
      SPOH2=SXOH2
      SPOH1=SXOH1
      SPH2P=SXH2P*DPH2O
      SPH1P=SXH1P*DPH2O
      FXH2=1.0/(1.0+SPOH2/CHY1+SPOH2*SPOH1/CHY1**2)
      FXH1=FXH2*SPOH2/CHY1
      FXH0=FXH1*SPOH1/CHY1
      FXP2=1.0/(1.0+SXH2P*DPH2P/(SXH1P*CHY1))
      FXP1=FXP2*SXH2P*DPH2P/(SXH1P*CHY1)
      FHPA=FHP2
      XPT=AMIN1(XOH,CPO4(L,NY,NX))
      XOH21=(XOH-XPT)*FXH2
      XOH11=(XOH-XPT)*FXH1
      XOH01=(XOH-XPT)*FXH0
      XH1P1=XPT*FXP1
      XH2P1=XPT*FXP2
      CH3P1=XHP*FHP3
      CH2P1=XHP*FHP2
      CH1P1=XHP*FHP1
      CH0P1=XHP*FHP0
      ENDIF
C     IF(K.EQ.3)THEN
C     WRITE(*,1109)'STARTE',I,L,K 
C    2,XH1P1,XH2P1,XOH01,XOH11,XOH21
C    3,XH1P1+XH2P1+XOH01+XOH11+XOH21
C    4,XH1P1/BKVL(L,NY,NX),XH2P1/BKVL(L,NY,NX)
C    4,XOH,XHP,XPT,FXP1,FXP2,XAEC(L,NY,NX),BKVLX,CPO4(L,NY,NX)
C    5,CH0P1,CH1P1,CH2P1,CH3P1
1109  FORMAT(A8,3I4,30E12.4)
C     ENDIF
C
C     INITIALIZE EQUILIBRIA BETWEEN SOLUBLE AND PRECIPITATED FORMS
C
C     P*1=precipitated Al(OH)3, Fe(OH)3, CaCO3, CaSO4, AlPO4, FePO4, 
C        Ca(H2PO4)2, CaHPO4, apatite from soil file (mol(Mg-1) 
C     VLPO4,VLPOB=fraction of soil volume in non-band,band P zones
C
      IF(K.EQ.3)THEN
      PALOH1=CALOHX
      PFEOH1=CFEOHX
      PCACO1=CCACOX
      PCASO1=CCASOX
      PALPO1=CALPOX
      PFEPO1=CFEPOX
      PCAPD1=CCAPDX
      PCAPH1=CCAPHX
C
C     INITIALIZE CATION EQILIBRIA BETWEEN SOLUBLE
C     AND EXCHANGEABLE FORMS
C
C     XCEC=cation exchange capacity from soil file (mol)
C     BKVL=soil mass (Mg)
C     ORGC=SOC (g Mg-1) from soil file
C     XCOOH,XHC1=total carboxyl exchange sites,occupied by H+ (mol)
C     ORGC=SOC (g)
C
      CCEC=AMAX1(ZEROC,XCEC(L,NY,NX)/BKVLX)
      XCECQ=AMAX1(CN4X,CEC(L,NY,NX))
      IF(BKVL(L,NY,NX).GT.ZEROS(NY,NX))THEN
      BKVLX=BKVL(L,NY,NX)
      ELSE
      BKVLX=VOLW(L,NY,NX)
      ENDIF
      XCOOH=AMAX1(ZEROC,COOH*1.0E-06*ORGC(L,NY,NX)/BKVLX)
      XHC1=XCOOH*AHY1/DPCOH 
      ENDIF
C
C     CONVERGE TOWARDS ALL SOLUBILITY EQUILIBRIA
C
      DO 1000 M=1,MRXN
C
C     ION ACTIVITY COEFFICIENTS
C
C     CC*,CA*=total cation,anion concentration (mol m-3)
C     CSTR*=ion strengths
C     A*S=ion activity coefficients
C     SP*,SH*=solubility product from PARAMETER above 
C     R*,P*=reactants, products of solubility reactions
C
      CC3=CAL1+CFE1
      CA3=CH0P1
      CC2=CCA1+CMG1+CALO1+CFEO1+CF2P1
      CA2=CSO41+CCO31+CH1P1
      CC1=CN41+CHY1+CNA1+CKA1+CALO2+CFEO2+CALS1+CFES1+CCAO1
     2+CCAH1+CMGO1+CMGH1+CF1P1+CC2P1
      CA1=CNO1+COH1+CHCO31+CCL1+CALO4+CFEO4+CNAC1+CNAS1+CKAS1
     2+CH2P1+CC0P1
      CSTR1=1.0E-03*(9.0*(CC3+CA3)+4.0*(CC2+CA2)+CC1+CA1)
      CSTRQ=SQRT(CSTR1)
      CSTRX=CSTRQ/(1.0+CSTRQ)-0.20*CSTR1
      A1S=AMIN1(1.0,10.0**(-0.509*1.0*CSTRX))
      A2S=AMIN1(1.0,10.0**(-0.509*4.0*CSTRX))
      A3S=AMIN1(1.0,10.0**(-0.509*9.0*CSTRX))
C
C     PRECIPITATION-DISSOLUTION EQUILIBRIA FROM SOLUBILITY PRODUCTS
C
C     A*1=ion activity
C
      AHY1=CHY1*A1S
      AOH1=COH1*A1S
      AAL1=CAL1*A3S
      AALO1=CALO1*A2S
      AALO2=CALO2*A1S
      AALO3=CALO3
      AALO4=CALO4*A1S
      AFE1=CFE1*A3S
      AFEO1=CFEO1*A2S
      AFEO2=CFEO2*A1S
      AFEO3=CFEO3
      AFEO4=CFEO4*A1S
      ACA1=CCA1*A2S
      ACO31=CCO31*A2S
      AHCO31=CHCO31*A1S
      ACO21=CCO21
      ASO41=CSO41*A2S
      AH0P1=CH0P1*A3S
      AH1P1=CH1P1*A2S
      AH2P1=CH2P1*A1S
      AH3P1=CH3P1
      AF1P1=CF1P1*A2S
      AF2P1=CF2P1*A1S
      AC0P1=CC0P1*A1S
      AC1P1=CC1P1
      AC2P1=CC2P1*A1S
      AM1P1=CM1P1
      AN41=CN41*A1S
      AN31=CN31
      AMG1=CMG1*A2S
      ANA1=CNA1*A1S
      AKA1=CKA1*A1S
      AALS1=CALS1*A1S
      AFES1=CFES1*A1S
      ACAO1=CCAO1*A1S
      ACAC1=CCAC1
      ACAS1=CCAS1
      ACAH1=CCAH1*A1S
      AMGO1=CMGO1*A1S
      AMGC1=CMGC1
      AMGH1=CMGH1*A1S
      AMGS1=CMGS1
      ANAC1=CNAC1*A1S
      ANAS1=CNAS1*A1S
      AKAS1=CKAS1*A1S
      IF(K.EQ.3)THEN
C
C     ALUMINUM HYDROXIDE (GIBBSITE)
C
      PX=AMAX1(AAL1,AALO1,AALO2,AALO3,AALO4)
      IF(PX.EQ.AAL1)THEN
      R1=AHY1
      P1=AAL1
      P2=AOH1
      NR1=3
      NP2=0
      SP=SHALO 
      ELSEIF(PX.EQ.AALO1)THEN
      R1=AHY1
      P1=AALO1
      P2=AOH1
      NR1=2
      NP2=0
      SP=SHAL1 
      ELSEIF(PX.EQ.AALO2)THEN
      R1=AHY1
      P1=AALO2
      P2=AOH1
      NR1=1
      NP2=0
      SP=SHAL2
      ELSEIF(PX.EQ.AALO3)THEN
      R1=AHY1
      P1=AALO3
      P2=AOH1
      NR1=0
      NP2=0
      SP=SPAL3
      ELSEIF(PX.EQ.AALO4)THEN
      R1=AOH1
      P1=AALO4
      P2=AHY1
      NR1=0
      NP2=1
      SP=SHAL4 
      ENDIF
      RHAL1=0.0
      RHALO1=0.0
      RHALO2=0.0
      RHALO3=0.0
      RHALO4=0.0
      SPX=SP*R1**NR1/P2**NP2
      RPALOX=AMAX1(-PALOH1,AMIN1(FCOH*COH1,TPD*(P1-SPX)))
      IF(PX.EQ.AAL1)THEN
      RHAL1=RPALOX
      ELSEIF(PX.EQ.AALO1)THEN
      RHALO1=RPALOX
      ELSEIF(PX.EQ.AALO2)THEN
      RHALO2=RPALOX
      ELSEIF(PX.EQ.AALO3)THEN
      RHALO3=RPALOX
      ELSEIF(PX.EQ.AALO4)THEN
      RHALO4=RPALOX
      ENDIF
C     IF((M/25)*25.EQ.M.AND.L.EQ.1)THEN 
C     WRITE(*,1112)'ALOHI',I,L,K,M,PALOH1,AAL1
C    2,AALO1,AALO2,AALO3,AALO4,AOH1,CAL1,CALO1,CALO2,CALO3,CALO4
C    2,COH1,R1,P1,P2,SP,SPX,RPALOX,RHAL1,RHALO1,RHALO2,RHALO3,RHALO4
C    3,AAL1*AOH1**3,SPALO,A1
C     ENDIF
C
C     IRON HYDROXIDE
C
      PX=AMAX1(AFE1,AFEO1,AFEO2,AFEO3,AFEO4)
      IF(PX.EQ.AFE1)THEN
      R1=AHY1
      P1=AFE1
      P2=AOH1
      NR1=3
      NP2=0
      SP=SHFEO 
      ELSEIF(PX.EQ.AFEO1)THEN
      R1=AHY1
      P1=AFEO1
      P2=AOH1
      NR1=2
      NP2=0
      SP=SHFE1 
      ELSEIF(PX.EQ.AFEO2)THEN
      R1=AHY1
      P1=AFEO2
      P2=AOH1
      NR1=1
      NP2=0
      SP=SHFE2
      ELSEIF(PX.EQ.AFEO3)THEN
      R1=AHY1
      P1=AFEO3
      P2=AOH1
      NR1=0
      NP2=0
      SP=SPFE3
      ELSEIF(PX.EQ.AFEO4)THEN
      R1=AOH1
      P1=AFEO4
      P2=AHY1
      NR1=0
      NP2=1
      SP=SHFE4 
      ENDIF
      RHFE1=0.0
      RHFEO1=0.0
      RHFEO2=0.0
      RHFEO3=0.0
      RHFEO4=0.0
      SPX=SP*R1**NR1/P2**NP2
      RPFEOX=AMAX1(-PFEOH1,AMIN1(FCOH*COH1,TPD*(P1-SPX)))
      IF(PX.EQ.AFE1)THEN
      RHFE1=RPFEOX
      ELSEIF(PX.EQ.AFEO1)THEN
      RHFEO1=RPFEOX
      ELSEIF(PX.EQ.AFEO2)THEN
      RHFEO2=RPFEOX
      ELSEIF(PX.EQ.AFEO3)THEN
      RHFEO3=RPFEOX
      ELSEIF(PX.EQ.AFEO4)THEN
      RHFEO4=RPFEOX
      ENDIF
C     IF((M/25)*25.EQ.M)THEN 
C     WRITE(*,1112)'FEOHI',I,L,K,M,PFEOH1,AFE1
C    2,AFEO1,AFEO2,AFEO3,AFEO4
C    2,AOH1,R1,P1,P2,SP,SPX,RPFEOX,RHFE1,RHFEO1,RHFEO2,RHFEO3,RHFEO4
C    3,AFE1*AOH1**3,SPFEO 
C     ENDIF
C
C     CALCITE
C
      PX=AMAX1(ACO31,AHCO31,ACO21)
      R1=AHY1
      P1=ACA1
      IF(PX.EQ.ACO31)THEN
      P2=ACO31
      NR1=0
      SP=SPCAC 
      ELSEIF(PX.EQ.AHCO31)THEN
      P2=AHCO31
      NR1=1
      SP=SHCAC1 
      ELSEIF(PX.EQ.ACO21)THEN
      P2=ACO21
      NR1=2
      SP=SHCAC2
      ENDIF
      RHCAC3=0.0
      RHCACH=0.0
      RHCACO=0.0
      SPX=SP*R1**NR1 
      S0=P1+P2
      S1=AMAX1(0.0,S0**2-4.0*(P1*P2-SPX))
      RPCACX=AMAX1(-PCACO1,-FCHY*CHY1,TPD*0.5*(S0-SQRT(S1)))
      IF(PX.EQ.ACO31)THEN
      RHCAC3=RPCACX
      ELSEIF(PX.EQ.AHCO31)THEN
      RHCACH=RPCACX
      ELSEIF(PX.EQ.ACO21)THEN
      RHCACO=RPCACX
      ENDIF
C     IF(K.EQ.3.AND.(M.LE.10.OR.INT(M/100)*100.EQ.M).AND.L.EQ.1)THEN
C     WRITE(*,1112)'CALC',I,L,K,M,PCACO1,RPCACX,ACA1,AHCO31,SPX 
C    3,ACA1*AHCO31,SHCAC1*AHY1
C    2,ACA1*ACO21,SHCAC2*AHY1**2,ACA1*ACO31,SPCAC
C     ENDIF
C
C     GYPSUM
C
      P1=ACA1
      P2=ASO41
      SPX=SPCAS 
      S0=P1+P2
      S1=AMAX1(0.0,S0**2-4.0*(P1*P2-SPX))
      RPCASO=AMAX1(-PCASO1,TPD*0.5*(S0-SQRT(S1)))
C     IF(K.EQ.3.AND.(M.LE.10.OR.INT(M/100)*100.EQ.M).AND.L.EQ.1)THEN
C     WRITE(*,1112)'GYPS',I,L,K,M,PCASO1,RPCASO,ACA1,ASO41
C    3,ACA1*ASO41,SPCAS
C     ENDIF
C
C     PHOSPHORUS PRECIPITATION-DISSOLUTION IN NON-BAND SOIL ZONE
C
C
C     ALUMINUM PHOSPHATE (VARISCITE)
C
      PX=AMAX1(AAL1,AALO1,AALO2,AALO3,AALO4)
      PY=AMAX1(AH1P1,AH2P1)
      R1=AHY1
      P3=AHY1
      IF(PY.EQ.AH1P1)THEN
      P2=AH1P1
      IF(PX.EQ.AAL1)THEN
      P1=AAL1
      NR1=1
      NP3=0
      SP=SHA0P1 
      ELSEIF(PX.EQ.AALO1)THEN
      P1=AALO1
      NR1=0
      NP3=0
      SP=SPA1P1 
      ELSEIF(PX.EQ.AALO2)THEN
      P1=AALO2
      NR1=0
      NP3=1
      SP=SHA2P1 
      ELSEIF(PX.EQ.AALO3)THEN
      P1=AALO3
      NR1=0
      NP3=2
      SP=SHA3P1 
      ELSEIF(PX.EQ.AALO4)THEN
      P1=AALO4
      NR1=0
      NP3=3
      SP=SHA4P1 
      ENDIF
      ELSE
      P2=AH2P1
      IF(PX.EQ.AAL1)THEN
      P1=AAL1
      NR1=2
      NP3=0
      SP=SHA0P2 
      ELSEIF(PX.EQ.AALO1)THEN
      P1=AALO1
      NR1=1
      NP3=0
      SP=SHA1P2
      ELSEIF(PX.EQ.AALO2)THEN
      P1=AALO2
      NR1=0
      NP3=0
      SP=SPA2P2 
      ELSEIF(PX.EQ.AALO3)THEN
      P1=AALO3
      NR1=0
      NP3=1
      SP=SHA3P2 
      ELSEIF(PX.EQ.AALO4)THEN
      P1=AALO4
      NR1=0
      NP3=2
      SP=SHA4P2 
      ENDIF
      ENDIF
      RHA0P1=0.0
      RHA1P1=0.0
      RHA2P1=0.0
      RHA3P1=0.0
      RHA4P1=0.0
      RHA0P2=0.0
      RHA1P2=0.0
      RHA2P2=0.0
      RHA3P2=0.0
      RHA4P2=0.0
      SPX=SP*R1**NR1/P3**NP3
      S0=P1+P2
      S1=AMAX1(0.0,S0**2-4.0*(P1*P2-SPX))
      RPALPX=AMAX1(-PALPO1,-FCOH*COH1,TPD*0.5*(S0-SQRT(S1)))
      IF(PY.EQ.AH1P1)THEN
      IF(PX.EQ.AAL1)THEN
      RHA0P1=RPALPX
      ELSEIF(PX.EQ.AALO1)THEN
      RHA1P1=RPALPX
      ELSEIF(PX.EQ.AALO2)THEN
      RHA2P1=RPALPX
      ELSEIF(PX.EQ.AALO3)THEN
      RHA3P1=RPALPX
      ELSEIF(PX.EQ.AALO4)THEN
      RHA4P1=RPALPX
      ENDIF
      ELSE
      IF(PX.EQ.AAL1)THEN
      RHA0P2=RPALPX
      ELSEIF(PX.EQ.AALO1)THEN
      RHA1P2=RPALPX
      ELSEIF(PX.EQ.AALO2)THEN
      RHA2P2=RPALPX
      ELSEIF(PX.EQ.AALO3)THEN
      RHA3P2=RPALPX
      ELSEIF(PX.EQ.AALO4)THEN
      RHA4P2=RPALPX
      ENDIF
      ENDIF
C     IF((M/25)*25.EQ.M)THEN 
C     WRITE(*,1112)'ALPO4I',I,L,K,M,PALPO1,AAL1
C    2,AALO1,AALO2,AALO3,AALO4
C    2,AH0P1,AH1P1,AH2P1,AHY1,AOH1,RPALPX,RHA0P1,RHA1P1,RHA2P1,RHA3P1 
C    3,RHA4P1,RHA0P2,RHA1P2,RHA2P2,RHA3P2,RHA4P2,SP,SPX,AAL1*AH0P1 
C    4,SPALP 
1112  FORMAT(A8,4I4,/,8F16.8,/,8F16.8,/,8F16.8,/,8F16.8,/
     2,8F16.8,/,8F16.8,/,8F16.8,/,8F16.8)
C     ENDIF
C
C     IRON PHOSPHATE (STRENGITE)
C
      PX=AMAX1(AFE1,AFEO1,AFEO2,AFEO3,AFEO4)
      PY=AMAX1(AH1P1,AH2P1)
      R1=AHY1
      P3=AHY1
      IF(PY.EQ.AH1P1)THEN
      P2=AH1P1
      IF(PX.EQ.AFE1)THEN
      P1=AFE1
      NR1=1
      NP3=0
      SP=SHF0P1 
      ELSEIF(PX.EQ.AFEO1)THEN
      P1=AFEO1
      NR1=0
      NP3=0
      SP=SPF1P1 
      ELSEIF(PX.EQ.AFEO2)THEN
      P1=AFEO2
      NR1=0
      NP3=1
      SP=SHF2P1 
      ELSEIF(PX.EQ.AFEO3)THEN
      P1=AFEO3
      NR1=0
      NP3=2
      SP=SHF3P1 
      ELSEIF(PX.EQ.AFEO4)THEN
      P1=AFEO4
      NR1=0
      NP3=3
      SP=SHF4P1 
      ENDIF
      ELSE
      P2=AH2P1
      IF(PX.EQ.AFE1)THEN
      P1=AFE1
      NR1=2
      NP3=0
      SP=SHF0P2 
      ELSEIF(PX.EQ.AFEO1)THEN
      P1=AFEO1
      NR1=1
      NP3=0
      SP=SHF1P2 
      ELSEIF(PX.EQ.AFEO2)THEN
      P1=AFEO2
      NR1=0
      NP3=0
      SP=SPF2P2 
      ELSEIF(PX.EQ.AFEO3)THEN
      P1=AFEO3
      NR1=0
      NP3=1
      SP=SHF3P2 
      ELSEIF(PX.EQ.AFEO4)THEN
      P1=AFEO4
      NR1=0
      NP3=2
      SP=SHF4P2 
      ENDIF
      ENDIF
      RHF0P1=0.0
      RHF1P1=0.0
      RHF2P1=0.0
      RHF3P1=0.0
      RHF4P1=0.0
      RHF0P2=0.0
      RHF1P2=0.0
      RHF2P2=0.0
      RHF3P2=0.0
      RHF4P2=0.0
      SPX=SP*R1**NR1/P3**NP3
      S0=P1+P2
      S1=AMAX1(0.0,S0**2-4.0*(P1*P2-SPX))
      RPFEPX=AMAX1(-PFEPO1,-FCOH*COH1,TPD*0.5*(S0-SQRT(S1)))
      IF(PY.EQ.AH1P1)THEN
      IF(PX.EQ.AFE1)THEN
      RHF0P1=RPFEPX
      ELSEIF(PX.EQ.AFEO1)THEN
      RHF1P1=RPFEPX
      ELSEIF(PX.EQ.AFEO2)THEN
      RHF2P1=RPFEPX
      ELSEIF(PX.EQ.AFEO3)THEN
      RHF3P1=RPFEPX
      ELSEIF(PX.EQ.AFEO4)THEN
      RHF4P1=RPFEPX
      ENDIF
      ELSE
      IF(PX.EQ.AFE1)THEN
      RHF0P2=RPFEPX
      ELSEIF(PX.EQ.AFEO1)THEN
      RHF1P2=RPFEPX
      ELSEIF(PX.EQ.AFEO2)THEN
      RHF2P2=RPFEPX
      ELSEIF(PX.EQ.AFEO3)THEN
      RHF3P2=RPFEPX
      ELSEIF(PX.EQ.AFEO4)THEN
      RHF4P2=RPFEPX
      ENDIF
      ENDIF
      IF((M/100)*100.EQ.M)THEN 
C     IF(L.EQ.9)THEN
C     WRITE(*,1112)'RPFEPXS',I,L,K,M,RPFEPX 
C    2,RHF0P1,RHF1P1,RHF2P1,RHF3P1 
C    3,RHF4P1,RHF0P2,RHF1P2,RHF2P2,RHF3P2,RHF4P2
C    3,PFEPO1,AFE1,AFEO1,AFEO2,AFEO3,AFEO4
C    2,AH0P1,AH1P1,AH2P1,AHY1,AOH1,SP,SPX,AFE1*AH0P1,CFE1,COH1 
C     ENDIF
      ENDIF 
C
C     DICALCIUM PHOSPHATE
C
      PX=AMAX1(AH1P1,AH2P1)
      R1=AHY1
      P1=ACA1
      IF(PX.EQ.AH1P1)THEN
      P2=AH1P1
      NR1=0
      SP=SPCAD 
      ELSEIF(PX.EQ.AH2P1)THEN
      P2=AH2P1
      NR1=1
      SP=SHCAD2 
      ENDIF
      RPCAD1=0.0
      RHCAD2=0.0
      SPX=SP*R1**NR1 
      S0=P1+P2
      S1=AMAX1(0.0,S0**2-4.0*(P1*P2-SPX))
      RPCADX=AMAX1(-PCAPD1,-FCHY*CHY1,TPD*0.5*(S0-SQRT(S1)))
      IF(PX.EQ.AH1P1)THEN
      RPCAD1=RPCADX
      ELSEIF(PX.EQ.AH2P1)THEN
      RHCAD2=RPCADX
      ENDIF
C     IF((M/10)*10.EQ.M)THEN
C     WRITE(*,1112)'CAPO4',I,L,K,M,PCAPM1,PCAPD1,CCA1
C    2,CH1P1,CH2P1,CHY1,COH1,RPCADX,RPCAD1,RHCAD2,R1,P1,P2,P3
C    3,SP,Z,FX,Y,X,TX,A2,CCA1*A2S*CH1P1*A2S,SPCAD
C     ENDIF
C
C     HYDROXYAPATITE
C
      PX=AMAX1(AH1P1,AH2P1)
      R1=AHY1
      P1=ACA1
      IF(PX.EQ.AH1P1)THEN
      P2=AH1P1
      NR1=4
      SP=SHCAH1 
      ELSEIF(PX.EQ.AH2P1)THEN
      P2=AH2P1
      NR1=7
      SP=SHCAH2 
      ENDIF
      RHCAH1=0.0
      RHCAH2=0.0
      SPX=(SP*R1**NR1/P1**5)**0.333
      RPCAHX=AMAX1(-PCAPH1,-FCHY*CHY1,TPD*(P2-SPX))
      IF(PX.EQ.AH1P1)THEN
      RHCAH1=RPCAHX
      ELSEIF(PX.EQ.AH2P1)THEN
      RHCAH2=RPCAHX
      ENDIF
      PALOH1=PALOH1+RPALOX
      PFEOH1=PFEOH1+RPFEOX
      PCACO1=PCACO1+RPCACX
      PCASO1=PCASO1+RPCASO
      PALPO1=PALPO1+RPALPX
      PFEPO1=PFEPO1+RPFEPX
      PCAPD1=PCAPD1+RPCADX
      PCAPH1=PCAPH1+RPCAHX
C
C     ANION EXCHANGE EQILIBRIA
C
C     XAEC=anion exchange capacity (mol)
C     RXOH2,RXOH1=OH2,OH exchange
C     RXH2P,RYH2P=H2PO4,HPO4 exchange
C     XH2P,XH1P=exchangeable H2PO4,HPO4
C     XOH2,XOH1=exchangeable OH2,OH
C     SP*=solubility product from PARAMETER above 
C     TADA=adsorption rate constant (t-1)
C
      IF(XAEC(L,NY,NX).GT.ZEROS(NY,NX))THEN
      RXOH2=AMIN1(FCHY*CHY1,TADA*(XOH11*AHY1-SXOH2*XOH21)
     2/(AHY1+SXOH2)) 
      RXOH1=AMIN1(FCHY*CHY1,TADA*(XOH01*AHY1-SXOH1*XOH11)
     2/(AHY1+SXOH1))
      SPH2P=SXH2P*DPH2O 
      RXH2P=TADA*(XOH21*AH2P1-SPH2P*XH2P1)
     2/(AH2P1+SPH2P)
      SYH2P=SXH2P*AOH1
      RYH2P=AMAX1(-FCOH*COH1,TADA*(XOH11*AH2P1-SYH2P*XH2P1)
     2/(AH2P1+SYH2P)) 
C
C     HPO4 EXCHANGE
C
      SPH1P=SXH1P*DPH2O/DPH2P
      RXH1P=AMAX1(-FCOH*COH1,TADA*(XOH11*AH1P1-SPH1P*XH1P1)
     2/(AH1P1+SPH1P))
      XOH01=XOH01-RXOH1
      XOH11=XOH11+RXOH1-RXOH2-RYH2P-RXH1P 
      XOH21=XOH21+RXOH2-RXH2P
      XH1P1=XH1P1+RXH1P 
      XH2P1=XH2P1+RXH2P+RYH2P 
      ELSE
      RXOH2=0.0
      RXOH1=0.0
      RXH2P=0.0
      RYH2P=0.0
      RXH1P=0.0
      ENDIF
C     IF((M.EQ.1.OR.(M/100)*100.EQ.M).AND.L.EQ.1)THEN 
C     WRITE(*,1112)'RXH2PE',I,L,K,M 
C    3,RXH1P,RXH2P,RYH2P,RXOH2,RXOH1
C    3,AH1P1,AH2P1,CH1P1,CH2P1,A1S,A2S
C    3,RXH1P+RXH2P+RYH2P+RXOH2+RXOH1
C    2,XH1P1,XH2P1,XOH01,XOH11,XOH21
C    3,XH1P1+XH2P1+XOH01+XOH11+XOH21
C    4,XAEC(L,NY,NX),BKVLX
C     ENDIF
C
C     CATION EXCHANGE FROM GAPON SELECTIVITY CO-EFFICIENTS
C
C     XCEC=cation exchange capacity from soil file (mol)
C     GKC4,GKCH,GKCA,GKCM,GKCN,GKCK=Gapon selectivity coefficients for
C        Ca-NH4,Ca-H,Ca-Al,Ca-Mg,Ca-Na,Ca-K from soil file
C     A*1=ion activity
C     X*Q=exchangeable ion concentration at equilibrium (mol Mg-1) 
C     X*1=exchangeable ion concentration (mol Mg-1) 
C     RX*=cation exchange
C     TADC=adsorption rate constant
C
      IF(M.EQ.1)THEN
      IF(XCEC(L,NY,NX).GT.ZEROS(NY,NX))THEN
      AALX=AMAX1(0.0,AAL1)**0.333
      AFEX=AMAX1(0.0,AFE1)**0.333
      ACAX=AMAX1(0.0,ACA1)**0.500
      AMGX=AMAX1(0.0,AMG1)**0.500
      XCAX=CCEC/(1.0+GKC4(L,NY,NX)*AN41/ACAX
     3+GKCH(L,NY,NX)*AHY1/ACAX+GKCA(L,NY,NX)*AALX/ACAX
     4+GKCA(L,NY,NX)*AFEX/ACAX+GKCM(L,NY,NX)*AMGX/ACAX
     5+GKCN(L,NY,NX)*ANA1/ACAX+GKCK(L,NY,NX)*AKA1/ACAX)
      XN4Q=XCAX*AN41*GKC4(L,NY,NX)
      XHYQ=XCAX*AHY1*GKCH(L,NY,NX) 
      XALQ=XCAX*AALX*GKCA(L,NY,NX) 
      XFEQ=XCAX*AFEX*GKCA(L,NY,NX) 
      XCAQ=XCAX*ACAX
      XMGQ=XCAX*AMGX*GKCM(L,NY,NX) 
      XNAQ=XCAX*ANA1*GKCN(L,NY,NX) 
      XKAQ=XCAX*AKA1*GKCK(L,NY,NX) 
      XTLQ=XN4Q+XALQ+XFEQ+XCAQ+XMGQ+XHYQ+XNAQ+XKAQ 
      IF(XTLQ.GT.ZERO)THEN
      FX=CCEC/XTLQ
      ELSE
      FX=0.0
      ENDIF
      XN4Q=FX*XN4Q
      XHYQ=FX*XHYQ
      XALQ=FX*XALQ
      XFEQ=FX*XFEQ
      XCAQ=FX*XCAQ
      XMGQ=FX*XMGQ
      XNAQ=FX*XNAQ
      XKAQ=FX*XKAQ
      XN41=XN4Q
      XHY1=XHYQ
      XAL1=XALQ
      XFE1=XFEQ
      XCA1=XCAQ
      XMG1=XMGQ
      XNA1=XNAQ
      XKA1=XKAQ
C     IF(L.EQ.1)THEN 
C     WRITE(*,1112)'RXCA',I,K,L,M 
C    2,XN4Q,XHYQ,XALQ,XFEQ,XCAQ,XMGQ,XNAQ,XKAQ
C    2,XN41,XHY1,XAL1,XFE1,XCA1,XMG1,XNA1,XKA1
C    2,AN41,AHY1,AAL1,AFE1,ACA1,AMG1,ANA1,AKA1
C    2,XN41+XHY1+XAL1*3.0+XFE1*3.0+XCA1*2.0+XMG1*2.0+XNA1+XKA1
C    2,CCEC,XCAX,XTLQ,FX,TXXX,TXXY
C     ENDIF
      ELSE
      XN41=0.0
      XHY1=0.0
      XAL1=0.0
      XFE1=0.0
      XCA1=0.0
      XMG1=0.0
      XNA1=0.0
      XKA1=0.0
      ENDIF
      ENDIF
      ELSE
      RHAL1=0.0
      RHALO1=0.0
      RHALO2=0.0
      RHALO3=0.0
      RHALO4=0.0
      RHFE1=0.0
      RHFEO1=0.0
      RHFEO2=0.0
      RHFEO3=0.0
      RHFEO4=0.0
      RHCAC3=0.0
      RHCACH=0.0
      RHCACO=0.0
      RPCACX=0.0
      RPCASO=0.0
      RPCADX=0.0
      RPCAHX=0.0
      RHA0P1=0.0
      RHA1P1=0.0
      RHA2P1=0.0
      RHA3P1=0.0
      RHA4P1=0.0
      RHA0P2=0.0
      RHA1P2=0.0
      RHA2P2=0.0
      RHA3P2=0.0
      RHA4P2=0.0
      RHF0P1=0.0
      RHF1P1=0.0
      RHF2P1=0.0
      RHF3P1=0.0
      RHF4P1=0.0
      RHF0P2=0.0
      RHF1P2=0.0
      RHF2P2=0.0
      RHF3P2=0.0
      RHF4P2=0.0
      RPCAD1=0.0
      RHCAD2=0.0
      RHCAH1=0.0
      RHCAH2=0.0
      RXOH2=0.0
      RXOH1=0.0
      RXH2P=0.0
      RYH2P=0.0
      RXH1P=0.0
      XN41=0.0
      XHY1=0.0
      XAL1=0.0
      XFE1=0.0
      XCA1=0.0
      XMG1=0.0
      XNA1=0.0
      XKA1=0.0
      ENDIF
C
C     DISSOCIATION OF CARBOXYL RADICALS
C
      IF(K.EQ.3)THEN
      XCOO=AMAX1(ZEROC,XCOOH-XHC1)
      RXHC=TADC*(AHY1*XCOO-DPCOH*XHC1)/(DPCOH+AHY1)
      XHC1=XHC1+RXHC
C     WRITE(*,1112)'XHC1',I,L,K,M,XHC1
C    2,RXHC,TAD,AHY1,XCOO,DPCOH,XHC1,XCOOH 
C    3,COOH,ORGC(0,NY,NX),BKVL(0,NY,NX)
      ENDIF
C
C     ION SPECIATION FROM ION DISSOCIATION CONSTANTS
C
C     R*=ion dissociation
C     A*=ion activity
C     DP*=dissociation products from PARAMETER above
C     TSL=dissociation rate constant
C
      RNH4=TSL*(AHY1*AN31-DPN4*AN41)
     2/(AMAX1(AHY1,AN31)+AMAX1(DPN4,AN41))
      RALO1=AMIN1(FCOH*COH1,TSL*(AAL1*AOH1-DPAL1*AALO1)
     2/(AMAX1(AAL1,AOH1)+AMAX1(DPAL1,AALO1)))
      RALO2=AMIN1(FCOH*COH1,TSL*(AALO1*AOH1-DPAL2*AALO2)
     2/(AMAX1(AALO1,AOH1)+AMAX1(DPAL2,AALO2)))
      RALO3=AMIN1(FCOH*COH1,TSL*(AALO2*AOH1-DPAL3*AALO3)
     2/(AMAX1(AALO2,AOH1)+AMAX1(DPAL3,AALO3)))
      RALO4=AMIN1(FCOH*COH1,TSL*(AALO3*AOH1-DPAL4*AALO4)
     2/(AMAX1(AALO3,AOH1)+AMAX1(DPAL4,AALO4)))
      RALS=TSL*(AAL1*ASO41-DPALS*AALS1)
     2/(AMAX1(AAL1,ASO41)+AMAX1(DPALS,AALS1))
      RFEO1=AMIN1(FCOH*COH1,TSL*(AFE1*AOH1-DPFE1*AFEO1)
     2/(AMAX1(AFE1,AOH1)+AMAX1(DPFE1,AFEO1)))
      RFEO2=AMIN1(FCOH*COH1,TSL*(AFEO1*AOH1-DPFE2*AFEO2)
     2/(AMAX1(AFEO1,AOH1)+AMAX1(DPFE2,AFEO2)))
      RFEO3=AMIN1(FCOH*COH1,TSL*(AFEO2*AOH1-DPFE3*AFEO3)
     2/(AMAX1(AFEO2,AOH1)+AMAX1(DPFE3,AFEO3)))
      RFEO4=AMIN1(FCOH*COH1,TSL*(AFEO3*AOH1-DPFE4*AFEO4)
     2/(AMAX1(AFEO3,AOH1)+AMAX1(DPFE4,AFEO4)))
      RFES=TSL*(AFE1*ASO41-DPFES*AFES1) 
     2/(AMAX1(AFE1,ASO41)+AMAX1(DPFES,AFES1)) 
      RCAO=TSL*(ACA1*AOH1-DPCAO*ACAO1)
     2/(AMAX1(ACA1,AOH1)+AMAX1(DPCAO,ACAO1))
      RCAC=TSL*(ACA1*ACO31-DPCAC*ACAC1)
     2/(AMAX1(ACA1,ACO31)+AMAX1(DPCAC,ACAC1))
      RCAH=TSL*(ACA1*AHCO31-DPCAH*ACAH1)
     2/(AMAX1(ACA1,AHCO31)+AMAX1(DPCAH,ACAH1))
      RCAS=TSL*(ACA1*ASO41-DPCAS*ACAS1)
     2/(AMAX1(ACA1,ASO41)+AMAX1(DPCAS,ACAS1))
      RMGO=TSL*(AMG1*AOH1-DPMGO*AMGO1)
     2/(AMAX1(AMG1,AOH1)+AMAX1(DPMGO,AMGO1))
      RMGC=TSL*(AMG1*ACO31-DPMGC*AMGC1)
     2/(AMAX1(AMG1,ACO31)+AMAX1(DPMGC,AMGC1))
      RMGH=TSL*(AMG1*AHCO31-DPMGH*AMGH1)
     2/(AMAX1(AMG1,AHCO31)+AMAX1(DPMGH,AMGH1))
      RMGS=TSL*(AMG1*ASO41-DPMGS*AMGS1)
     2/(AMAX1(AMG1,ASO41)+AMAX1(DPMGS,AMGS1))
      RNAC=TSL*(ANA1*ACO31-DPNAC*ANAC1)
     2/(AMAX1(ANA1,ACO31)+AMAX1(DPNAC,ANAC1))
      RNAS=TSL*(ANA1*ASO41-DPNAS*ANAS1)
     2/(AMAX1(ANA1,ASO41)+AMAX1(DPNAS,ANAS1))
      RKAS=TSL*(AKA1*ASO41-DPKAS*AKAS1)
     2/(AMAX1(AKA1,ASO41)+AMAX1(DPKAS,AKAS1))
      RH1P=TSL*(AH0P1*AHY1-DPH1P*AH1P1)
     2/(AMAX1(AH0P1,AHY1)+AMAX1(DPH1P,AH1P1))
      RH2P=TSL*(AH1P1*AHY1-DPH2P*AH2P1)
     2/(AMAX1(AH1P1,AHY1)+AMAX1(DPH2P,AH2P1))
      RH3P=TSL*(AH2P1*AHY1-DPH3P*AH3P1)
     2/(AMAX1(AH2P1,AHY1)+AMAX1(DPH3P,AH3P1))
      RF1P=TSL*(AFE1*AH1P1-DPF1P*AF1P1)
     2/(AMAX1(AFE1,AH1P1)+AMAX1(DPF1P,AF1P1))
      RF2P=TSL*(AFE1*AH2P1-DPF2P*AF2P1)
     2/(AMAX1(AFE1,AH2P1)+AMAX1(DPF2P,AF2P1))
      RC0P=TSL*(ACA1*AH0P1-DPC0P*AC0P1)
     2/(AMAX1(ACA1,AH0P1)+AMAX1(DPC0P,AC0P1))
      RC1P=TSL*(ACA1*AH1P1-DPC1P*AC1P1)
     2/(AMAX1(ACA1,AH1P1)+AMAX1(DPC1P,AC1P1))
      RC2P=TSL*(ACA1*AH2P1-DPC2P*AC2P1)
     2/(AMAX1(ACA1,AH2P1)+AMAX1(DPC2P,AC2P1))
      RM1P=TSL*(AMG1*AH1P1-DPM1P*AM1P1)
     2/(AMAX1(AMG1,AH1P1)+AMAX1(DPM1P,AM1P1))
C
C     TOTAL ION FLUX FOR EACH ION SPECIES
C     FROM PRECIPITATION-DISSOLUTION, EXCGANGE AND SOLUTION REACTIONS
C
      RN4S=RNH4 
      RN3S=-RNH4
      RAL=-RHAL1-RHA0P1-RHA0P2-RALO1-RALS
      RFE=-RHFE1-RHF0P1-RHF0P2-RFEO1-RFES
     2-RF1P-RF2P
      RCA=-RPCACX-RPCASO-RPCADX-5.0*RPCAHX
     2-RCAO-RCAC-RCAH-RCAS-RC0P-RC1P-RC2P
      RMG=-RMGO-RMGC-RMGH-RMGS-RM1P
      RNA=-RNAC-RNAS
      RKA=-RKAS
      RSO4=-RPCASO-RALS-RFES-RCAS-RMGS-RNAS-RKAS
      RAL1=-RHALO1-RHA1P1-RHA1P2+RALO1-RALO2
      RAL2=-RHALO2-RHA2P1-RHA2P2+RALO2-RALO3
      RAL3=-RHALO3-RHA3P1-RHA3P2+RALO3-RALO4
      RAL4=-RHALO4-RHA4P1-RHA4P2+RALO4
      RFE1=-RHFEO1-RHF1P1-RHF1P2+RFEO1-RFEO2
      RFE2=-RHFEO2-RHF2P1-RHF2P2+RFEO2-RFEO3
      RFE3=-RHFEO3-RHF3P1-RHF3P2+RFEO3-RFEO4
      RFE4=-RHFEO4-RHF4P1-RHF4P2+RFEO4
      RHP0=-RH1P-RC0P
      RHP1=-RHA0P1-RHA1P1-RHA2P1-RHA3P1
     2-RHA4P1-RHF0P1-RHF1P1-RHF2P1 
     3-RHF3P1-RHF4P1-RPCAD1-3.0*RHCAH1 
     4-RXH1P+RH1P-RH2P-RF1P-RC1P-RM1P
      RHP2=-RHA0P2-RHA1P2-RHA2P2-RHA3P2
     2-RHA4P2-RHF0P2-RHF1P2-RHF2P2 
     3-RHF3P2-RHF4P2-RHCAD2-3.0*RHCAH2
     4-RXH2P-RYH2P+RH2P-RH3P-RF2P-RC2P
      RHP3=RH3P
C
C     RECALCULATE ION CONCENTRATIONS FROM TOTAL ION FLUXES
C
      CN41=CN41+RN4S 
      CN31=CN31+RN3S
      CAL1=CAL1+RAL
      CFE1=CFE1+RFE
      CCA1=CCA1+RCA
      CMG1=CMG1+RMG
      CNA1=CNA1+RNA
      CKA1=CKA1+RKA
      CSO41=CSO41+RSO4
      CALO1=CALO1+RAL1
      CALO2=CALO2+RAL2 
      CALO3=CALO3+RAL3
      CALO4=CALO4+RAL4
      CALS1=CALS1+RALS
      CFEO1=CFEO1+RFE1
      CFEO2=CFEO2+RFE2 
      CFEO3=CFEO3+RFE3
      CFEO4=CFEO4+RFE4
      CFES1=CFES1+RFES
      CCAO1=CCAO1+RCAO
      CCAC1=CCAC1+RCAC
      CCAH1=CCAH1+RCAH
      CCAS1=CCAS1+RCAS
      CMGO1=CMGO1+RMGO
      CMGC1=CMGC1+RMGC
      CMGH1=CMGH1+RMGH
      CMGS1=CMGS1+RMGS
      CNAC1=CNAC1+RNAC
      CNAS1=CNAS1+RNAS
      CKAS1=CKAS1+RKAS
      CH0P1=CH0P1+RHP0
      CH1P1=CH1P1+RHP1
      CH2P1=CH2P1+RHP2
      CH3P1=CH3P1+RHP3
      CF1P1=CF1P1+RF1P
      CF2P1=CF2P1+RF2P
      CC0P1=CC0P1+RC0P
      CC1P1=CC1P1+RC1P
      CC2P1=CC2P1+RC2P
      CM1P1=CM1P1+RM1P
C     IF(K.EQ.3.AND.(M.LE.10.OR.INT(M/100)*100.EQ.M).AND.L.EQ.1)THEN
C     IF(K.EQ.3)THEN
C     WRITE(*,1112)'ALL',I,L,K,M 
C    2,CHY1,CSTRQ,CC3,CA3,CC2,CA2,CC1,CA1,VOLW(L,NY,NX)
C    3,CSO41,CCO31,CH1P1,CNO1,COH1,CHCO31,CCL1
C    4,CALO4,CFEO4,CNAC1,CNAS1,CKAS1,CH2P1,CC0P1
C    5,RHP2,RHA0P2,RHA1P2,RHA2P2,RHA3P2
C    2,RHA4P2,RHF0P2,RHF1P2,RHF2P2 
C    3,RHF3P2,RHF4P2,RHCAD2,3.0*RHCAH2
C    4,RXH2P,RYH2P,RH2P,RH3P,RF2P,RC2P
C    5,RHP1,RHA0P1,RHA1P1,RHA2P1,RHA3P1
C    2,RHA4P1,RHF0P1,RHF1P1,RHF2P1 
C    3,RHF3P1,RHF4P1,RPCAD1,3.0*RHCAH1 
C    4,RXH1P,RH1P,RH2P,RF1P,RC1P,RM1P
C     WRITE(*,1112)'ALPO4I',I,L,K,M,PALPO1,CAL1,AAL1,AALX,XAL1,XALQ
C    5,RAL,RHAL1,RHA0P1,RHA0P2,RALO1,RALS 
C    2,AALO1,AALO2,AALO3,AALO4,XCOO
C    2,AH0P1,AH1P1,AH2P1,AHY1,AOH1,RPALPX,RHA0P1,RHA1P1,RHA2P1,RHA3P1 
C    3,RHA4P1,RHA0P2,RHA1P2,RHA2P2,RHA3P2,RHA4P2,SP,SPX,AAL1*AH0P1 
C    4,SPALP,CH0P1,CH1P1,CH2P1,CH3P1,RHP0,RHP1,RHP2,RHP3
C     WRITE(*,1112)'FEPO4I',I,L,K,M,PFEPO1,CFE1,AFE1,AFEX,XFE1,XFEQ
C    2,RFE,RHFE1,RHF0P1,RHF0P2,RFEO1,RFES,RF1P,RF2P
C    2,AFEO1,AFEO2,AFEO3,AFEO4 
C     WRITE(*,1112)'APATITE',I,L,K,M,PCAPH1,ACA1,CCA1,XCA1
C    2,RCA,RPCACX,RPCASO,RPCADX,5.0*RPCAHX
C    2,RCAO,RCAC,RCAH,RCAS,RC0P,RC1P,RC2P,VOLW(L,NY,NX)
C    3,SPCAC,CCO31,CHCO31,CCO21,CCO2M 
C    2,CSO41,CCAS1,RSO4,RPCASO,RALS,RFES,RCAS,RMGS,RNAS,RKAS 
C    2,AH0P1,AH1P1,AH2P1,AHY1,AOH1,RPCAHX,RHCAH1,RHCAH2 
C    3,SP,SPX,ACA1**5*AH0P1**3*AOH1,SPCAH,SHCAH1,SHCAH2
C    3,CH0P1,CH1P1,CH2P1,XOH01,XOH11,XOH21,XH1P1,XH2P1
C    4,RHA0P1,RHA1P1,RHA2P1,RHA3P1
C    2,RHA4P1,RHF0P1,RHF1P1,RHF2P1 
C    3,RHF3P1,RHF4P1,RPCAD1,3.0*RHCAH1 
C    4,RXH1P,RH1P,RH2P,RF1P,RC1P,RM1P
C    5,RHA0P2,RHA1P2,RHA2P2,RHA3P2
C    2,RHA4P2,RHF0P2,RHF1P2,RHF2P2 
C    3,RHF3P2,RHF4P2,RHCAD2,3.0*RHCAH2
C    4,RXH2P,RYH2P,RH2P,RH3P,RF2P,RC2P,RH3P 
C     ENDIF
1000  CONTINUE
C
C     RECALCULATE SOLUTE CONCENTRATIONS IN PRECIPITATION
C     FROM TOTAL ION FLUXES IN RAINWATER
C
C     C*R=solute concentrations in precipitation (mol m-3)
C
      IF(K.EQ.1.AND.I.EQ.1.AND.L.EQ.1)THEN
      CCOR(NY,NX)=CCO21
      CCHR(NY,NX)=CCH41
      COXR(NY,NX)=COXY1
      CNNR(NY,NX)=CZ2G1
      CN2R(NY,NX)=CZ2O1
      CN4R(NY,NX)=CN41
      CN3R(NY,NX)=CN31
      CALR(NY,NX)=CAL1
      CFER(NY,NX)=CFE1
      CHYR(NY,NX)=CHY1
      CCAR(NY,NX)=CCA1
      CMGR(NY,NX)=CMG1
      CNAR(NY,NX)=CNA1
      CKAR(NY,NX)=CKA1
      COHR(NY,NX)=COH1
      CSOR(NY,NX)=CSO41
      CCLR(NY,NX)=CCL1
      CC3R(NY,NX)=CCO31
      CHCR(NY,NX)=CHCO31
      CAL1R(NY,NX)=CALO1
      CAL2R(NY,NX)=CALO2
      CAL3R(NY,NX)=CALO3
      CAL4R(NY,NX)=CALO4
      CALSR(NY,NX)=CALS1
      CFE1R(NY,NX)=CFEO1
      CFE2R(NY,NX)=CFEO2
      CFE3R(NY,NX)=CFEO3
      CFE4R(NY,NX)=CFEO4
      CFESR(NY,NX)=CFES1
      CCAOR(NY,NX)=CCAO1
      CCACR(NY,NX)=CCAC1
      CCAHR(NY,NX)=CCAH1
      CCASR(NY,NX)=CCAS1
      CMGOR(NY,NX)=CMGO1
      CMGCR(NY,NX)=CMGC1
      CMGHR(NY,NX)=CMGH1
      CMGSR(NY,NX)=CMGS1
      CNACR(NY,NX)=CNAC1
      CNASR(NY,NX)=CNAS1
      CKASR(NY,NX)=CKAS1
      CH0PR(NY,NX)=CH0P1
      CH1PR(NY,NX)=CH1P1
      CPOR(NY,NX)=CH2P1
      CH3PR(NY,NX)=CH3P1
      CF1PR(NY,NX)=CF1P1
      CF2PR(NY,NX)=CF2P1
      CC0PR(NY,NX)=CC0P1
      CC1PR(NY,NX)=CC1P1
      CC2PR(NY,NX)=CC2P1
      CM1PR(NY,NX)=CM1P1
C
C     RECALCULATE SOLUTE CONCENTRATIONS IN IRRIGATION
C     FROM TOTAL ION FLUXES IN IRRIGATION WATER
C
C     C*Q=solute concentrations in irrigation (mol m-3)
C
      ELSEIF(K.EQ.2.AND.L.EQ.1)THEN
      CCOQ(NY,NX)=CCO21
      CCHQ(NY,NX)=CCH41
      COXQ(NY,NX)=COXY1
      CNNQ(NY,NX)=CZ2G1
      CN2Q(NY,NX)=CZ2O1
      CN4Q(I,NY,NX)=CN41
      CN3Q(I,NY,NX)=CN31
      CALQ(I,NY,NX)=CAL1
      CFEQ(I,NY,NX)=CFE1
      CHYQ(I,NY,NX)=CHY1
      CCAQ(I,NY,NX)=CCA1
      CMGQ(I,NY,NX)=CMG1
      CNAQ(I,NY,NX)=CNA1
      CKAQ(I,NY,NX)=CKA1
      COHQ(I,NY,NX)=COH1
      CSOQ(I,NY,NX)=CSO41
      CCLQ(I,NY,NX)=CCL1
      CC3Q(I,NY,NX)=CCO31
      CHCQ(I,NY,NX)=CHCO31
      CAL1Q(I,NY,NX)=CALO1
      CAL2Q(I,NY,NX)=CALO2
      CAL3Q(I,NY,NX)=CALO3
      CAL4Q(I,NY,NX)=CALO4
      CALSQ(I,NY,NX)=CALS1
      CFE1Q(I,NY,NX)=CFEO1
      CFE2Q(I,NY,NX)=CFEO2
      CFE3Q(I,NY,NX)=CFEO3
      CFE4Q(I,NY,NX)=CFEO4
      CFESQ(I,NY,NX)=CFES1
      CCAOQ(I,NY,NX)=CCAO1
      CCACQ(I,NY,NX)=CCAC1
      CCAHQ(I,NY,NX)=CCAH1
      CCASQ(I,NY,NX)=CCAS1
      CMGOQ(I,NY,NX)=CMGO1
      CMGCQ(I,NY,NX)=CMGC1
      CMGHQ(I,NY,NX)=CMGH1
      CMGSQ(I,NY,NX)=CMGS1
      CNACQ(I,NY,NX)=CNAC1
      CNASQ(I,NY,NX)=CNAS1
      CKASQ(I,NY,NX)=CKAS1
      CH0PQ(I,NY,NX)=CH0P1
      CH1PQ(I,NY,NX)=CH1P1
      CPOQ(I,NY,NX)=CH2P1
      CH3PQ(I,NY,NX)=CH3P1
      CF1PQ(I,NY,NX)=CF1P1
      CF2PQ(I,NY,NX)=CF2P1
      CC0PQ(I,NY,NX)=CC0P1
      CC1PQ(I,NY,NX)=CC1P1
      CC2PQ(I,NY,NX)=CC2P1
      CM1PQ(I,NY,NX)=CM1P1
C
C     RECALCULATE SOLUTE CONCENTRATIONS IN SOIL
C     FROM TOTAL ION FLUXES IN SOIL WATER
C
C     C*U=solute concentrations in soil water (g or mol m-3)
C
      ELSEIF(K.EQ.3.AND.I.EQ.1)THEN
      CCOU=CCO21
      CCHU=CCH41
      COXU=0.0
      CNNU=CZ2G1
      CN2U=CZ2O1
      CN4U(L,NY,NX)=CN41*14.0
      CN3U(L,NY,NX)=CN31*14.0
      CNOU(L,NY,NX)=CNOX*14.0
      CALU(L,NY,NX)=CAL1
      CFEU(L,NY,NX)=CFE1
      CHYU(L,NY,NX)=CHY1
      CCAU(L,NY,NX)=CCA1
      CMGU(L,NY,NX)=CMG1
      CNAU(L,NY,NX)=CNA1
      CKAU(L,NY,NX)=CKA1
      COHU(L,NY,NX)=COH1
      CSOU(L,NY,NX)=CSO41
      CCLU(L,NY,NX)=CCL1
      CC3U(L,NY,NX)=CCO31
      CHCU(L,NY,NX)=CHCO31
      CAL1U(L,NY,NX)=CALO1
      CAL2U(L,NY,NX)=CALO2
      CAL3U(L,NY,NX)=CALO3
      CAL4U(L,NY,NX)=CALO4
      CALSU(L,NY,NX)=CALS1
      CFE1U(L,NY,NX)=CFEO1
      CFE2U(L,NY,NX)=CFEO2
      CFE3U(L,NY,NX)=CFEO3
      CFE4U(L,NY,NX)=CFEO4
      CFESU(L,NY,NX)=CFES1
      CCAOU(L,NY,NX)=CCAO1
      CCACU(L,NY,NX)=CCAC1
      CCAHU(L,NY,NX)=CCAH1
      CCASU(L,NY,NX)=CCAS1
      CMGOU(L,NY,NX)=CMGO1
      CMGCU(L,NY,NX)=CMGC1
      CMGHU(L,NY,NX)=CMGH1
      CMGSU(L,NY,NX)=CMGS1
      CNACU(L,NY,NX)=CNAC1
      CNASU(L,NY,NX)=CNAS1
      CKASU(L,NY,NX)=CKAS1
      CH0PU(L,NY,NX)=CH0P1
      CH1PU(L,NY,NX)=CH1P1
      CH2PU(L,NY,NX)=CH2P1*31.0
      CH3PU(L,NY,NX)=CH3P1*31.0
      CF1PU(L,NY,NX)=CF1P1
      CF2PU(L,NY,NX)=CF2P1
      CC0PU(L,NY,NX)=CC0P1
      CC1PU(L,NY,NX)=CC1P1
      CC2PU(L,NY,NX)=CC2P1
      CM1PU(L,NY,NX)=CM1P1
C
C     INITIALIZE STATE VARIABLES FOR GAS IN SOIL 
C     AQUEOUS (*S) AND GASEOUS (*G) PHASES
C
C     C*G=soil gaseous gas content (g)
C     C*S=soil aqueous gas content (g)
C     C*E=atmospheric gas concentration (g m-2)
C     VOLP,VOLW=soil air,water content (m3)
C     S*X=gas solubility (g m-3 / (g m-3))
C
      IF(DATA(20).EQ.'NO'.AND.IGO.EQ.0)THEN
      CO2G(L,NY,NX)=CCO2EI(NY,NX)*VOLP(L,NY,NX)
      CH4G(L,NY,NX)=CCH4E(NY,NX)*VOLP(L,NY,NX)
      OXYG(L,NY,NX)=COXYE(NY,NX)*VOLP(L,NY,NX)
      Z2GG(L,NY,NX)=CZ2GE(NY,NX)*VOLP(L,NY,NX)
      Z2OG(L,NY,NX)=CZ2OE(NY,NX)*VOLP(L,NY,NX)
      ZNH3G(L,NY,NX)=CNH3E(NY,NX)*VOLP(L,NY,NX)
      H2GG(L,NY,NX)=CH2GE(NY,NX)*VOLP(L,NY,NX)
      IF(CDPTH(L-1,NY,NX).LT.DTBLZ(NY,NX))THEN
      OXYS(L,NY,NX)=COXYE(NY,NX)*SOXYX/(EXP(AOXYX*CSTR1))
     2*EXP(0.516-0.0172*ATCA(NY,NX))*VOLW(L,NY,NX)
      ELSE
      OXYS(L,NY,NX)=0.0
      ENDIF
      CO2S(L,NY,NX)=CCO2EI(NY,NX)*SCO2X/(EXP(ACO2X*CSTR1))
     2*EXP(0.843-0.0281*ATCA(NY,NX))*VOLW(L,NY,NX)
      CH4S(L,NY,NX)=CCH4E(NY,NX)*SCH4X/(EXP(ACH4X*CSTR1))
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(L,NY,NX)
      Z2GS(L,NY,NX)=CZ2GE(NY,NX)*SN2GX/(EXP(AN2GX*CSTR1))
     2*EXP(0.456-0.0152*ATCA(NY,NX))*VOLW(L,NY,NX)
      Z2OS(L,NY,NX)=CZ2OE(NY,NX)*SN2OX/(EXP(AN2OX*CSTR1))
     2*EXP(0.897-0.0299*ATCA(NY,NX))*VOLW(L,NY,NX)
      H2GS(L,NY,NX)=CH2GE(NY,NX)*SH2GX/(EXP(AH2GX*CSTR1))
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(L,NY,NX)
C
C     INITIAL STATE VARIABLES FOR MINERAL N AND P IN SOIL
C     IN NON-BAND ABND BAND ZONES
C
C     VLNH4,VLNHB=fractions of soil volume in NH4 non-band,band
C     VLNO3,VLNOB=fractions of soil volume in NO3 non-band,band
C     VLPO4,VLPOB=fractions of soil volume in H2PO4 non-band,band
C     ZNH4,ZNH3,ZNO3,ZNO2,H2PO4,H1PO=NH4,NH3,NO3,NO2,H2PO4,HPO4
C
      ZNH4S(L,NY,NX)=CN4U(L,NY,NX)*VOLW(L,NY,NX)*VLNH4(L,NY,NX)
      ZNH4B(L,NY,NX)=CN4U(L,NY,NX)*VOLW(L,NY,NX)*VLNHB(L,NY,NX)
      ZNH3S(L,NY,NX)=CN3U(L,NY,NX)*VOLW(L,NY,NX)*VLNH4(L,NY,NX)
      ZNH3B(L,NY,NX)=CN3U(L,NY,NX)*VOLW(L,NY,NX)*VLNHB(L,NY,NX)
      ZNO3S(L,NY,NX)=CNOU(L,NY,NX)*VOLW(L,NY,NX)*VLNO3(L,NY,NX)
      ZNO3B(L,NY,NX)=CNOU(L,NY,NX)*VOLW(L,NY,NX)*VLNOB(L,NY,NX)
      ZNO2S(L,NY,NX)=0.0
      ZNO2B(L,NY,NX)=0.0
      H2PO4(L,NY,NX)=CH2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      H2POB(L,NY,NX)=CH2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      H1PO4(L,NY,NX)=CH1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      H1POB(L,NY,NX)=CH1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
C     WRITE(*,444)'ZNH4S',NX,NY,L,ZNH4S(L,NY,NX),CN4U(L,NY,NX)
C    2,VOLW(L,NY,NX),VLNH4(L,NY,NX),H2PO4(L,NY,NX),CH2PU(L,NY,NX)
C    3,H1PO4(L,NY,NX),CH1PU(L,NY,NX),VLPO4(L,NY,NX)
C    4,XN41*BKVL(L,NY,NX)*VLNH4(L,NY,NX)
C    5,XN41,BKVL(L,NY,NX),VLNH4(L,NY,NX)
444   FORMAT(A8,3I4,20E12.4)
C
C     INITIAL STATE VARIABLES FOR CATIONS, ANIONS AND ION PAIRS 
C     IN SOIL WATER
C
C     Z*=ion content (mol)
C     C*U=solute concentrations in soil water (g or mol m-3)
C     VOLW=soil water content (m3)
C
      ZAL(L,NY,NX)=CALU(L,NY,NX)*VOLW(L,NY,NX)
      ZFE(L,NY,NX)=CFEU(L,NY,NX)*VOLW(L,NY,NX)
      ZHY(L,NY,NX)=CHYU(L,NY,NX)*VOLW(L,NY,NX)
      ZCA(L,NY,NX)=CCAU(L,NY,NX)*VOLW(L,NY,NX)
      ZMG(L,NY,NX)=CMGU(L,NY,NX)*VOLW(L,NY,NX)
      ZNA(L,NY,NX)=CNAU(L,NY,NX)*VOLW(L,NY,NX)
      ZKA(L,NY,NX)=CKAU(L,NY,NX)*VOLW(L,NY,NX)
      ZOH(L,NY,NX)=COHU(L,NY,NX)*VOLW(L,NY,NX)
      ZSO4(L,NY,NX)=CSOU(L,NY,NX)*VOLW(L,NY,NX)
      ZCL(L,NY,NX)=CCLU(L,NY,NX)*VOLW(L,NY,NX)
      ZCO3(L,NY,NX)=CC3U(L,NY,NX)*VOLW(L,NY,NX)
      ZHCO3(L,NY,NX)=CHCU(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH1(L,NY,NX)=CAL1U(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH2(L,NY,NX)=CAL2U(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH3(L,NY,NX)=CAL3U(L,NY,NX)*VOLW(L,NY,NX)
      ZALOH4(L,NY,NX)=CAL4U(L,NY,NX)*VOLW(L,NY,NX)
      ZALS(L,NY,NX)=CALSU(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH1(L,NY,NX)=CFE1U(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH2(L,NY,NX)=CFE2U(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH3(L,NY,NX)=CFE3U(L,NY,NX)*VOLW(L,NY,NX)
      ZFEOH4(L,NY,NX)=CFE4U(L,NY,NX)*VOLW(L,NY,NX)
      ZFES(L,NY,NX)=CFESU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAO(L,NY,NX)=CCAOU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAC(L,NY,NX)=CCACU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAH(L,NY,NX)=CCAHU(L,NY,NX)*VOLW(L,NY,NX)
      ZCAS(L,NY,NX)=CCASU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGO(L,NY,NX)=CMGOU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGC(L,NY,NX)=CMGCU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGH(L,NY,NX)=CMGHU(L,NY,NX)*VOLW(L,NY,NX)
      ZMGS(L,NY,NX)=CMGSU(L,NY,NX)*VOLW(L,NY,NX)
      ZNAC(L,NY,NX)=CNACU(L,NY,NX)*VOLW(L,NY,NX)
      ZNAS(L,NY,NX)=CNASU(L,NY,NX)*VOLW(L,NY,NX)
      ZKAS(L,NY,NX)=CKASU(L,NY,NX)*VOLW(L,NY,NX)
      H0PO4(L,NY,NX)=CH0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      H3PO4(L,NY,NX)=CH3PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZFE1P(L,NY,NX)=CF1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZFE2P(L,NY,NX)=CF2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZCA0P(L,NY,NX)=CC0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZCA1P(L,NY,NX)=CC1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZCA2P(L,NY,NX)=CC2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      ZMG1P(L,NY,NX)=CM1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPO4(L,NY,NX)
      H0POB(L,NY,NX)=CH0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      H3POB(L,NY,NX)=CH3PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZFE1PB(L,NY,NX)=CF1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZFE2PB(L,NY,NX)=CF2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZCA0PB(L,NY,NX)=CC0PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZCA1PB(L,NY,NX)=CC1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZCA2PB(L,NY,NX)=CC2PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZMG1PB(L,NY,NX)=CM1PU(L,NY,NX)*VOLW(L,NY,NX)*VLPOB(L,NY,NX)
      ZHYSI(L,NY,NX)=1.0E-03*VOLW(L,NY,NX)
C     IF(L.EQ.1)THEN
C     WRITE(*,1112)'ZHCO3',I,L,K,M
C    2,ZHCO3(L,NY,NX),CHCU(L,NY,NX),VOLW(L,NY,NX),ZHYSI(L,NY,NX)
C     WRITE(*,1112)'ZFE',I,L,K,M
C    2,ZFE(L,NY,NX),CFEU(L,NY,NX),VOLW(L,NY,NX),CFE1
C     WRITE(*,1112)'ZCA',I,L,K,M
C    2,ZCA(L,NY,NX),CCAU(L,NY,NX),CCA1,CCAX,CCAZ,CCA(L,NY,NX)
C    2,ZSO4(L,NY,NX),CSOU(L,NY,NX),CSO41,CSOX,CSOZ,CSO4(L,NY,NX)
C     ENDIF
C
C     INITIAL STATE VARIABLES FOR ALL MATERIAL IN SOIL MACROPORES
C
C     *H=soil macropore gas, solute content (g or mol m-3)
C
      CO2SH(L,NY,NX)=0.0
      CH4SH(L,NY,NX)=0.0
      OXYSH(L,NY,NX)=0.0
      Z2GSH(L,NY,NX)=0.0
      Z2OSH(L,NY,NX)=0.0
      H2GSH(L,NY,NX)=0.0
      ZNH4SH(L,NY,NX)=0.0
      ZNH4BH(L,NY,NX)=0.0
      ZNH3SH(L,NY,NX)=0.0
      ZNH3BH(L,NY,NX)=0.0
      ZNO3SH(L,NY,NX)=0.0
      ZNO3BH(L,NY,NX)=0.0
      ZNO2SH(L,NY,NX)=0.0
      ZNO2BH(L,NY,NX)=0.0
      H2PO4H(L,NY,NX)=0.0
      H2POBH(L,NY,NX)=0.0
      H1PO4H(L,NY,NX)=0.0
      H1POBH(L,NY,NX)=0.0
      ZALH(L,NY,NX)=0.0
      ZFEH(L,NY,NX)=0.0
      ZHYH(L,NY,NX)=0.0
      ZCCH(L,NY,NX)=0.0
      ZMAH(L,NY,NX)=0.0
      ZNAH(L,NY,NX)=0.0
      ZKAH(L,NY,NX)=0.0
      ZOHH(L,NY,NX)=0.0
      ZSO4H(L,NY,NX)=0.0
      ZCLH(L,NY,NX)=0.0
      ZCO3H(L,NY,NX)=0.0
      ZHCO3H(L,NY,NX)=0.0
      ZALO1H(L,NY,NX)=0.0
      ZALO2H(L,NY,NX)=0.0
      ZALO3H(L,NY,NX)=0.0
      ZALO4H(L,NY,NX)=0.0
      ZALSH(L,NY,NX)=0.0
      ZFEO1H(L,NY,NX)=0.0
      ZFEO2H(L,NY,NX)=0.0
      ZFEO3H(L,NY,NX)=0.0
      ZFEO4H(L,NY,NX)=0.0
      ZFESH(L,NY,NX)=0.0
      ZCAOH(L,NY,NX)=0.0
      ZCACH(L,NY,NX)=0.0
      ZCAHH(L,NY,NX)=0.0
      ZCASH(L,NY,NX)=0.0
      ZMGOH(L,NY,NX)=0.0
      ZMGCH(L,NY,NX)=0.0
      ZMGHH(L,NY,NX)=0.0
      ZMGSH(L,NY,NX)=0.0
      ZNACH(L,NY,NX)=0.0
      ZNASH(L,NY,NX)=0.0
      ZKASH(L,NY,NX)=0.0
      H0PO4H(L,NY,NX)=0.0
      H1PO4H(L,NY,NX)=0.0
      H3PO4H(L,NY,NX)=0.0
      ZFE1PH(L,NY,NX)=0.0
      ZFE2PH(L,NY,NX)=0.0
      ZCA0PH(L,NY,NX)=0.0
      ZCA1PH(L,NY,NX)=0.0
      ZCA2PH(L,NY,NX)=0.0
      ZMG1PH(L,NY,NX)=0.0
      H0POBH(L,NY,NX)=0.0
      H1POBH(L,NY,NX)=0.0
      H3POBH(L,NY,NX)=0.0
      ZFE1BH(L,NY,NX)=0.0
      ZFE2BH(L,NY,NX)=0.0
      ZCA0BH(L,NY,NX)=0.0
      ZCA1BH(L,NY,NX)=0.0
      ZCA2BH(L,NY,NX)=0.0
      ZMG1BH(L,NY,NX)=0.0
C
C     INITIAL STATE VARIABLES FOR EXCHANGEABLE CATIONS AND ANIONS
C     IN NON-BAND AND BAND ZONES
C
C     XN4,XHY,XAL,XFE,XCA,XMG,XNA,XKA,XHC,XOH0,XOH1,XOH2
C        XH1P,XH2P=exchangeable NH4,H,AL,FE,CA,MG,NA,K,HCO3
C        OH,OH2,HPO4,H2PO4
C     VLNH4,VLNHB=fractions of soil volume in NH4 non-band,band
C     VLNO3,VLNOB=fractions of soil volume in NO3 non-band,band
C     VLPO4,VLPOB=fractions of soil volume in H2PO4 non-band,band
C
      XN4(L,NY,NX)=XN41*BKVL(L,NY,NX)*VLNH4(L,NY,NX)
      XNB(L,NY,NX)=XN41*BKVL(L,NY,NX)*VLNHB(L,NY,NX)
      XHY(L,NY,NX)=XHY1*BKVL(L,NY,NX)
      XAL(L,NY,NX)=XAL1*BKVL(L,NY,NX) 
      XFE(L,NY,NX)=XFE1*BKVL(L,NY,NX) 
      XCA(L,NY,NX)=XCA1*BKVL(L,NY,NX) 
      XMG(L,NY,NX)=XMG1*BKVL(L,NY,NX) 
      XNA(L,NY,NX)=XNA1*BKVL(L,NY,NX)
      XKA(L,NY,NX)=XKA1*BKVL(L,NY,NX)
      XHC(L,NY,NX)=XHC1*BKVL(L,NY,NX)
      XOH0(L,NY,NX)=XOH01*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XOH1(L,NY,NX)=XOH11*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XOH2(L,NY,NX)=XOH21*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XH1P(L,NY,NX)=XH1P1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XH2P(L,NY,NX)=XH2P1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      XOH0B(L,NY,NX)=XOH01*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XOH1B(L,NY,NX)=XOH11*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XOH2B(L,NY,NX)=XOH21*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XH1PB(L,NY,NX)=XH1P1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      XH2PB(L,NY,NX)=XH2P1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
C
C     INITIAL STATE VARIABLES FOR PRECIPITATES 
C
C     P*=precipitate content (mol)
C     ALOH,FEOH,CACO,CASO,ALPO,FEPO,CAPD,CAPH,CAPM
C        =AL(OH)3,FE(OH)3,CACO3,CASO4,ALPO4,FEPO4,CAHPO4
C         CA(H2PO4)2,hydroxyapatite     
C
      SSAL=(0.3*CSAND(L,NY,NX)+2.2*CSILT(L,NY,NX)
     2+8.0*CCLAY(L,NY,NX))*BKVL(L,NY,NX) 
      QALSI(L,NY,NX)=0.167*SSAL*5.0E+03
      QFESI(L,NY,NX)=0.167*SSAL*5.0E+03
      QCASI(L,NY,NX)=0.167*SSAL*5.0E+03
      QMGSI(L,NY,NX)=0.167*SSAL*5.0E+03
      QNASI(L,NY,NX)=0.167*SSAL*5.0E+03
      QKASI(L,NY,NX)=0.167*SSAL*5.0E+03
      PALOH(L,NY,NX)=PALOH1*BKVL(L,NY,NX)
      PFEOH(L,NY,NX)=PFEOH1*BKVL(L,NY,NX)
      PCACO(L,NY,NX)=PCACO1*BKVL(L,NY,NX)
      PCASO(L,NY,NX)=PCASO1*BKVL(L,NY,NX)
      PALPO(L,NY,NX)=PALPO1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PFEPO(L,NY,NX)=PFEPO1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PCAPD(L,NY,NX)=PCAPD1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PCAPH(L,NY,NX)=PCAPH1*BKVL(L,NY,NX)*VLPO4(L,NY,NX)
      PCAPM(L,NY,NX)=0.0
      PALPB(L,NY,NX)=PALPO1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PFEPB(L,NY,NX)=PFEPO1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PCPDB(L,NY,NX)=PCAPD1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PCPHB(L,NY,NX)=PCAPH1*BKVL(L,NY,NX)*VLPOB(L,NY,NX)
      PCPMB(L,NY,NX)=0.0
      ECND(L,NY,NX)=0.0
      ZNH4S(L,NY,NX)=ZNH4S(L,NY,NX)+0.5*OSN(1,2,L,NY,NX)
      OSN(1,2,L,NY,NX)=OSN(1,2,L,NY,NX)-0.5*OSN(1,2,L,NY,NX)
C     IF(K.EQ.3.AND.L.EQ.1)THEN
C     WRITE(*,2222)'XN4F',I,K,L
C    2,XN4(L,NY,NX),XN41,BKVL(L,NY,NX),VLNH4(L,NY,NX)
C    3,XHY(L,NY,NX),XHY1,BKVL(L,NY,NX)
C     WRITE(*,2222)'XOH2F',I,K,L
C    2,XOH21,XOH11,XOH01,XH2P1,XH1P1
C    3,XH1P(L,NY,NX),XH2P(L,NY,NX),BKVL(L,NY,NX),VLPO4(L,NY,NX) 
C     WRITE(*,2222)'PCACO',I,K,L
C    2,PCACO(L,NY,NX),PCACO1,BKVL(L,NY,NX)
2222  FORMAT(A8,3I4,20E12.4)
C     ENDIF
      ENDIF
      ENDIF
2000  CONTINUE
1200  CONTINUE
C
C     SURFACE LITTER
C
C     BKVL=soil mass (Mg)
C     ORGC=SOC(g Mg-1) from soil file
C     XCOOH,XHC1=carboxyl exchange sites,occupied by H+ (mol)
C     ORGC=surface litter C (g)
C     C*1=litter ion concentration (mol Mg-1) 
C
      IF(ISALTG.NE.0)THEN
      IF(BKVL(0,NY,NX).GT.ZEROS(NY,NX))THEN
      XCOOH=AMAX1(ZEROC,COOH*1.0E-06*ORGC(0,NY,NX)/BKVL(0,NY,NX))
      ELSE
      XCOOH=ZERO
      ENDIF
      XHC1=XCOOH*CHY1/DPCOH 
      CCEC0=XCOOH
      CN41=CNH4(NU(NY,NX),NY,NX)*0.10/14.0
      CHY1=10.0**(-(PH(0,NY,NX)-3.0))
      COH1=DPH2O/CHY1
      CAL1=SPALO/COH1**3
      CFE1=SPFEO/COH1**3
      CCA1=CCA(NU(NY,NX),NY,NX)
      CMG1=CMG(NU(NY,NX),NY,NX)
      CNA1=CNA(NU(NY,NX),NY,NX)
      CKA1=CKA(NU(NY,NX),NY,NX)
      CSO41=CSOU(NU(NY,NX),NY,NX)
      CCL1=CCLU(NU(NY,NX),NY,NX) 
      CCO31=CC3U(NU(NY,NX),NY,NX)
      CHCO31=CHCU(NU(NY,NX),NY,NX)
      CALO1=CAL1U(NU(NY,NX),NY,NX)
      CALO2=CAL2U(NU(NY,NX),NY,NX)
      CALO3=CAL3U(NU(NY,NX),NY,NX)
      CALO4=CAL4U(NU(NY,NX),NY,NX)
      CALS1=CALSU(NU(NY,NX),NY,NX)
      CFEO1=CFE1U(NU(NY,NX),NY,NX)
      CFEO2=CFE2U(NU(NY,NX),NY,NX)
      CFEO3=CFE3U(NU(NY,NX),NY,NX)
      CFEO4=CFE4U(NU(NY,NX),NY,NX)
      CFES1=CFESU(NU(NY,NX),NY,NX)
      CCAO1=CCAOU(NU(NY,NX),NY,NX)
      CCAC1=CCACU(NU(NY,NX),NY,NX)
      CCAH1=CCAHU(NU(NY,NX),NY,NX)
      CCAS1=CCASU(NU(NY,NX),NY,NX)
      CMGO1=CMGOU(NU(NY,NX),NY,NX)
      CMGC1=CMGCU(NU(NY,NX),NY,NX)
      CMGH1=CMGHU(NU(NY,NX),NY,NX)
      CMGS1=CMGSU(NU(NY,NX),NY,NX)
      CNAC1=CNACU(NU(NY,NX),NY,NX)
      CNAS1=CNASU(NU(NY,NX),NY,NX)
      CKAS1=CKASU(NU(NY,NX),NY,NX)
      CH0P1=CH0PU(NU(NY,NX),NY,NX)
      CH3P1=CH3PU(NU(NY,NX),NY,NX)
      CF1P1=CF1PU(NU(NY,NX),NY,NX)
      CF2P1=CF2PU(NU(NY,NX),NY,NX)
      CC0P1=CC0PU(NU(NY,NX),NY,NX)
      CC1P1=CC1PU(NU(NY,NX),NY,NX)
      CC2P1=CC2PU(NU(NY,NX),NY,NX)
      CM1P1=CM1PU(NU(NY,NX),NY,NX)
      DO 3000 M=1,MRXN
C
C     ION ACTIVITY COEFFICIENTS
C
C     CC*,CA*=total cation,anion concentration (mol m-3)
C     CSTR*=ion strengths
C     A*1=ion activity coefficients
C
      CC3=CAL1+CFE1
      CA3=CH0P1
      CC2=CCA1+CMG1+CALO1+CFEO1+CF2P1
      CA2=CSO41+CCO31+CH1P1
      CC1=CN41+CHY1+CNA1+CKA1+CALO2+CFEO2+CALS1+CFES1+CCAO1
     2+CCAH1+CMGO1+CMGH1+CF1P1+CC2P1
      CA1=CNO1+COH1+CHCO31+CCL1+CALO4+CFEO4+CNAC1+CNAS1+CKAS1
     2+CH2P1+CC0P1
      CSTR1=1.0E-03*(9.0*(CC3+CA3)+4.0*(CC2+CA2)+CC1+CA1)
      CSTRQ=SQRT(CSTR1)
      CSTRX=CSTRQ/(1.0+CSTRQ)-0.20*CSTR1
      A1R=AMIN1(1.0,10.0**(-0.509*1.0*CSTRX))
      A2R=AMIN1(1.0,10.0**(-0.509*4.0*CSTRX))
      A3R=AMIN1(1.0,10.0**(-0.509*9.0*CSTRX))
      AN41=CN41*A1R
      AHY1=CHY1*A1R
      AAL1=CAL1*A3R
      AFE1=CFE1*A3R
      ACA1=CCA1*A2R
      AMG1=CMG1*A2R
      ANA1=CNA1*A1R
      AKA1=CKA1*A1R
C
C     CATION EXCHANGE
C
C     XCEC=cation exchange capacity from soil file (mol)
C     GKC4,GKCH,GKCA,GKCM,GKCN,GKCK=Gapon selectivity coefficients for
C        Ca-NH4,Ca-H,Ca-Al,Ca-Mg,Ca-Na,Ca-K from soil file
C     A*1=ion activity
C     X*Q=exchangeable ion concentration at equilibrium (mol Mg-1) 
C     X*1=exchangeable ion concentration (mol Mg-1) 
C     RX*=cation exchange
C     TADC=adsorption rate constant
C
      IF(M.EQ.1)THEN
      IF(ORGC(0,NY,NX).GT.ZEROS(NY,NX))THEN
      AALX=AMAX1(ZEROC,AAL1)**0.333
      AFEX=AMAX1(ZEROC,AFE1)**0.333
      ACAX=AMAX1(ZEROC,ACA1)**0.500
      AMGX=AMAX1(ZEROC,AMG1)**0.500
      XCAX=CCEC0/(1.0+GKC4(NU(NY,NX),NY,NX)*AN41/ACAX
     3+GKCH(NU(NY,NX),NY,NX)*AHY1/ACAX
     3+GKCA(NU(NY,NX),NY,NX)*AALX/ACAX
     4+GKCA(NU(NY,NX),NY,NX)*AFEX/ACAX
     4+GKCM(NU(NY,NX),NY,NX)*AMGX/ACAX
     5+GKCN(NU(NY,NX),NY,NX)*ANA1/ACAX
     5+GKCK(NU(NY,NX),NY,NX)*AKA1/ACAX)
      XN4Q=XCAX*AN41*GKC4(NU(NY,NX),NY,NX)
      XHYQ=XCAX*AHY1*GKCH(NU(NY,NX),NY,NX) 
      XALQ=XCAX*AALX*GKCA(NU(NY,NX),NY,NX) 
      XFEQ=XCAX*AFEX*GKCA(NU(NY,NX),NY,NX) 
      XCAQ=XCAX*ACAX
      XMGQ=XCAX*AMGX*GKCM(NU(NY,NX),NY,NX) 
      XNAQ=XCAX*ANA1*GKCN(NU(NY,NX),NY,NX) 
      XKAQ=XCAX*AKA1*GKCK(NU(NY,NX),NY,NX) 
      XTLQ=XN4Q+XALQ+XFEQ+XCAQ+XMGQ+XHYQ+XNAQ+XKAQ 
      IF(XTLQ.GT.ZERO)THEN
      FX=CCEC0/XTLQ
      ELSE
      FX=0.0
      ENDIF
      XN4Q=FX*XN4Q
      XHYQ=FX*XHYQ
      XALQ=FX*XALQ
      XFEQ=FX*XFEQ
      XCAQ=FX*XCAQ
      XMGQ=FX*XMGQ
      XNAQ=FX*XNAQ
      XKAQ=FX*XKAQ
      XN41=XN4Q
      XHY1=XHYQ
      XAL1=XALQ/3.0
      XFE1=XFEQ/3.0
      XCA1=XCAQ/2.0
      XMG1=XMGQ/2.0
      XNA1=XNAQ
      XKA1=XKAQ
C     IF((M.LE.10.OR.(M/100)*100.EQ.M).AND.L.LE.4)THEN 
C     WRITE(*,1113)'RXCA0',M 
C    2,XN4Q,XHYQ,XALQ,XFEQ,XCAQ,XMGQ,XNAQ,XKAQ
C    2,XN41,XHY1,XAL1,XFE1,XCA1,XMG1,XNA1,XKA1
C    2,AN41,AHY1,AAL1,AFE1,ACA1,AMG1,ANA1,AKA1
C    2,XN41+XHY1+XAL1*3.0+XFE1*3.0+XCA1*2.0+XMG1*2.0+XNA1+XKA1
C    2,CCEC0,XCAX,XTLQ,FX,TXXX,TXXY
C     ENDIF
      ELSE
      XN41=0.0
      XHY1=0.0
      XAL1=0.0
      XFE1=0.0
      XCA1=0.0
      XMG1=0.0
      XNA1=0.0
      XKA1=0.0
      ENDIF
      ENDIF
C
C     DISSOCIATION OF CARBOXYL RADICALS
C
C     RXHC=H+ adsorption on carboxyl exchange sites
C
      XCOO=AMAX1(ZEROC,XCOOH-XHC1)
      RXHC=TADC*(AHY1*XCOO-DPCOH*XHC1)
     2/(AMAX1(AHY1,XCOO)+AMAX1(DPCOH,XHC1))
      XHC1=XHC1+RXHC
C     WRITE(*,1113)'XHC0',M,XHC1*BKVL(0,NY,NX),XHC1,BKVL(0,NY,NX)
C    2,XCOOH,CHY1,AHY1,DPCOH,COOH,ORGC(0,NY,NX),RXHC,A1R,A2R,A3R 
1113  FORMAT(A8,1I4,/,8F16.8,/,8F16.8,/,8F16.8,/,8F16.8,/
     2,8F16.8,/,8F16.8,/,8F16.8)
3000  CONTINUE 
      XHC(0,NY,NX)=XHC1*BKVL(0,NY,NX)
      ELSE
      XHC(0,NY,NX)=0.0
      ENDIF
C
C     INITIAL STATE VARIABLES FOR MINERALS IN SURFACE LITTER
C
C     surface litter L=0
C     C*G=litter gaseous gas content (g)
C     C*S=litter aqueous gas content (g)
C     C*E=atmospheric gas concentration (g m-2)
C     VOLP,VOLW=litter air,water content (m3)
C     S*X=gas solubility (g m-3 / (g m-3))
C
      IF(DATA(20).EQ.'NO'.AND.IGO.EQ.0)THEN
      CO2G(0,NY,NX)=CCO2EI(NY,NX)*VOLP(0,NY,NX)
      CH4G(0,NY,NX)=CCH4E(NY,NX)*VOLP(0,NY,NX)
      OXYG(0,NY,NX)=COXYE(NY,NX)*VOLP(0,NY,NX)
      Z2GG(0,NY,NX)=CZ2GE(NY,NX)*VOLP(0,NY,NX)
      Z2OG(0,NY,NX)=CZ2OE(NY,NX)*VOLP(0,NY,NX)
      ZNH3G(0,NY,NX)=CNH3E(NY,NX)*VOLP(0,NY,NX)
      H2GG(0,NY,NX)=CH2GE(NY,NX)*VOLP(0,NY,NX)
      CO2S(0,NY,NX)=CCO2EI(NY,NX)*SCO2X
     2*EXP(0.843-0.0281*ATCA(NY,NX))*VOLW(0,NY,NX)
      CH4S(0,NY,NX)=CCH4E(NY,NX)*SCH4X
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(0,NY,NX)
      OXYS(0,NY,NX)=COXYE(NY,NX)*SOXYX
     2*EXP(0.516-0.0172*ATCA(NY,NX))*VOLW(0,NY,NX)
      Z2GS(0,NY,NX)=CZ2GE(NY,NX)*SN2GX
     2*EXP(0.456-0.0152*ATCA(NY,NX))*VOLW(0,NY,NX)
      Z2OS(0,NY,NX)=CZ2OE(NY,NX)*SN2OX
     2*EXP(0.897-0.0299*ATCA(NY,NX))*VOLW(0,NY,NX)
      H2GS(0,NY,NX)=CH2GE(NY,NX)*SH2GX
     2*EXP(0.597-0.0199*ATCA(NY,NX))*VOLW(0,NY,NX)
C
C     SOLUTES
C
C     Z*=litter solute content (g or mol)
C
      ZNH4S(0,NY,NX)=CN41*VOLW(0,NY,NX)*14.0
      ZNH3S(0,NY,NX)=CN3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNO3S(0,NY,NX)=CNOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNO2S(0,NY,NX)=0.0
      H2PO4(0,NY,NX)=CH2PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      H1PO4(0,NY,NX)=CH1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNH4B(0,NY,NX)=0.0
      ZNH3B(0,NY,NX)=0.0
      ZNO3B(0,NY,NX)=0.0
      ZNO2B(0,NY,NX)=0.0
      H2POB(0,NY,NX)=0.0
      H1POB(0,NY,NX)=0.0
      ZNO2B(0,NY,NX)=0.0
      CHY0=10.0**(-(PH(0,NY,NX)-3.0))
      COH0=DPH2O/CHY0
      ZHY(0,NY,NX)=CHY0*VOLW(0,NY,NX)
      ZOH(0,NY,NX)=COH0*VOLW(0,NY,NX)
      ZAL(0,NY,NX)=CAL1*VOLW(0,NY,NX)
      ZFE(0,NY,NX)=CFE1*VOLW(0,NY,NX)
      ZCA(0,NY,NX)=CCA1*VOLW(0,NY,NX)
      ZMG(0,NY,NX)=CMG1*VOLW(0,NY,NX)
      ZNA(0,NY,NX)=CNA1*VOLW(0,NY,NX)
      ZKA(0,NY,NX)=CKA1*VOLW(0,NY,NX)
C
C     INITIAL STATE VARIABLES FOR CATIONS, ANIONS AND ION PAIRS 
C     IN LITTER
C
      IF(ISALTG.NE.0)THEN
      ZSO4(0,NY,NX)=CSOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCL(0,NY,NX)=CCLU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCO3(0,NY,NX)=CC3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZHCO3(0,NY,NX)=CHCU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH1(0,NY,NX)=CAL1U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH2(0,NY,NX)=CAL2U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH3(0,NY,NX)=CAL3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALOH4(0,NY,NX)=CAL4U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZALS(0,NY,NX)=CALSU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH1(0,NY,NX)=CFE1U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH2(0,NY,NX)=CFE2U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH3(0,NY,NX)=CFE3U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFEOH4(0,NY,NX)=CFE4U(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFES(0,NY,NX)=CFESU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAO(0,NY,NX)=CCAOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAC(0,NY,NX)=CCACU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAH(0,NY,NX)=CCAHU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCAS(0,NY,NX)=CCASU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGO(0,NY,NX)=CMGOU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGC(0,NY,NX)=CMGCU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGH(0,NY,NX)=CMGHU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMGS(0,NY,NX)=CMGSU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNAC(0,NY,NX)=CNACU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZNAS(0,NY,NX)=CNASU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZKAS(0,NY,NX)=CKASU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZHYSI(0,NY,NX)=1.0E-03*VOLW(0,NY,NX)
      H0PO4(0,NY,NX)=CH0PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      H3PO4(0,NY,NX)=CH3PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFE1P(0,NY,NX)=CF1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZFE2P(0,NY,NX)=CF2PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCA0P(0,NY,NX)=CC0PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCA1P(0,NY,NX)=CC1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZCA2P(0,NY,NX)=CC2PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ZMG1P(0,NY,NX)=CM1PU(NU(NY,NX),NY,NX)*VOLW(0,NY,NX)
      ELSE
      ZSO4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCL(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCO3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZHCO3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH1(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH2(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALOH4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZALS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH1(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH2(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH3(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFEOH4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFES(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAO(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAC(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAH(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCAS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGO(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGC(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGH(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMGS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZNAC(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZNAS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZKAS(0,NY,NX)=0.0*VOLW(0,NY,NX)
      H0PO4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      H3PO4(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFE1P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZFE2P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCA0P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCA1P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZCA2P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ZMG1P(0,NY,NX)=0.0*VOLW(0,NY,NX)
      ENDIF
C
C     EXCHANGEABLE CATIONS AND ANIONS
C
      XN4(0,NY,NX)=XN41*BKVL(0,NY,NX)
      XNB(0,NY,NX)=0.0
      XHY(0,NY,NX)=XHY1*BKVL(0,NY,NX)
      XAL(0,NY,NX)=XAL1*BKVL(0,NY,NX)
      XFE(0,NY,NX)=XFE1*BKVL(0,NY,NX)
      XCA(0,NY,NX)=XCA1*BKVL(0,NY,NX)
      XMG(0,NY,NX)=XMG1*BKVL(0,NY,NX)
      XNA(0,NY,NX)=XNA1*BKVL(0,NY,NX)
      XKA(0,NY,NX)=XKA1*BKVL(0,NY,NX) 
      XOH0(0,NY,NX)=0.0
      XOH1(0,NY,NX)=0.0
      XOH2(0,NY,NX)=0.0
      XH1P(0,NY,NX)=0.0
      XH2P(0,NY,NX)=0.0
      XOH0B(0,NY,NX)=0.0
      XOH1B(0,NY,NX)=0.0
      XOH2B(0,NY,NX)=0.0
      XH1PB(0,NY,NX)=0.0
      XH2PB(0,NY,NX)=0.0
C
C     INITIAL STATE VARIABLES FOR GAS AND MINERAL N AND P IN SNOWPACK
C     FROM CONCENTRATIONS IN PRECIPITATION
C
      DO 9985 L=1,JS
      IF(VHCPW(L,NY,NX).GT.VHCPWX(NY,NX))THEN
C
C     VOLSSL,VOLWSL,VOLISL,VOLSL=snow,water,ice,total layer volume(m3)
C     DENSI=ice density (Mg m-3)
C     *W=snowpack solute content (g or mol)
C     C*R=solute concentration in precipitation (mol m-3)
C
      VOLWW=VOLWSL(L,NY,NX)+VOLSSL(L,NY,NX)+VOLISL(L,NY,NX)*DENSI
      CO2W(L,NY,NX)=VOLWW*CCOR(NY,NX)
      CH4W(L,NY,NX)=VOLWW*CCHR(NY,NX)
      OXYW(L,NY,NX)=VOLWW*COXR(NY,NX)
      ZNGW(L,NY,NX)=VOLWW*CNNR(NY,NX)
      ZN2W(L,NY,NX)=VOLWW*CN2R(NY,NX)
      ZN4W(L,NY,NX)=VOLWW*CN4R(NY,NX)*14.0
      ZN3W(L,NY,NX)=VOLWW*CN3R(NY,NX)*14.0
      ZNOW(L,NY,NX)=VOLWW*CNOR(NY,NX)*14.0
      Z1PW(L,NY,NX)=VOLWW*CH1PR(NY,NX)*31.0
      ZHPW(L,NY,NX)=VOLWW*CPOR(NY,NX)*31.0
C
C     INITIAL STATE VARIABLES FOR CATIONS AND ANIONS IN SNOWPACK
C
      IF(ISALTG.NE.0)THEN
      ZALW(L,NY,NX)=VOLWW*CALR(NY,NX)
      ZFEW(L,NY,NX)=VOLWW*CFER(NY,NX)
      ZHYW(L,NY,NX)=VOLWW*CHYR(NY,NX)
      ZCAW(L,NY,NX)=VOLWW*CCAR(NY,NX)
      ZMGW(L,NY,NX)=VOLWW*CMGR(NY,NX)
      ZNAW(L,NY,NX)=VOLWW*CNAR(NY,NX)
      ZKAW(L,NY,NX)=VOLWW*CKAR(NY,NX)
      ZOHW(L,NY,NX)=VOLWW*COHR(NY,NX)
      ZSO4W(L,NY,NX)=VOLWW*CSOR(NY,NX)
      ZCLW(L,NY,NX)=VOLWW*CCLR(NY,NX)
      ZCO3W(L,NY,NX)=VOLWW*CC3R(NY,NX)
      ZHCO3W(L,NY,NX)=VOLWW*CHCR(NY,NX)
      ZALH1W(L,NY,NX)=VOLWW*CAL1R(NY,NX)
      ZALH2W(L,NY,NX)=VOLWW*CAL2R(NY,NX)
      ZALH3W(L,NY,NX)=VOLWW*CAL3R(NY,NX)
      ZALH4W(L,NY,NX)=VOLWW*CAL4R(NY,NX)
      ZALSW(L,NY,NX)=VOLWW*CALSR(NY,NX)
      ZFEH1W(L,NY,NX)=VOLWW*CFE1R(NY,NX)
      ZFEH2W(L,NY,NX)=VOLWW*CFE2R(NY,NX)
      ZFEH3W(L,NY,NX)=VOLWW*CFE3R(NY,NX)
      ZFEH4W(L,NY,NX)=VOLWW*CFE4R(NY,NX)
      ZFESW(L,NY,NX)=VOLWW*CFESR(NY,NX)
      ZCAOW(L,NY,NX)=VOLWW*CCAOR(NY,NX)
      ZCACW(L,NY,NX)=VOLWW*CCACR(NY,NX)
      ZCAHW(L,NY,NX)=VOLWW*CCAHR(NY,NX)
      ZCASW(L,NY,NX)=VOLWW*CCASR(NY,NX)
      ZMGOW(L,NY,NX)=VOLWW*CMGOR(NY,NX)
      ZMGCW(L,NY,NX)=VOLWW*CMGCR(NY,NX)
      ZMGHW(L,NY,NX)=VOLWW*CMGHR(NY,NX)
      ZMGSW(L,NY,NX)=VOLWW*CMGSR(NY,NX)
      ZNACW(L,NY,NX)=VOLWW*CNACR(NY,NX)
      ZNASW(L,NY,NX)=VOLWW*CNASR(NY,NX)
      ZKASW(L,NY,NX)=VOLWW*CKASR(NY,NX)
      H0PO4W(L,NY,NX)=VOLWW*CH0PR(NY,NX)
      H3PO4W(L,NY,NX)=VOLWW*CH3PR(NY,NX)
      ZFE1PW(L,NY,NX)=VOLWW*CF1PR(NY,NX)
      ZFE2PW(L,NY,NX)=VOLWW*CF2PR(NY,NX)
      ZCA0PW(L,NY,NX)=VOLWW*CC0PR(NY,NX)
      ZCA1PW(L,NY,NX)=VOLWW*CC1PR(NY,NX)
      ZCA2PW(L,NY,NX)=VOLWW*CC2PR(NY,NX)
      ZMG1PW(L,NY,NX)=VOLWW*CM1PR(NY,NX)
      ENDIF
      ELSE
      CO2W(L,NY,NX)=0.0
      CH4W(L,NY,NX)=0.0
      OXYW(L,NY,NX)=0.0
      ZNGW(L,NY,NX)=0.0
      ZN2W(L,NY,NX)=0.0
      ZN4W(L,NY,NX)=0.0
      ZN3W(L,NY,NX)=0.0
      ZNOW(L,NY,NX)=0.0
      Z1PW(L,NY,NX)=0.0
      ZHPW(L,NY,NX)=0.0
C
C     INITIAL STATE VARIABLES FOR CATIONS AND ANIONS IN SNOWPACK
C
      IF(ISALTG.NE.0)THEN
      ZALW(L,NY,NX)=0.0
      ZFEW(L,NY,NX)=0.0
      ZHYW(L,NY,NX)=0.0
      ZCAW(L,NY,NX)=0.0
      ZMGW(L,NY,NX)=0.0
      ZNAW(L,NY,NX)=0.0
      ZKAW(L,NY,NX)=0.0
      ZOHW(L,NY,NX)=0.0
      ZSO4W(L,NY,NX)=0.0 
      ZCLW(L,NY,NX)=0.0 
      ZCO3W(L,NY,NX)=0.0 
      ZHCO3W(L,NY,NX)=0.0
      ZALH1W(L,NY,NX)=0.0
      ZALH2W(L,NY,NX)=0.0
      ZALH3W(L,NY,NX)=0.0
      ZALH4W(L,NY,NX)=0.0
      ZALSW(L,NY,NX)=0.0 
      ZFEH1W(L,NY,NX)=0.0 
      ZFEH2W(L,NY,NX)=0.0
      ZFEH3W(L,NY,NX)=0.0
      ZFEH4W(L,NY,NX)=0.0
      ZFESW(L,NY,NX)=0.0
      ZCAOW(L,NY,NX)=0.0
      ZCACW(L,NY,NX)=0.0
      ZCAHW(L,NY,NX)=0.0
      ZCASW(L,NY,NX)=0.0
      ZMGOW(L,NY,NX)=0.0
      ZMGCW(L,NY,NX)=0.0
      ZMGHW(L,NY,NX)=0.0
      ZMGSW(L,NY,NX)=0.0
      ZNACW(L,NY,NX)=0.0
      ZNASW(L,NY,NX)=0.0
      ZKASW(L,NY,NX)=0.0
      H0PO4W(L,NY,NX)=0.0
      H3PO4W(L,NY,NX)=0.0
      ZFE1PW(L,NY,NX)=0.0
      ZFE2PW(L,NY,NX)=0.0
      ZCA0PW(L,NY,NX)=0.0
      ZCA1PW(L,NY,NX)=0.0
      ZCA2PW(L,NY,NX)=0.0
      ZMG1PW(L,NY,NX)=0.0
      ENDIF
      ENDIF
9985  CONTINUE
      ENDIF
9990  CONTINUE
9995  CONTINUE
      RETURN
      END



