      COMMON/BLK1N/WTSHN(JP,JY,JX),ZPOOLP(JP,JY,JX),WTLFN(JP,JY,JX)     &
     &,WTSHEN(JP,JY,JX),WTSTKN(JP,JY,JX),WTRSVN(JP,JY,JX)               &
     &,WTHSKN(JP,JY,JX),WTEARN(JP,JY,JX),WTGRNN(JP,JY,JX)               &
     &,WTSHTN(JC,JP,JY,JX),WTLFBN(JC,JP,JY,JX),WTSHBN(JC,JP,JY,JX)      &
     &,WTSTBN(JC,JP,JY,JX),WTRSBN(JC,JP,JY,JX),WTHSBN(JC,JP,JY,JX)      &
     &,WTEABN(JC,JP,JY,JX),WTGRBN(JC,JP,JY,JX),ZPOOL(JC,JP,JY,JX)       &
     &,WGLFN(0:25,JC,JP,JY,JX),WGSHN(0:25,JC,JP,JY,JX)                  &
     &,WGNODN(0:25,JC,JP,JY,JX),WGLFLN(JZ,0:25,JC,JP,JY,JX)             &
     &,ZPOOLR(2,JZ,JP,JY,JX),CZPOLR(2,JZ,JP,JY,JX),ZPOOLN(JZ,JP,JY,JX)  &
     &,ZSNC(4,0:1,0:JZ,JP,JY,JX),CFOPN(0:5,4,JP,JY,JX),WTRTN(JP,JY,JX)  &
     &,WTRT1N(2,JZ,JC,JP,JY,JX),WTRT2N(2,JZ,JC,JP,JY,JX),WTNDN(JP,JY,JX)&
     &,WTNDLN(JZ,JP,JY,JX),CZPOLP(JP,JY,JX),CZPOLB(JC,JP,JY,JX)         &
     &,RTWT1N(2,JC,JP,JY,JX),WTSTDN(4,JP,JY,JX)                         &
     &,WTSTGN(JP,JY,JX),ZPOLNB(JC,JP,JY,JX),ZPOLNP(JP,JY,JX)            &
     &,WTNDBN(JC,JP,JY,JX)
