      COMMON/BLK10/PARG(JY,JX),PARR(JY,JX),FLWM(60,3,JD,JV,JH)          &
     &,FLWHM(60,3,JD,JV,JH),QRM(60,2,JV,JH),QSM(60,2,JV,JH)             &
     &,VOLWM(60,0:JZ,JY,JX),VOLWHM(60,JZ,JY,JX),VOLPM(60,0:JZ,JY,JX)    &
     &,HYSM(60,JZ,JY,JX),FILM(60,0:JZ,JY,JX),QRV(60,2,JV,JH)            &
     &,VOLGM(60,JY,JX),DFGS(60,0:JZ,JY,JX),ROXSK(60,0:JZ,JY,JX)         &
     &,FLWRM(60,JY,JX),FLPM(60,JZ,JY,JX),FINHM(60,JZ,JY,JX)             &
     &,THETPM(60,0:JZ,JY,JX),TORT(60,0:JZ,JY,JX),TORTH(60,JZ,JY,JX)     &
     &,FLQRM(60,JY,JX),FLQSM(60,JY,JX),FLQHM(60,JY,JX)                  &
     &,FLQWM(60,JS,JY,JX),VHCPWM(60,JS,JY,JX)
