      COMMON/BLK12A/WSTR(JP,JY,JX),OSTR(JP,JY,JX)                       &
     &,RAD1(JP,JY,JX),THRM1(JP,JY,JX)                                   &
     &,EFLXC(JP,JY,JX),SFLXC(JP,JY,JX),HFLXC(JP,JY,JX),ENGYX(JP,JY,JX)  &
     &,VHCPC(JP,JY,JX),PSILT(JP,JY,JX),PSILG(JP,JY,JX),PSILO(JP,JY,JX)  &
     &,RC(JP,JY,JX),RA(JP,JY,JX),EP(JP,JY,JX),EVAPC(JP,JY,JX)           &
     &,UPWTR(2,JZ,JP,JY,JX),PSIRT(2,JZ,JP,JY,JX)                        &
     &,PSIRO(2,JZ,JP,JY,JX),PSIRG(2,JZ,JP,JY,JX),CO2A(2,JZ,JP,JY,JX)    &
     &,OXYA(2,JZ,JP,JY,JX),CH4A(2,JZ,JP,JY,JX),Z2OA(2,JZ,JP,JY,JX)      &
     &,ZH3A(2,JZ,JP,JY,JX),CO2P(2,JZ,JP,JY,JX),OXYP(2,JZ,JP,JY,JX)      &
     &,CH4P(2,JZ,JP,JY,JX),Z2OP(2,JZ,JP,JY,JX),ZH3P(2,JZ,JP,JY,JX)      &
     &,ROXYP(2,JZ,JP,JY,JX),RCOFLA(2,JZ,JP,JY,JX),ROXFLA(2,JZ,JP,JY,JX) &
     &,RCHFLA(2,JZ,JP,JY,JX),RN2FLA(2,JZ,JP,JY,JX),RNHFLA(2,JZ,JP,JY,JX)&
     &,RCODFA(2,JZ,JP,JY,JX),ROXDFA(2,JZ,JP,JY,JX),RCHDFA(2,JZ,JP,JY,JX)&
     &,RN2DFA(2,JZ,JP,JY,JX),RNHDFA(2,JZ,JP,JY,JX),RCO2S(2,JZ,JP,JY,JX) &
     &,RUPOXS(2,JZ,JP,JY,JX),RUPCHS(2,JZ,JP,JY,JX),RUPN2S(2,JZ,JP,JY,JX)&
     &,RUPN3S(2,JZ,JP,JY,JX),RUPN3B(2,JZ,JP,JY,JX),RCO2P(2,JZ,JP,JY,JX) &
     &,RUPOXP(2,JZ,JP,JY,JX),RCO2M(2,JZ,JP,JY,JX),RCO2A(2,JZ,JP,JY,JX)  &
     &,UPOMC(JP,JY,JX),UPOMN(JP,JY,JX),UPOMP(JP,JY,JX),UPNH4(JP,JY,JX)  &
     &,UPNO3(JP,JY,JX),UPH2P(JP,JY,JX),UPH1P(JP,JY,JX),UPNF(JP,JY,JX)   &
     &,RCO2Z(JP,JY,JX),ROXYZ(JP,JY,JX),RCH4Z(JP,JY,JX),RN2OZ(JP,JY,JX)

