      COMMON/BLK1CR/WTRT(JP,JY,JX),WTRTS(JP,JY,JX),WSRTL(2,JZ,JP,JY,JX) &
     &,WTRT1(2,JZ,JC,JP,JY,JX),WTRT2(2,JZ,JC,JP,JY,JX)                  &
     &,WTRTD(2,JZ,JP,JY,JX),RTLGP(2,JZ,JP,JY,JX),RTLG1(2,JZ,JC,JP,JY,JX)&
     &,RTLG2(2,JZ,JC,JP,JY,JX),RTDNP(2,JZ,JP,JY,JX),RTN1(2,JZ,JP,JY,JX) &
     &,RTNL(2,JZ,JP,JY,JX),RTN2(2,JZ,JC,JP,JY,JX),RTLGA(2,JZ,JP,JY,JX)  &
     &,RTARP(2,JZ,JP,JY,JX),RTVLW(2,JZ,JP,JY,JX),RRAD1(2,JZ,JP,JY,JX)   &
     &,RTVLP(2,JZ,JP,JY,JX),RTDP1(2,JZ,JP,JY,JX),RRAD2(2,JZ,JP,JY,JX)   &
     &,RTLG1X(2,JP,JY,JX),RTLG2X(2,JP,JY,JX),WTRVC(JP,JY,JX)            &
     &,WTRVX(JP,JY,JX),WTNDL(JZ,JP,JY,JX),WTND(JP,JY,JX),WTRVN(JP,JY,JX)&
     &,WTRVP(JP,JY,JX),WTRTL(2,JZ,JP,JY,JX),CPOOLR(2,JZ,JP,JY,JX)       &
     &,CCPOLR(2,JZ,JP,JY,JX),RTWT1(2,JC,JP,JY,JX),HTCTL(JP,JY,JX)       &
     &,CWSRTL(2,JZ,JP,JY,JX),CPOOLN(JZ,JP,JY,JX)
