      COMMON/BLK16/VOLWSO,HEATSO,OXYGSO,TLRSDC,TLRSDN,TLRSDP            &
     &,TLORGC,TLORGN,TLORGP,TLNH4,TLNO3,TLPO4,TBALC,TBALN,TBALP         &
     &,CRAIN,HEATIN,OXYGIN,TORGF,TORGN,TORGP,CO2GIN,ZN2GIN,VOLWOU       &
     &,CEVAP,CRUN,HEATOU,OXYGOU,TCOU,TZOU,TPOU,TZIN,TPIN,XCSN,XZSN,XPSN &
     &,TLCO2G,TLN2G,HCO2G(JY,JX),HCH4G(JY,JX),HOXYG(JY,JX),HN2OG(JY,JX) &
     &,HNH3G(JY,JX),URAIQ(JY,JX),TOMT(JY,JX),TONT(JY,JX),TOPT(JY,JX)    &
     &,URSDC(JY,JX),UORGC(JY,JX),UORGF(JY,JX),UXCSN(JY,JX),UCO2S(JY,JX) &
     &,UDOCQ(JY,JX),UDOCD(JY,JX),TNBP(JY,JX),UEVAP(JY,JX),URAIN(JY,JX)  &
     &,URUN(JY,JX),UVOLW(JY,JX),UVOLO(JY,JX),URSDN(JY,JX),UORGN(JY,JX)  &
     &,UFERTN(JY,JX),UXZSN(JY,JX),UNH4(JY,JX),UNO3(JY,JX),UPO4(JY,JX)   &
     &,UDONQ(JY,JX),UDOND(JY,JX),UDOPQ(JY,JX),UDOPD(JY,JX),UPP4(JY,JX)  &
     &,UN2GS(JY,JX),URSDP(JY,JX),UORGP(JY,JX),UFERTP(JY,JX),UH2GG(JY,JX)&
     &,UXPSN(JY,JX),HN2GG(JY,JX),UN2GG(JY,JX),UION(JY,JX),UIONOU(JY,JX) &
     &,UCO2G(JY,JX),UCH4G(JY,JX),UOXYG(JY,JX),UNH3G(JY,JX),UN2OG(JY,JX) &
     &,UCO2F(JY,JX),UCH4F(JY,JX),UOXYF(JY,JX),UNH3F(JY,JX),UN2OF(JY,JX) &
     &,UPO4F(JY,JX),UDRAIN(JY,JX),ZDRAIN(JY,JX),PDRAIN(JY,JX)           &
     &,UCOP(JY,JX),USEDOU(JY,JX),PPT(JY,JX),UDICQ(JY,JX),UDICD(JY,JX)   &
     &,UDINQ(JY,JX),UDIND(JY,JX),UDIPQ(JY,JX),UDIPD(JY,JX),HVOLO(JY,JX) &
     &,WTSTGT(JY,JX),TION,TIONIN,TIONOU,TSEDSO,TSEDOU                   &
     &,TLH2G,H2GIN,H2GOU
