      COMMON/BLK2C/CCOQ(JY,JX),CCHQ(JY,JX),COXQ(JY,JX),CNNQ(JY,JX)      &
     &,CN2Q(JY,JX),COCU(0:4,JZ,JY,JX),CONU(0:4,JZ,JY,JX)                &
     &,COAU(0:4,JZ,JY,JX),CN4U(JZ,JY,JX),CN3U(JZ,JY,JX),CNOU(JZ,JY,JX)  &
     &,CH2PU(JZ,JY,JX),CNZU(JZ,JY,JX),CALU(JZ,JY,JX),CFEU(JZ,JY,JX)     &
     &,CHYU(JZ,JY,JX),CCAU(JZ,JY,JX),CMGU(JZ,JY,JX),CNAU(JZ,JY,JX)      &
     &,CKAU(JZ,JY,JX),COHU(JZ,JY,JX),CSOU(JZ,JY,JX),CCLU(JZ,JY,JX)      &
     &,CC3U(JZ,JY,JX),CHCU(JZ,JY,JX),CAL1U(JZ,JY,JX),CAL2U(JZ,JY,JX)    &
     &,CAL3U(JZ,JY,JX),CAL4U(JZ,JY,JX),CALSU(JZ,JY,JX),CFE1U(JZ,JY,JX)  &
     &,CFE2U(JZ,JY,JX),CFE3U(JZ,JY,JX),CFE4U(JZ,JY,JX),CFESU(JZ,JY,JX)  &
     &,CCAOU(JZ,JY,JX),CCACU(JZ,JY,JX),CCAHU(JZ,JY,JX),CCASU(JZ,JY,JX)  &
     &,CMGOU(JZ,JY,JX),CMGCU(JZ,JY,JX),CMGHU(JZ,JY,JX),CMGSU(JZ,JY,JX)  &
     &,CNACU(JZ,JY,JX),CNASU(JZ,JY,JX),CKASU(JZ,JY,JX),CH0PU(JZ,JY,JX)  &
     &,CH1PU(JZ,JY,JX),CH3PU(JZ,JY,JX),CF1PU(JZ,JY,JX),CF2PU(JZ,JY,JX)  &
     &,CC0PU(JZ,JY,JX),CC1PU(JZ,JY,JX),CC2PU(JZ,JY,JX),CM1PU(JZ,JY,JX)  &
     &,COPU(0:4,JZ,JY,JX),CCOU,CCHU,COXU,CNNU,CN2U,BKRS(0:2)
