      COMMON/BLK3/GROUP(JC,JP,JY,JX),GSTGI(JC,JP,JY,JX)                 &
     &,PSILZ(JP,JY,JX),VSTG(JC,JP,JY,JX),VSTGX(JC,JP,JY,JX)             &
     &,DGSTGI(JC,JP,JY,JX),DGSTGF(JC,JP,JY,JX),PSTG(JC,JP,JY,JX)        &
     &,PSTGI(JC,JP,JY,JX),GSTGF(JC,JP,JY,JX),PSTGF(JC,JP,JY,JX)         &
     &,TGSTGI(JC,JP,JY,JX),TGSTGF(JC,JP,JY,JX),FLG4(JC,JP,JY,JX)        &
     &,VRNS(JC,JP,JY,JX),VRNF(JC,JP,JY,JX),ATRP(JC,JP,JY,JX)            &
     &,FLGZ(JC,JP,JY,JX),VRNY(JC,JP,JY,JX),VRNZ(JC,JP,JY,JX)            &
     &,NBR(JP,JY,JX),NB1(JP,JY,JX),NRT(JP,JY,JX),KVSTGN(JC,JP,JY,JX)    &
     &,IDAY(10,JC,JP,JY,JX),NBT(JP,JY,JX),NBTB(JC,JP,JY,JX)             &
     &,NINR(JC,JP,JY,JX),KLEAF(JC,JP,JY,JX)                             &
     &,IDTHR(JP,JY,JX),IFLGR(JC,JP,JY,JX),IFLGQ(JC,JP,JY,JX)            &
     &,IFLGG(JC,JP,JY,JX),IDTHP(JP,JY,JX),KVSTG(JC,JP,JY,JX)            &
     &,IDTHB(JC,JP,JY,JX),NIX(JP,JY,JX),NI(JP,JY,JX),NG(JP,JY,JX)       &
     &,IFLGP(JC,JP,JY,JX),IFLGA(JC,JP,JY,JX),IFLGE(JC,JP,JY,JX)         &
     &,IFLGF(JC,JP,JY,JX),IFLGD(JC,JP,JY,JX),KLEAFX(JC,JP,JY,JX)
