      COMMON/BLK8B/ALBX(JY,JX),DPTH(JZ,JY,JX),DLYR(3,0:JZ,JY,JX)        &
     &,POROS(0:JZ,JY,JX),PSL(JZ,JY,JX),FCL(JZ,JY,JX)                    &
     &,WPL(JZ,JY,JX),PSD(JZ,JY,JX),FCD(JZ,JY,JX),ZD50(JY,JX)            &
     &,VOLX(0:JZ,JY,JX),BKVL(0:JZ,JY,JX),SRP(JZ,JY,JX),FORGC,FVLWB,FCH4F&
     &,CNRH(0:4),CPRH(0:4),DIST(3,JD,JV,JH),XDPTH(3,JZ,JY,JX)           &
     &,POROQ(0:JZ,JY,JX),TFND(0:JZ,JY,JX),FCI,WPI                       &
     &,PSIMS(JY,JX),PSIMX(JY,JX),PSIMN(JY,JX),PSISD(JY,JX),PSIMD(JY,JX) &
     &,SAND(JZ,JY,JX),SILT(JZ,JY,JX),CLAY(JZ,JY,JX),CDPTHZ(0:JZ,JY,JX)  &
     &,DPTHZ(JZ,JY,JX),AREA(3,0:JZ,JY,JX),DISP(3,JD,JV,JH),OXKM,PSIHY   &
     &,VOLXI(0:JZ,JY,JX),DLYRI(3,0:JZ,JY,JX),OMCI(3,0:4),OMCF(7),OMCA(7)&
     &,VOLAI(0:JZ,JY,JX),IUTYP(JY,JX),IXTYP(2,JY,JX)                    &
     &,IYTYP(0:2,366,JY,JX)
