#!/bin/bash -l
#SBATCH --job-name=ecosys_dk
#SBATCH --partition=lr3
#SBATCH --qos=lr_lowprio
#SBATCH --account=ac_co2seq
#SBATCH --mail-user=yaningliu@lbl.gov
#SBATCH --mail-type=all
#SBATCH --time=02:00:00
#SBATCH --ntasks=1

# /global/home/users/yaningl/repos/src_120316/ecosys.x << eor > log_dk3
/global/home/users/yaningl/repos/ecosys_120316_for_dukeforest/ecosys.x << eor > log_dk3
1 1 1 1
stdk3
tpdk3
10 1
1 1
w1996107641
opt1996
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w1997107641
opt1997
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w98dk3
opt1998
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w99dk3
opt1999
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w00dk3
opt2000
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w01dk3
opt2001
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w02dk3
opt2002
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w03dk3
opt2003
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w04dk3
opt2004
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
1 1
w05dk3
opt2005
sm
nlegg3
hc
hw
hn
hp
hh
dc
dw
NO
NO
NO
0 0
eor
