      COMMON/BLK12B/RUPNH4(2,JZ,JP,JY,JX),RUPNHB(2,JZ,JP,JY,JX)         &
     &,RUPNO3(2,JZ,JP,JY,JX),RUPNOB(2,JZ,JP,JY,JX),RUPH2P(2,JZ,JP,JY,JX)&
     &,RUPH2B(2,JZ,JP,JY,JX),RUONH4(2,JZ,JP,JY,JX),RUONHB(2,JZ,JP,JY,JX)&
     &,RUONO3(2,JZ,JP,JY,JX),RUONOB(2,JZ,JP,JY,JX),RUOH2P(2,JZ,JP,JY,JX)&
     &,RUOH2B(2,JZ,JP,JY,JX),RUCNH4(2,JZ,JP,JY,JX),RUCNHB(2,JZ,JP,JY,JX)&
     &,RUCNO3(2,JZ,JP,JY,JX),RUCNOB(2,JZ,JP,JY,JX),RUCH2P(2,JZ,JP,JY,JX)&
     &,RUCH2B(2,JZ,JP,JY,JX),RUPNF(JZ,JP,JY,JX),RUPHGS(2,JZ,JP,JY,JX)   &
     &,RUPH1P(2,JZ,JP,JY,JX),RUOH1P(2,JZ,JP,JY,JX),RUCH1P(2,JZ,JP,JY,JX)&
     &,RUPH1B(2,JZ,JP,JY,JX),RUOH1B(2,JZ,JP,JY,JX),RUCH1B(2,JZ,JP,JY,JX)&
     &,VOLWP(JP,JY,JX),RCO2N(2,JZ,JP,JY,JX),RDFOMC(2,0:4,JZ,JP,JY,JX)   &
     &,RDFOMN(2,0:4,JZ,JP,JY,JX),RDFOMP(2,0:4,JZ,JP,JY,JX)              &
     &,RUNNHP(2,JZ,JP,JY,JX),RUNNOP(2,JZ,JP,JY,JX),RUPPOP(2,JZ,JP,JY,JX)&
     &,RUNNBP(2,JZ,JP,JY,JX),RUNNXP(2,JZ,JP,JY,JX),RUPPBP(2,JZ,JP,JY,JX)&
     &,RNH3Z(JP,JY,JX),RNH3B(JC,JP,JY,JX),WFR(2,JZ,JP,JY,JX)            &
     &,RHGFLA(2,JZ,JP,JY,JX),RHGDFA(2,JZ,JP,JY,JX),H2GA(2,JZ,JP,JY,JX)  &
     &,H2GP(2,JZ,JP,JY,JX),RH2GZ(JP,JY,JX),RUPP1P(2,JZ,JP,JY,JX)        &
     &,RUPP1B(2,JZ,JP,JY,JX)

