      COMMON/BLK1CP/WTSHT(JP,JY,JX),WTLF(JP,JY,JX),WTSHE(JP,JY,JX)      &
     &,WTSTK(JP,JY,JX),WVSTK(JP,JY,JX),WTRSV(JP,JY,JX),WTHSK(JP,JY,JX)  &
     &,WTEAR(JP,JY,JX),WTGR(JP,JY,JX),WTLS(JP,JY,JX),WVSTKB(JC,JP,JY,JX)&
     &,CPOOL(JC,JP,JY,JX),WTLSB(JC,JP,JY,JX),WTSHTB(JC,JP,JY,JX)        &
     &,WTLFB(JC,JP,JY,JX),WTSHEB(JC,JP,JY,JX),WTSTKB(JC,JP,JY,JX)       &
     &,WTRSVB(JC,JP,JY,JX),WTHSKB(JC,JP,JY,JX),WTEARB(JC,JP,JY,JX)      &
     &,WTGRB(JC,JP,JY,JX),WTRTA(JP,JY,JX),WGLF(0:25,JC,JP,JY,JX)        &
     &,WGSHE(0:25,JC,JP,JY,JX),WGNODE(0:25,JC,JP,JY,JX)                 &
     &,HTSTZ(JP,JY,JX),ARLF(0:25,JC,JP,JY,JX),HTSHE(0:25,JC,JP,JY,JX)   &
     &,HTNODE(0:25,JC,JP,JY,JX),ARLFB(JC,JP,JY,JX),CCPLNP(JP,JY,JX)     &
     &,GRNOB(JC,JP,JY,JX),GRNXB(JC,JP,JY,JX),GRNO(JP,JY,JX)             &
     &,GRWTB(JC,JP,JY,JX),ARLFV(JZ,JP,JY,JX),WGLFL(JZ,0:25,JC,JP,JY,JX) &
     &,ARLFL(JZ,0:25,JC,JP,JY,JX),WSLF(0:25,JC,JP,JY,JX)                &
     &,WSSHE(0:25,JC,JP,JY,JX),CSNC(4,0:1,0:JZ,JP,JY,JX),CNET(JP,JY,JX) &
     &,PP(JP,JY,JX),WGLFV(JZ,JP,JY,JX)                                  &
     &,CPOOLP(JP,JY,JX),CCPOLP(JP,JY,JX),CCPOLB(JC,JP,JY,JX)            &
     &,ARSTV(JZ,JP,JY,JX),WTSTDG(4,JP,JY,JX),WTSTG(JP,JY,JX)            &
     &,CPOLNB(JC,JP,JY,JX),CPOLNP(JP,JY,JX),HTNODX(0:25,JC,JP,JY,JX)    &
     &,WTNDB(JC,JP,JY,JX)
