      COMMON/BLK14/CARBN(JP,JY,JX),TCUPTK(JP,JY,JX),TCSNC(JP,JY,JX)     &
     &,TZUPTK(JP,JY,JX),TZSNC(JP,JY,JX),TPUPTK(JP,JY,JX),TPSNC(JP,JY,JX)&
     &,TZUPFX(JP,JY,JX),TCO2T(JP,JY,JX),BALC(JP,JY,JX),BALN(JP,JY,JX)   &
     &,BALP(JP,JY,JX),HCSNC(JP,JY,JX),HZSNC(JP,JY,JX),HPSNC(JP,JY,JX)   &
     &,HCUPTK(JP,JY,JX),HZUPTK(JP,JY,JX),HPUPTK(JP,JY,JX),ZNPP(JP,JY,JX)&
     &,TCSN0(JP,JY,JX),CTRAN(JP,JY,JX),RNH3C(JP,JY,JX),RSETC(JP,JY,JX)  &
     &,RSETN(JP,JY,JX),RSETP(JP,JY,JX),HVSTC(JP,JY,JX),HVSTN(JP,JY,JX)  &
     &,HVSTP(JP,JY,JX),THVSTC(JP,JY,JX),THVSTN(JP,JY,JX),TNH3C(JP,JY,JX)&
     &,THVSTP(JP,JY,JX),TCO2A(JP,JY,JX),VCO2F(JP,JY,JX),VCH4F(JP,JY,JX) &
     &,VOXYF(JP,JY,JX),VNH3F(JP,JY,JX),VN2OF(JP,JY,JX),VPO4F(JP,JY,JX)  &
     &,TZSN0(JP,JY,JX),TPSN0(JP,JY,JX)
