      COMMON/BLK1P/WTSHP(JP,JY,JX),PPOOLP(JP,JY,JX),WTLFP(JP,JY,JX)     &
     &,WTSHEP(JP,JY,JX),WTSTKP(JP,JY,JX),WTRSVP(JP,JY,JX)               &
     &,WTHSKP(JP,JY,JX),WTEARP(JP,JY,JX),WTGRNP(JP,JY,JX)               &
     &,WTSHTP(JC,JP,JY,JX),WTLFBP(JC,JP,JY,JX),WTSHBP(JC,JP,JY,JX)      &
     &,WTSTBP(JC,JP,JY,JX),WTRSBP(JC,JP,JY,JX),WTHSBP(JC,JP,JY,JX)      &
     &,WTEABP(JC,JP,JY,JX),WTGRBP(JC,JP,JY,JX),PPOOL(JC,JP,JY,JX)       &
     &,WGLFP(0:25,JC,JP,JY,JX),WGSHP(0:25,JC,JP,JY,JX)                  &
     &,WGNODP(0:25,JC,JP,JY,JX),WGLFLP(JZ,0:25,JC,JP,JY,JX)             &
     &,PPOOLR(2,JZ,JP,JY,JX),CPPOLR(2,JZ,JP,JY,JX),PPOOLN(JZ,JP,JY,JX)  &
     &,PSNC(4,0:1,0:JZ,JP,JY,JX),CFOPP(0:5,4,JP,JY,JX),WTRTP(JP,JY,JX)  &
     &,WTRT1P(2,JZ,JC,JP,JY,JX),WTRT2P(2,JZ,JC,JP,JY,JX),WTNDP(JP,JY,JX)&
     &,WTNDLP(JZ,JP,JY,JX),CPPOLP(JP,JY,JX),CPPOLB(JC,JP,JY,JX)         &
     &,RTWT1P(2,JC,JP,JY,JX),WTSTDP(4,JP,JY,JX),WTSTGP(JP,JY,JX)        &
     &,PPOLNB(JC,JP,JY,JX),PPOLNP(JP,JY,JX),WTNDBP(JC,JP,JY,JX)
