      COMMON/BLK18/ARLFC(JY,JX),ARSTC(JY,JX),TEVAPP(JY,JX),TEVAPC(JY,JX)&
     &,TENGYC(JY,JX),THFLXC(JY,JX),TUPWTR(0:JZ,JY,JX),TUPHT(0:JZ,JY,JX) &
     &,TVOLWP(JY,JX),TCOFLA(JZ,JY,JX),TOXFLA(JZ,JY,JX),TCHFLA(JZ,JY,JX) &
     &,TN2FLA(JZ,JY,JX),TNHFLA(JZ,JY,JX),TLCO2P(JZ,JY,JX),GPP(JY,JX)    &
     &,TLOXYP(JZ,JY,JX),TLCH4P(JZ,JY,JX),TLN2OP(JZ,JY,JX),RECO(JY,JX)   &
     &,TLNH3P(JZ,JY,JX),TCO2S(JZ,JY,JX),TUPOXS(JZ,JY,JX)                &
     &,TUPCHS(JZ,JY,JX),TUPN2S(JZ,JY,JX),TUPN3S(JZ,JY,JX)               &
     &,TUPNH4(JZ,JY,JX),TUPNO3(JZ,JY,JX),TUPH2P(JZ,JY,JX)               &
     &,TUPN3B(JZ,JY,JX),TUPNHB(JZ,JY,JX),TUPNOB(JZ,JY,JX)               &
     &,TUPH2B(JZ,JY,JX),TUPNF(JZ,JY,JX),CSNT(4,0:1,0:JZ,JY,JX)          &
     &,ZSNT(4,0:1,0:JZ,JY,JX),PSNT(4,0:1,0:JZ,JY,JX)                    &
     &,TDFOMC(0:4,JZ,JY,JX),TDFOMN(0:4,JZ,JY,JX),TDFOMP(0:4,JZ,JY,JX)   &
     &,TCO2Z(JY,JX),TOXYZ(JY,JX),TCH4Z(JY,JX),TN2OZ(JY,JX),TNH3Z(JY,JX) &
     &,TCO2P(JZ,JY,JX),TUPOXP(JZ,JY,JX),THRMC(JY,JX),TCNET(JY,JX)       &
     &,ZCSNC(JY,JX),ZZSNC(JY,JX),ZPSNC(JY,JX),WGLFT(JC,JY,JX)           &
     &,ARLFT(JC,JY,JX),ARSTT(JC,JY,JX),ARLSS(JY,JX),RTDNT(JZ,JY,JX)     &
     &,TCCAN(JY,JX),TUPH1P(JZ,JY,JX),TUPH1B(JZ,JY,JX)
