      COMMON/BLK22C/XMGHBS(JY,JX),XMGSBS(JY,JX),XNACBS(JY,JX)
     2,XNASBS(JY,JX),XKASBS(JY,JX),XH0PBS(JY,JX),XH1PBS(JY,JX)
     3,XH3PBS(JY,JX),XF1PBS(JY,JX),XF2PBS(JY,JX),XC0PBS(JY,JX)
     4,XC1PBS(JY,JX),XC2PBS(JY,JX),XM1PBS(JY,JX)
