      COMMON/BLK22C/XMGHBS(JS,JY,JX),XMGSBS(JS,JY,JX)
     2,XNACBS(JS,JY,JX),XNASBS(JS,JY,JX),XKASBS(JS,JY,JX)
     3,XH0PBS(JS,JY,JX),XH3PBS(JS,JY,JX),XF1PBS(JS,JY,JX)
     4,XF2PBS(JS,JY,JX),XC0PBS(JS,JY,JX),XC1PBS(JS,JY,JX)
     5,XC2PBS(JS,JY,JX),XM1PBS(JS,JY,JX)

