      COMMON/BLK8B/ALBX(JY,JX),DPTH(JZ,JY,JX),DLYR(3,0:JZ,JY,JX)
     2,POROS(0:JZ,JY,JX),PSL(0:JZ,JY,JX),FCL(0:JZ,JY,JX)
     3,WPL(0:JZ,JY,JX),PSD(0:JZ,JY,JX),FCD(0:JZ,JY,JX),VOLX(0:JZ,JY,JX)
     4,VOLY(0:JZ,JY,JX),BKVL(0:JZ,JY,JX),SRP(0:JZ,JY,JX),FORGC,FVLWB 
     5,FCH4F,CNRH(0:4),CPRH(0:4),DIST(3,JD,JV,JH),XDPTH(3,JZ,JY,JX)
     6,POROQ,TFND(0:JZ,JY,JX),FCI,WPI,POROS0(JY,JX)
     7,PSIMS(JY,JX),PSIMX(JY,JX),PSIMN(JY,JX),PSISD(JY,JX),PSIMD(JY,JX)
     8,SAND(JZ,JY,JX),SILT(JZ,JY,JX),CLAY(JZ,JY,JX),CDPTHZ(0:JZ,JY,JX)
     9,DPTHZ(JZ,JY,JX),AREA(3,0:JZ,JY,JX),DISP(3,JD,JV,JH),OXKM,PSIHY
     1,DLYRI(3,0:JZ,JY,JX),OMCI(3,0:4),OMCF(7),OMCA(7)
     2,VOLAI(0:JZ,JY,JX),IUTYP(JY,JX),IXTYP(2,JY,JX)
     3,IYTYP(0:2,366,JY,JX)

