      COMMON/BLK8B/ALBX(JY,JX),DPTH(JZ,JY,JX),DLYR(3,0:JZ,JY,JX)
     2,POROS(0:JZ,JY,JX),PSL(JZ,JY,JX),FCL(JZ,JY,JX)
     3,WPL(JZ,JY,JX),PSD(JZ,JY,JX),FCD(JZ,JY,JX),VOLX(0:JZ,JY,JX)
     4,VOLY(0:JZ,JY,JX),BKVL(0:JZ,JY,JX),SRP(JZ,JY,JX),FORGC,FVLWB,FCH4F
     5,CNRH(0:4),CPRH(0:4),DIST(3,JD,JV,JH),XDPTH(3,JZ,JY,JX)
     6,POROQ(0:JZ,JY,JX),TFND(0:JZ,JY,JX),FCI,WPI
     7,PSIMS(JY,JX),PSIMX(JY,JX),PSIMN(JY,JX),PSISD(JY,JX),PSIMD(JY,JX)
     8,SAND(JZ,JY,JX),SILT(JZ,JY,JX),CLAY(JZ,JY,JX),CDPTHZ(0:JZ,JY,JX)
     9,DPTHZ(JZ,JY,JX),AREA(3,0:JZ,JY,JX),DISP(3,JD,JV,JH),OXKM,PSIHY
     1,DLYRI(3,0:JZ,JY,JX),OMCI(3,0:4),OMCF(7),OMCA(7)
     2,VOLAI(0:JZ,JY,JX),IUTYP(JY,JX),IXTYP(2,JY,JX)
     3,IYTYP(0:2,366,JY,JX)

