      COMMON/BLK9A/VCMX(JP,JY,JX),VOMX(JP,JY,JX),VCMX4(JP,JY,JX)        &
     &,XKCO2(JP,JY,JX),XKO2(JP,JY,JX),XKCO24(JP,JY,JX)                  &
     &,RUBP(JP,JY,JX),PEPC(JP,JY,JX),ETMX(JP,JY,JX),CHL(JP,JY,JX)       &
     &,CHL4(JP,JY,JX),XRNI(JP,JY,JX),XRLA(JP,JY,JX),CTC(JP,JY,JX)       &
     &,FCO2(JP,JY,JX),WDLF(JP,JY,JX),PB(JP,JY,JX),SLA1(JP,JY,JX)        &
     &,SSL1(JP,JY,JX),SNL1(JP,JY,JX),VRNL(JC,JP,JY,JX),HTC(JP,JY,JX)    &
     &,SSTX(JP,JY,JX),FNOD(JP,JY,JX),DMLF(JP,JY,JX),DMSHE(JP,JY,JX)     &
     &,DMSTK(JP,JY,JX),DMRSV(JP,JY,JX),DMHSK(JP,JY,JX),DMEAR(JP,JY,JX)  &
     &,DMGR(JP,JY,JX),DMRT(JP,JY,JX),DMND(JP,JY,JX),RSMX(JP,JY,JX)      &
     &,RCMX(JP,JY,JX),RSMH(JP,JY,JX),CNLF(JP,JY,JX),CNSHE(JP,JY,JX)     &
     &,CNSTK(JP,JY,JX),CNRSV(JP,JY,JX),CNHSK(JP,JY,JX),CNEAR(JP,JY,JX)  &
     &,CNGR(JP,JY,JX),CNRT(JP,JY,JX),CNND(JP,JY,JX),CPLF(JP,JY,JX)      &
     &,CPSHE(JP,JY,JX),CPSTK(JP,JY,JX),CPRSV(JP,JY,JX),CPHSK(JP,JY,JX)  &
     &,CPEAR(JP,JY,JX),CPGR(JP,JY,JX),CPRT(JP,JY,JX),CPND(JP,JY,JX)     &
     &,CLASS(4,JP,JY,JX),CF(JP,JY,JX),XDL(JP,JY,JX),XPPD(JP,JY,JX)      &
     &,CFI(JP,JY,JX),XTLI(JP,JY,JX),OSMO(JP,JY,JX),RCS(JP,JY,JX)        &
     &,STMX(JP,JY,JX),SDMX(JP,JY,JX),GRMX(JP,JY,JX),PPZ(JP,JY,JX)       &
     &,GRDM(JP,JY,JX),GFILL(JP,JY,JX),SDPTHI(JP,JY,JX),VRNX(JC,JP,JY,JX)&
     &,CFX(JP,JY,JX)
