      COMMON/BLK9B/OFFST(JP,JY,JX),RRAD1M(2,JP,JY,JX),RRAD2M(2,JP,JY,JX)&
     &,TCZ(JP,JY,JX),PORT(2,JP,JY,JX),PR(JP,JY,JX),RSRR(2,JP,JY,JX)     &
     &,RSRA(2,JP,JY,JX),PTSHT(JP,JY,JX),UPMXZH(2,JP,JY,JX)              &
     &,UPKMZH(2,JP,JY,JX),UPMNZH(2,JP,JY,JX),UPMXZO(2,JP,JY,JX)         &
     &,UPKMZO(2,JP,JY,JX),UPMNZO(2,JP,JY,JX),UPMXPO(2,JP,JY,JX)         &
     &,UPKMPO(2,JP,JY,JX),UPMNPO(2,JP,JY,JX),RRADP(2,JP,JY,JX)          &
     &,CNRTS(JP,JY,JX),CPRTS(JP,JY,JX),ALBR(JP,JY,JX),ALBP(JP,JY,JX)    &
     &,TAUR(JP,JY,JX),TAUP(JP,JY,JX),ABSR(JP,JY,JX),ABSP(JP,JY,JX)      &
     &,TCX(JP,JY,JX),ZTYPI(JP,JY,JX),TCZD,TCXD                          &
     &,ZTYP(JP,JY,JX),ICTYP(JP,JY,JX),IGTYP(JP,JY,JX),ISTYP(JP,JY,JX)   &
     &,IDTYP(JP,JY,JX),NNOD(JP,JY,JX),INTYP(JP,JY,JX),IWTYP(JP,JY,JX)   &
     &,IPTYP(JP,JY,JX),IBTYP(JP,JY,JX),IRTYP(JP,JY,JX),MY(JP,JY,JX)
