      COMMON/BLKC/DRAD(12),DTMPX(12),DTMPN(12),DHUM(12),DPREC(12)       &
     &,DIRRI(12),DWIND(12),DCO2E(12),DCN4R(12),DCNOR(12),TDIRI(JY,JX,12)&
     &,TDTPX(JY,JX,12),TDTPN(JY,JX,12),TDRAD(JY,JX,12),TDHUM(JY,JX,12)  &
     &,TDPRC(JY,JX,12),TDWND(JY,JX,12),TDCO2(JY,JX,12),TDCN4(JY,JX,12)  &
     &,TDCNO(JY,JX,12),TAREA,XDIM,XCORP(JY,JX),ZERO,ZERO2,ZEROS(JY,JX)  &
     &,ZEROP(JP,JY,JX),ZEROQ(JP,JY,JX),ZEROL(JP,JY,JX),XH(3,0:JZ,JY,JX) &
     &,XHS(JY,JX),XNPH,XNPT,XNPG,XNPR,XNPD,ALAT(JY,JX),DOY,DYLM(JY,JX)  &
     &,XNPS,XNPY,XNPZ,XNPQ,XNPV,ZEROS2(JY,JX),IFLGV(JY,JX)              &
     &,IGO,IFLGS(JY,JX),IFNHB(JY,JX),IFNOB(JY,JX),IFPOB(JY,JX)          &
     &,IWTHR(2),IDAYR,IYRC,IYRR,NYR,ITERM,IFIN,ISALTG                   &
     &,IERSNG,NCN(JY,JX),NPX,NPY,NPH,NPT,NPG,ICLM,IMNG,IFLGW            &
     &,NPR,NPS,JOUT,IOUT,KOUT,IOLD,ILAST,IRUN,IBEGIN,ISTART,IEND        &
     &,ISOIL(0:4,JZ,JY,JX),LYRX,LYRC,LSG(JZ,JY,JX),NP(JY,JX)            &
     &,NP0(JY,JX),IFLGI(JP,JY,JX),IFLGC(JP,JY,JX),IETYP(JY,JX)
