      COMMON/BLKC/DRAD(12),DTMPX(12),DTMPN(12),DHUM(12),DPREC(12)
     2,DIRRI(12),DWIND(12),DCO2E(12),DCN4R(12),DCNOR(12),TDIRI(JY,JX,12)
     3,TDTPX(JY,JX,12),TDTPN(JY,JX,12),TDRAD(JY,JX,12),TDHUM(JY,JX,12)
     4,TDPRC(JY,JX,12),TDWND(JY,JX,12),TDCO2(JY,JX,12),TDCN4(JY,JX,12)
     5,TDCNO(JY,JX,12),TAREA,XDIM,XCORP(JY,JX),ZERO,ZERO2,ZEROS(JY,JX)
     6,ZEROP(JP,JY,JX),ZEROQ(JP,JY,JX),ZEROL(JP,JY,JX)
     7,XNPH,XNPT,XNPG,XNPR,XNPD,ALAT(JY,JX),DOY,DYLM(JY,JX)
     8,XNPS,XNPY,XNPZ,XNPQ,XNPV,ZEROS2(JY,JX),IFLGV(JY,JX)
     8,IGO,IFLGS(JY,JX),IFNHB(JY,JX),IFNOB(JY,JX),IFPOB(JY,JX)
     9,IWTHR(2),IDAYR,IYRC,IYRR,NYR,ITERM,IFIN,ISALTG
     1,IERSNG,NCN(JY,JX),NPX,NPY,NPH,NPT,NPG,ICLM,IMNG,IFLGW
     2,NPR,NPS,JOUT,IOUT,KOUT,IOLD,ILAST,IRUN,IBEGIN,ISTART,IEND
     3,ISOIL(0:4,JZ,JY,JX),LYRX,LYRC,LSG(JZ,JY,JX),NP(JY,JX)
     4,NP0(JY,JX),IFLGI(JP,JY,JX),IFLGC(JP,JY,JX),IETYP(JY,JX)

